### ISSUE TITLE
Add I18n config for background

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1003]
- Add config I18n to background
- Show transcript messages from background

**Comment by Quangdm-cdm** [comment]
@sokol142 @ThaoNguyen998 this issue need update from background. @S2kael please fix this bug in background

**Comment by Sokol142196** [comment]
> @sokol142 @ThaoNguyen998 this issue need update from background. @S2kael please fix this bug in background

Thanks @Quangdm-cdm, @S2kael please fixed this bug in the issue https://github.com/Koniverse/SubWallet-Extension/issues/1915

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-215-1024-merge-2023-09-14T11-32-51.ipa
Device test: IP 11

- [ ] Do not save config Language in case re-open app
https://drive.google.com/file/d/1J-mY6pWGGpZ045G1W4fuBa7r-xjnO4an/view?usp=sharing

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.0(217)
Device test: IP 11

Validation passed.
