### ISSUE TITLE
Show duplicate message in case of incorrect biometrics entered too many times on Android

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1004]
**Describe the bug**
Version test: v1.1 (213)
Device test: Samsung S20 FE 5G

**To reproduce the bug**
Steps: 
1. Open Subwallet app 
2. Perform transaction have required master password
3. Input incorrect biometrics too many times 
4. Obserse the displayed screen

Actual: Show duplicate message

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/8adbb4be-6e31-4f83-8603-247a91f873a7

**Comment by Sokol142196** [comment]
Same as https://github.com/Koniverse/SubWallet-Mobile/issues/1170
