### ISSUE TITLE
Support fiat on-ramp with Coinbase Pay on mobile app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1005]
**Describe the task**
Support fiat on-ramp with Coinbase Pay on mobile app (both iOS and Android)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-215-1025-merge-2023-09-15T04-38-44.ipa

Please check:

- [ ] An error occurs when buying token with Banxa

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/bebd7f9c-20d2-4ae8-a6ca-85289189e6dd)


- [ ] Incorrect token when buy token with Transak 
  - DOCK -> Actual show ETH
  - BUSD -> Actual show ETH

- [ ] Update logo style

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/b73a84d3-2b4f-4bff-a5b0-2d826965936f)


- [ ] Only show tokens that integrated
  - Actual: Show tokens that not integrate
  - Expect: Only show tokens that integrated

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/6bbc4b76-25f2-433a-b0c2-e1153c78b601)

- [ ] Don't navigate to service page when click on Buy token button with Android device

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-215-1025-merge-2023-09-18T09-55-12.ipa
Device test: IP 11
Validation passed.
