### ISSUE TITLE
Upgrade React Native 0.72.4

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1007]
- React Native 0.72.4 has interop layer could lead big impact with performance, so we upgrade to this version first
- What to test:
  + Interaction with native components: Camera, biometry, upload file, browser,...
  + Performance in all list view
  + Items with image

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-221-1008-merge-2023-09-27T07-54-17.apk
Device test: Samsung S20 FE 5G

Validation passed.
