### ISSUE TITLE
Errors when authenticating using biometrics

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1009]
**Describe the bug**
- [ ] Show biometric popup two times when import json -> Refer: https://github.com/Koniverse/SubWallet-Mobile/issues/1013
- [x] Show migrate biometric popup again if user doesn't complete yet
- [x] Handling case of reset master password in Keychain when reset account

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.0(215)
Device test: IP 11

Validation passed.
