### ISSUE TITLE
Show error message when cancel transaction

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1010]
**Describe the bug**
Show error message when cancel transaction

**Actual:** When user cancel any transaction then show error message "Rejected by user"

![Image](https://user-images.githubusercontent.com/130966515/266762398-2e107ee3-168f-459f-acfd-5f71514f827d.png)

**Expect:** Do not show message

**Comment by nguyenduythuc** [comment]
Will be fixed in #1009

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.0(215)
Device test: IP 11

Validation passed.
