### ISSUE TITLE
Update web-runner and chain list (V1.1.11)

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1012]
**Describe the task**
Update web-runner and chain list (V1.1.11): https://github.com/Koniverse/SubWallet-Extension/releases/tag/v1.1.11

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-215-1015-merge-2023-09-11T05-57-14.ipa
Devices test: IP 11

Validation passed.
