### ISSUE TITLE
Do not show notify in case of incorrect biometric authentication exceeding the allowed number of attempts

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1016]
**Describe the bug**
Do not display a warning popup in case of incorrect biometric authentication exceeding the allowed number of attempts when:

- [x] Enable FaceID/ Touch ID
  - Actual: Do not show notification and can not enable the FaceID/ Touch ID
  - Expect: Show notification

- [x] Change master password
  - Actual: Do not show notification, standing on the Change password screen
  - Expect: Show notification

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-220-1042-merge-2023-09-26T09-18-16.ipa
Device test: IP 11

@nguyenduythuc Please re-check this bug when Enable Face ID/ Touch ID on IOS

**Comment by nguyenduythuc** [comment]
Hi @ThaoNguyen998, this issue based on the response of keychain library, we don't have specific message to this case and this case has low priority so we could be closed this issue.
