### ISSUE TITLE
Re-check network's logo on the crowdloans tab

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1017]
Describe the task
Re-check network's logo on the crowdloans tab
- Actual: Do not show logo of the Composable Finance

![Image](https://user-images.githubusercontent.com/130966515/266977176-05b101b9-416e-432f-b978-999ef88ff67a.png)

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.0(218)
Devices test: IP 11, Samsung S20 FE 5G

Validation passed.
