### ISSUE TITLE
Need to auto-focus the master password field on Android device

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1020]
**Describe the task**
Need to auto-focus the master password field on Android device

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-220-1038-merge-2023-09-25T08-27-09.apk
Device test: Mi 8 Lite

- [ ] Do not auto-focus in case cancel biometric

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-220-1038-merge-2023-09-25T08-27-09.apk
Device test: IP 11

Validation passed.
