### ISSUE TITLE
Show incorrect message in case add new provider

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1045]
**Describe the bug**
Show incorrect message in case add new provider

**To reproduce the behavior**
Steps:
1. Go to the add new provider screen
2. Input the invalid provider (provider of another network)
3. Click on save button then observe the message displayed

**Actual:** Show incorect message 
- Message: This chain has already been added

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/4369c952-6fae-435e-a792-7e2dcf92199d)

**Expect:** Show message: This provider is not for this network

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-221-1044-merge-2023-09-27T11-14-57.ipa
Device test: IP 11

@Quangdm-cdm Please re-check this issue: Show incorrect message in case add an existing provider
Actual: Show message "This provider is not for this network"
Expect: Show message "This provider has already been added"

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-221-1044-merge-2023-09-28T08-39-06.apk
Device test: Samsung S20 FE 5G

Validation passed.
