### ISSUE TITLE
Error page in case reset wallet

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1047]
Describe the bug
Version test: v1.1.0(211)

To reproduce the bug 
Steps:
1. Go to Login screen 
2. Touch Forget account -> Erase all
3. Observe the displayed screen

Actual: Error page
Expect: Navigate to Welcome screen

**Comment by nguyenduythuc** [comment]
@ThaoNguyen998 Can't reproduce this issue, i'll move this task to follow up

**Comment by nguyenduythuc** [comment]
This issue has been open for a long time, i'll close this issue
