### ISSUE TITLE
Improve deeplink (Add more deeplink type)

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Mobile#1049]

**Comment by saltict** [comment]
- [ ] Support deeplink for specific token or group of token
- [ ] Deeplink to navigate NFT Collection
- [ ] Deeplink for staking, crowdloan....

**Comment by Quangdm-cdm** [comment]
Some deeplink to check: 

-[ ] Token detail: subwallet://home/main/tokens/token-groups-detail?slug=DOT-Polkadot

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-223-1060-merge-2023-10-09T10-14-35.ipa
Device test: IP 11

- [ ] Re-check deeplink on Android
- [ ] Navigate incorrect screen when add/ delete account in case open app with deeplink Token detail
https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/ERj-3pHXN2VAu8wgl_RjG1QBsKpta5S31MQ4UGbfUk7-Aw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0RpcmVjdCJ9fQ&e=wBIniW
- [ ] The scan QR doesn't close automatic
- [ ] Bug when open deeplink NFT detail

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/1cfcbe68-ceaf-4f0d-82d9-3de5a9adcefc

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-223-1060-merge-2023-10-12T02-54-15.ipa

Validation passed with deep link Token Detail
