### ISSUE TITLE
Swipe to delete/copy account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1066]
**Describe the task**
Swipe to delete/copy account
- Link design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=11707-442551&mode=design&t=6gxKjYxpUL6OiuKg-4

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-226-1093-merge-2023-10-21T11-25-29.apk
Device test: Samsung S20 FE 5G

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/fa45d1a6-11a4-4929-9da8-43ae8cfd166f)
