### ISSUE TITLE
Add banner crowdloan unlock in Crowdloan tab

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1068]
**Describe the task**
Add banner crowdloan unlock in Crowdloan tab
- Link design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=11896-170808&mode=design&t=RZ2sIMG6ri95GbZn-4

When click on banner:
- If have account in webapp -> Redirect user to the earning screen: https://web.subwallet.app/home/earning
- If have no account in webapp -> Redirect user to the earning-demo screen: https://web.subwallet.app/earning-demo

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-224-1078-merge-2023-10-16T11-51-48.ipa
Device test: IP 11

@Quangdm-cdm Please re-check this issue: 
- [ ] Do not show banner when update version
- [ ] Do not show banner when install app

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-226-1078-merge-2023-10-21T08-52-52.apk
Device test: Samsung S20 FE 5G

Validation passed. 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/0f050676-edc0-48b3-a784-a457bae48a84)


![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/499bf4af-c910-46ea-adae-9a0425b7ba0d)
