### ISSUE TITLE
In-app broser DApp connections status

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Mobile#107]
Show connection information on in-app browser like the extension version
<img width="458" alt="image" src="https://user-images.githubusercontent.com/11567273/193496185-5929bc70-26f9-4de2-a961-471a6ab9f9a3.png">

<img width="460" alt="image" src="https://user-images.githubusercontent.com/11567273/193496161-58ece61b-86c1-4460-9ad8-713326872aa1.png">

<img width="459" alt="image" src="https://user-images.githubusercontent.com/11567273/193496085-f9489c8f-e322-4e9d-bbe7-9c5aa25b6b9a.png">

**Comment by sokol142** [comment]
Update follow new UI: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3647-409422&t=Qx4ke3j8wTGtNYjo-4

Resolve in https://github.com/Koniverse/SubWallet-Mobile/issues/692
