### ISSUE TITLE
New image slider for browser tab

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1072]
- Show images as slider
- Image clickable
- Infinite loop
- Small indicator

**Comment by ThaoNguyen998** [comment]
Version test: PR 1134 12:27 08/11/2023
Device test: IP 11

Validation passed.
https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/EZyPs-HHBetFhDz86ZDuwp0Bn_W1J8c_7vlx4GjqFd1U5g?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0RpcmVjdCJ9fQ&e=UEzdRI
