### ISSUE TITLE
Update buy token ordering

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1076]
**Describe the task**
Update list token when buy token: 
- Prioritize DOT token at the top of the list for Substrate account
- Prioritize ETH (Ethereum) token at the top of the list for EVM account

**Comment by nguyenduythuc** [comment]
Will be pushed in #1074

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-224-1077-merge-2023-10-13T07-49-50.ipa
Device test: IP 11

Validation passed.
