### ISSUE TITLE
Do not send Sub0 NFT

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1088]
**Describe the bug**
Do not send Sub0 NFT
- Check with address 5DcW42REUeTLySnuhG3ob8H6SPoVYMk73uZ1unKfRTg8hJdB
_Version test: v1.1.3 (226)_

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/a90249de-cf14-4a02-a111-3dc432a85380)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-227-1099-merge-2023-10-24T02-28-51.apk
Device test: Samsung S20 FE 5G

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/8944ed22-3458-4595-b962-f9b8d774d448)
