### ISSUE TITLE
Convert I18n language files from TS to JSON

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1091]
- Convert format of language files from .ts to .json
- Use formatString to indexing params instead of arrow function

** This would impact all language of the app

**Comment by ThaoNguyen998** [comment]
Version test: 
Device test: Samsung S20 FE 5G

- [ ] Crash app when unstake

**Comment by ThaoNguyen998** [comment]
Version test: PR #1098 16:12 26/10/2023
Device test:  Samsung S20 FE 5G

Validation passed.
