### ISSUE TITLE
The wallet connect confirmation is unable to be shown after opening the app from the browser

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1094]
**Describe the bug**
Version test: v1.1.0(215)
Device test: IP 11

To reproduce the bug
Steps: 
1. Perform sign transactions continuously used Wallet connect
2. Observe the displayed screen
3. Close app and re-open

Actual: https://bit.ly/46g05Wm
In step 2: Do not show confirmation modal
In step 3: Show the confirmation modal

Expect: Show confirmation after the request

**Comment by nguyenduythuc** [comment]
This was fixed by update wallet connect version in package.json
