### ISSUE TITLE
Update the Token detail screen for mobile app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1095]
**Describe the task**
Update the Token detail screen
- Design link: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=11742-356846&mode=design&t=eXhEkcONDhlXK3mv-4
- Component link: https://www.figma.com/file/mfCcK60D4OWv42MlVvrJF4/SubWallet-UI-Base-1.0.1?type=design&node-id=3590-23741&mode=design&t=MhTv9PnES3XK9qc2-4

**Comment by ThaoNguyen998** [comment]
Version test: PR #1220 10:28 08/12/2023
Device test: Samsung S20 FE 5G

- [ ] UI bug

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/f25bb5ee-9159-4ad1-afa7-4422ec2f6b93)

**Comment by ThaoNguyen998** [comment]
Version test: PR #1220 10:30 11/12/2023
Device test: IP 11
Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/6e1d522a-2065-4920-b721-ca98405c0c54)
