### ISSUE TITLE
Mission pools feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1096]
**Describe the task**
Implement mission pool
- Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=12114-203467&mode=design&t=M9dTXPQ5OHGlgkt5-4

**Comment by ThaoNguyen998** [comment]
Version test: PR #1107 15:28 31/10/2023
Device test: Samsung S20 FE 5G
@Quangdm-cdm Please re-check this issue

- [ ] Error page when touch Browser tab

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/5907274d-1fdf-4e5a-80f0-815b39a288af

**Comment by ThaoNguyen998** [comment]
Version test: PR #1107 16:21 01/11/2023
Device test: IP 11

- [ ] Re-check number of Polkadot networks on detail mission pool

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/e9f53aaa-462d-4eeb-a856-c19e564086d0)

**Comment by ThaoNguyen998** [comment]
Version test: PR 1107 18:28 01/11/23
Device test: MI 8 Lite

UI bug Mission pool

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/9026b7d1-65e3-4cad-bbe9-738f62967b89

**Comment by ThaoNguyen998** [comment]
Version test: PR 1107 11:23 03/11/2023
Device test: Samsung S20 FE 5G

Validation passed.
https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/EUYP7RNhMU5Fhh7fEaJsDosBI7EL4UOCxbgrP0CkQ5nr3w?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0RpcmVjdCJ9fQ&e=6FbFrL
