### ISSUE TITLE
Add "Token Name" to the Token Details and Import Token screen for mobile app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1097]
**Describe the task**
Add "Token Name" to the screens:
- [x] Token Details: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3312-238367&mode=design&t=M9dTXPQ5OHGlgkt5-4
- [x] Import Token: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=1901-54480&mode=design&t=M9dTXPQ5OHGlgkt5-4
- [x] Select token: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=1774-56639&mode=design&t=M9dTXPQ5OHGlgkt5-4

**Comment by ThaoNguyen998** [comment]
Version test: 
Device test: Samsung S20 FE 5G 

- [ ] UI bug

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/78dbae59-fc9a-4fde-90c6-ba34b5876db7)

**Comment by ThaoNguyen998** [comment]
Version test: PR #1100 14:59 30/10/2023
Device test: Samsung S20 FE 5G

@Quangdm-cdm Please re-check Token name when buy token 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/eb9e80ed-dcd3-4576-b6e7-b0a034415843)

**Comment by ThaoNguyen998** [comment]
Version test: 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/10512f4b-725c-4325-b5d8-4af428405b30)

Device test: Samsung S20 FE 5G

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/5b878d3c-e411-4c6a-967a-5a8cb74e8c90)
