### ISSUE TITLE
Re-check bug can't open app on Redmi note 7

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1103]
Describe the bug
Re-check can't open app on Redmi note 7

To reproduce the bug

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/e2da21d2-4b0b-4ddb-8912-5d161c7e898b

**Comment by Sokol142196** [comment]
Reason: polkadot's code uses new technology. 
Solution: Users need to update Chrome to the latest version
