### ISSUE TITLE
Do not load data in the browser tab

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1105]
**Describe the task**
Do not load data in the browser tab

Version test: v1.1.4 (227) (store version)
- Device test: IP 8 Plus (15.5)
- Notes: Balance, NFT, crowdloans data is normal

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/aaf1d2e2-1232-4bba-b277-047a4f6b6092)

**Comment by nguyenduythuc** [comment]
Already on upgrade ui, @ThaoNguyen998 check it again, thanks!

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.6(231)
Device test: IP 8 Plus, IP 11

I can't reproduce this issue on the newest version -> Close issue
