### ISSUE TITLE
Still enable "Confirm" button although do not select account in case reconnect after unblock dApp

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1115]
**Describe the task**
Still enable "Confirm" button although do not select in case reconnect after unblock dApp

**Reproduce the behavior**
Steps:
1. Go to Browser in app
2. Visit any dApp
3. On the connect wallet confirmation, choose the Block action
4. After blocked successfully, perform unblock
5. Observe the screen displayed

**Actual:** Still enable button Confirm although do not select account
https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/Efk-tJaKTU5Cs8KuIgeljbABEXAJMGbrA5kKM1QB4-DiPA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0RpcmVjdCJ9fQ&e=5d9PAf

**Comment by Sokol142196** [comment]
@ThaoNguyen998 please record this bug for me

**Comment by nguyenduythuc** [comment]
@Quangdm-cdm disable "Confirm" button when no account is selected, thanks!

**Comment by ThaoNguyen998** [comment]
Version test: PR #1117 17:38 03/11/2023
Device test: MI 8 Lite 

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/1cf099f5-c20d-4a5f-8c82-25a015d7b94f)
