### ISSUE TITLE
Bug error page in case upgrade Polkadot vault app

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1116]
**Describe the bug**
Error page in case upgrade Polkadot vault app

**To reproduce the bug**
Device: IP 14 promax

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/250f2f27-92b2-4c89-bea7-bf52cbaa0878)

**Comment by Sokol142196** [comment]
Feedback from user: User changed the device but this issue is still there.
- Notes: User use Nova wallet is normal
![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/0e418db0-d4ec-4289-8333-07f7e36367b2)

**Comment by nguyenduythuc** [comment]
Duplicate with https://github.com/Koniverse/SubWallet-Mobile/issues/1157
