### ISSUE TITLE
Bug show duckduckgo instead of show dapp in browser in case deeplink containing special charactors

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1119]
* What to do:
  - Only check protocol and domain to choose which search engine or domain for browsing
  - Support decode encoded string in browser search

* What to test:
  - Test on both encoded and decoded deeplink
  - Test on both encoded and decoded search string in browser search

**Comment by ThaoNguyen998** [comment]
Version test: PR #1120 11:55 04/10/2023

Device test: IP 11, Samsung S20 FE 5G 

Validation passed in case: 
- Open dapp in app browser
- Token detail

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/6188170d-b88c-4c7d-b347-d714bfc937df
