### ISSUE TITLE
Migrate useTransaction from v1 to v2

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-Mobile#1121]
- [x] Stake
- [x] Unstake
- [x] Withdraw
- [x] CancelUnstake
- [x] ClaimReward
- [x] SendNFT

**Comment by ThaoNguyen998** [comment]
Version test: PR 1132 16:44 07/11/2023 
Device test: Samsung S20 FE 5G

- [ ] Crash app when touch Nominate when Stake
- [ ] Navigate incorrect when click Unstake button

**Comment by ThaoNguyen998** [comment]
Version test: PR https://github.com/Koniverse/SubWallet-Mobile/pull/1132 17:30 15/1/2023
Device test: IP 11

Validation passed in case:
- Transfer
- Stake
- Unstake
- Withdraw
- CancelUnstake
- ClaimReward
- SendNFT
