### ISSUE TITLE
Update token list with static content in Buy Token

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1127]
What to do:
- Get list supported token from static content
- Fix bug do not show Notifi Network icon: https://notifi.network/login

**Comment by ThaoNguyen998** [comment]
Version test: PR #1146 18:19 10/11/2023
Device test: Samsung S20 FE 5G

- [ ] Do not show Notifi Network icon
- [ ] Re-check the list token is sorting by criteria

**Comment by ThaoNguyen998** [comment]
Version test: PR #1146 12:13 15/11/2023
Device test: Samsung S20 FE 5G

Validation passed. 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/3a8fbf6d-6697-406e-873e-0bc6a6ae0b52)
