### ISSUE TITLE
Hide the token of the Inactive chain on mobile app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1133]
**Describe the task**
Hide the token of the Inactive chain

**Actual:** The network is inactive (do not show on UI) but the token of these network still show
- Example: BOBA (Boba base), tSSc (Subspace gemini testnet)
**Expect:** Hide the token of the Inactive chain

**Comment by ThaoNguyen998** [comment]
Version test: PR #1134 18:33 08/11/2023
Device test: Samsung S20 FE 5G

@nguyenduythuc Please re-check this issue
- [ ] Error page in case touch Buy token

**Comment by ThaoNguyen998** [comment]
Version test: PR #1138 14:56 09/11/2023
Device test: Samsung S20 FE 5G

Validation passed.
