### ISSUE TITLE
Improve deeplink(Add more deeplink type) (Round 3)

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1151]
Describe the task

- [x] Fix bug NFT detail: https://mobile.subwallet.app/home/main/nfts/collection?collectionId=Vara%20-%20Coinbase%20collection-0x4341c285413eef39e9bff9f65ab71a29889606172a3ae6b6364a2d7f9f674902&nftId=0x4341c285413eef39e9bff9f65ab71a29889606172a3ae6b6364a2d7f9f674902-12586
- [x]  Crowdloans: https://mobile.subwallet.app/home/main/crowdloans

- [x] Swap

**Comment by ThaoNguyen998** [comment]
- [ ] Do not list Collection after open app with deeplink NFT list -> Issue #1151 

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/1cfcbe68-ceaf-4f0d-82d9-3de5a9adcefc

**Comment by Quangdm-cdm** [comment]
Crowdloan: please use this url: https://mobile.subwallet.app/crowdloans @ThaoNguyen998

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/JJrf2Z
@Quangdm-cdm please re-check bug on comment: https://github.com/Koniverse/SubWallet-Mobile/issues/1151#issuecomment-1809578967

**Comment by Quangdm-cdm** [comment]
> Version test: https://www.diawi.com/qrcode/link/JJrf2Z [@Quangdm-cdm](https://github.com/Quangdm-cdm) please re-check bug on comment: [#1151 (comment)](https://github.com/Koniverse/SubWallet-Mobile/issues/1151#issuecomment-1809578967) Add deeplink for swap

About bug in nft screen: please re-check this bug, i can't reproduce this.
About swap: please use this url to test: https://mobile.subwallet.app/drawer/transaction-action/swap?slug=HDX-HydraDX&chain=hydradx_main

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/U2cGRb
https://www.diawi.com/qrcode/link/52EE2V
Device test: IP 11, S20 FE 5G

Validation passed.
- Support deeplink: Crowdloan, Swap
- Fix bug deeplink NFT detail,  can't open telegram in-app browser
