### ISSUE TITLE
Update network connection status

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1166]
Implement what changes from this issue(https://github.com/Koniverse/SubWallet-Extension/issues/1554) to mobile

Why: User have to go to setting to turn on/turn off chain when connection interrupted.

Todo:
- Auto reconnect when connection interrupted
- If not connected, auto turn off => turn on chain
- if not connected, show popup update chain & suggest change provider

Expect: User don't have to turn on/off chain manually in most time

**Comment by Sokol142196** [comment]
Will resolve in https://github.com/Koniverse/SubWallet-Extension/issues/2504
