### ISSUE TITLE
Crash app in case search dapp

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1168]
**Describe the bug**
Version test: v1.0.11(200)
Devices test: IP 11

**To reproduce the bug**
Steps: 
1. Go to the Browser tab
2. Input search dapp and observe the displayed screen

Actual: Crash app

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/a9f26def-baeb-4683-a793-c366c198892f)

**Comment by Sokol142196** [comment]
Do not reproduce on the v1.1.78
