### ISSUE TITLE
Improve list performance (round 3rd)

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1169]
Describe the task
Improve list performance (round 3rd):

Changes:
- Change from Flatlist to Flashlist
- Memorize callbacks in list
- Define item height for list item

Apply for:
- [x] Token list
- [x] Customize list
- [x] NFT list:  collection, collection detail, network
- [x] Crowdloan list
- [x] dApp list
- [x] Setting - Network list
- [x] Setting - Token list
- [x] Earning list: Position, pools, validator
- [x] Mission pool list

Next step:
- Section list: History, browser home

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.10(240)
Device test: Samsung S20 FE 5G

- [ ] Do not load data mission pool

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/afdda6fb-5c22-4dea-98e3-04d38c3f2abe

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-326-1521-merge-2024-03-04T04-25-08.ipa
Device test: IP 11

- [ ] UI bug Select account 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/e0941604-376c-4762-9437-01510f9213cf)

**Comment by Quangdm-cdm** [comment]
> Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-326-1521-merge-2024-03-04T04-25-08.ipa Device test: IP 11
> 
> * [x]  UI bug Select account
> 
> ![Image](https://private-user-images.githubusercontent.com/117999489/310759727-e0941604-376c-4762-9437-01510f9213cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4OTgzNzAsIm5iZiI6MTcxNjg5ODA3MCwicGF0aCI6Ii8xMTc5OTk0ODkvMzEwNzU5NzI3LWUwOTQxNjA0LTM3NmMtNDc2Mi05NDM3LTAxNTEwZjkyMTNjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQxMjA3NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZWQ2ZjRjZmYxODJiZmI5MmUwNzE3M2NlMDk2NTJlZGExMDA5ZmVlMGViYjFiYjdhZjNjNzBmNzY5ZGI5NjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uNUZF1TzcUa11nL9_P1FyWvhlXyOqpkdVDg3pwNqK6Q)

Can't reproduce this bug in current version

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/AuZUo2
Device test: S20 FE 5G

- [ ] Bug when export all account
  Actual: Do not select all account

  https://github.com/user-attachments/assets/a1b8b63d-2173-401a-8270-1af460cf1121

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/ax4Fve
Device test: IP 13
Checklist: https://www.notion.so/subwallet/Checklist-theo-issue-13c9e3215ec24762973dc680aec67198?pvs=4#ac0982d066414f54b1fc39b063867508

- [ ] Bug on Website access details

Check action: Block this site/Connect all/ Disconnect all
https://github.com/user-attachments/assets/2041536a-8548-4aae-b98b-12056a158fad
