### ISSUE TITLE
Download seed phrase from web.subwallet.app in webview

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1173]
**Describe the bug:**
Do not download seedphrase from web.subwallet.app in webview

**Reproduce:**
- Open web.subwallet.app from in-app Browser
- Go to Create account from seedphrase
- Press Copy & Save to the clipboard

**Actual:** Press download seedPhrase -> open page include seedPhrase but do not dowload.
**Expect:** Press download seedPhrase -> open page include seedPhrase -> open Share dialog box to save -> back to main page

**Comment by ThaoNguyen998** [comment]
Version test: PR 1176 11:21 22/11/2023
Device test: Samsung S20 FE 5G 
Iss
- [ ] Do not download the seed phrase

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/1302b3fc-a6d0-49f8-bea5-05b4c4dc30d7

**Comment by ThaoNguyen998** [comment]
Version test: PR #1176 11:20 23/11/2023
Device test: IP 11, SS S20 FE 5G

Validation passed in IOS (Android does not support Save action)
https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/EUxbQulJY5xOsmswFXY_Hj4B4hA-CcxrJMFO2MM9VLhBoQ?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=4feyZR
