### ISSUE TITLE
Handle case unstake when active stake = 0

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Mobile#1177]
User report that the unstake button is not disabled even after unstaking everything

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/44641118/e601dab0-bbe6-4bd2-b3d6-a9f18679c976)

Expect: 
- If "Withdraw action" available -> Show button Withdraw on details screen (Move unstake action on "... button)
- User click on "Unstake" 
  - "Active stake" > 0 => Show unstake screen
  - "Active stake" = 0 and "Withdraw action is available" => Move unstake action on "... button" and disable button Unstake
  - "Active stake" = 0 and "Withdraw action not available" => Show popup with content: 
    - Header: Unstaking not available
    - Message: You don't have any staked funds left to unstake. Check withdrawal status (how long left until the unstaking period ends) by scrolling down in the Details screen. Keep in mind that you need to withdraw manually.
    - Button: Check withdraw status 
      - Click button -> Back to details screen (automatically open see more and scroll to bottom)

**Comment by Sokol142196** [comment]
Version test: Mobile - v1.1.15 - Build: 261
Device test: IP 8 Plus (15.5)
Validation passed
https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/EVCcBWSb_N1JulKrGhmAK6oBCS4XJprwzhT7lleHTCzfEA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=OFbJCS
