### ISSUE TITLE
Replace rtk query with fetch for Buy Token

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1179]
* Round 1:
  - Use fetch or axios to get config
  - Config's only applied when start app
 
* Round 2:
  - Use cache methods for config
  - Config applying at any time

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.10(239) PR #1180 19:37 23/11/2023
Device test: 
- IP 8 Plus
- IP 11
- IP 11 Promax

Validation passed.
