### ISSUE TITLE
Bug reset data on iOS version 17.1.1 (round 2)

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1182]
* What to do: 
  - Fix bug show randomly welcome screen
* Next round:
  - Update indexed db
  - Clear backup data when remove account or clear app data

**Comment by ThaoNguyen998** [comment]
The issues are compiled in the file 
https://konistudio-my.sharepoint.com/:w:/g/personal/nhungphung_koni_studio/Ebalh2Nvp8tGvgrBqboIPDABddJ2ra0vnGeXno4x9PHoMw?e=fjgv6q

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.12(242)
Device test: IP 11, Samsung S20 FE 5G

Validation passed.
