### ISSUE TITLE
Do not display dApps that have been added to predefined lists on Strapi

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-Mobile#1183]
Actual: Do not display dApps that have been added to predefined lists on Strapi
Expect: Replace rtk query with fetch to get data

**Comment by ThaoNguyen998** [comment]
Version test: PR 1185 19:05 27/11/2023
Device test: Samsung S20 FE 5G

- [ ] Crash app in case open dApp tab the first time https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/Ef9_W7gW1MpEjoB7yOEfJdQBas0YD9pC9tQ8PHA5DzLrOQ?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0RpcmVjdCJ9fQ&e=aWx3Z0

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.12(242)
Device test: Samsung S20 FE 5G

Validation passed.
