### ISSUE TITLE
Re-check show popup Important notice on some device Android

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1191]
**Describe the bug**
Re-check show popup Important notice on some device Android

**To reproduce the bug**
Device test: Redmi note 11, Xiaomi Redmi Note 10

Steps:
1. Update version 242 -> 254
2. Open app and observe the displayed

Actual: Show popup

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/6baa0e97-be0f-43a6-962e-99549fb860c8)

Expect: Do not show popup

Note: Campain marketing has been deleted

**Comment by nguyenduythuc** [comment]
@ThaoNguyen998 i'll close this issue after following up for a month
