### ISSUE TITLE
Add the earning status of pool for mobile app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1203]
**Describe the task**
Add the earning status of pool for mobile app
- Link design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=13835-128516&mode=design&t=UQJw5CtlL5uamINr-4

**Comment by nguyenduythuc** [comment]
This feature require web runner 1.1.24

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.15(266)
Device test: IP 11

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/405b4239-5a93-451a-8e82-c356cafa4802)
