### ISSUE TITLE
Update history feature for mobile app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1207]
**Describe the task**
Update history feature for mobile app

- Link design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=13330-231228&mode=design&t=so4YSVjvdIT35Jzz-4

**Comment by ThaoNguyen998** [comment]
Version test: PR #1240 12:13 13/12/2023
Validation passed in case: 
- Transaction performed on wallet
- Transaction on Subscan
