### ISSUE TITLE
Update some UX on mobile app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1208]
**Describe the task**
Update some UX below:
- [x] Add the warning about locked balance after stake on the Add to bond confirmation
  - Style message: Warning 
  - Message: 
    - Header: Your staked funds will be locked
    - Message: Once staked, your funds will be locked and become non-transferable. To unlock your funds, you need to unstake manually, wait for the unstaking period to end and then withdraw manually.
- [x] Update message on the Unstake screen 
  - Old message: Once unbonded, your funds would be available for withdrawal after 7 days.
  - New message: Once unbonded, your funds will be available for withdrawal after around 7 days. Keep in mind that you need to withdraw manually.
![image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/d3234778-008c-437b-aff1-b375f464744c)

- [x] Show message when user do not select account
  - Message: Select account to view available balance
  - Expect:
    - if user do not select account then show message "Select account to view available balance" (message show under the Account field)
    - if user select account then show Available balance
  - Notes: Apply all views with All accounts mode
    - Unstake
    - Withdraw
    - Claim reward
    - Cancel unstake
- [x] Handle case Unstake if Active stake = 0 (https://github.com/Koniverse/SubWallet-Mobile/issues/1177)
- [x] Automatically select accounts in case only 1 account is eligible for the feature when in All accounts mode

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/d6e44182-0ec3-4b0a-ae12-cc3dc0b01745)

- [x] Sort the Current account on top in the Account selector
- [x] Remove button "Copy to clipboard when exported QR code"

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/a867d2bf-5c5a-465d-9296-9666010138ff)

- [x] Order token list by Network priority is enabled
  - Send fund
  - Buy token
  - Stake

**Comment by Sokol142196** [comment]
Version test: v1.1.15 - Build: 261
Device test: Ip 8 Plus (15.5)

Validation passed cases 1, 2, 3 
- Case 4: Noted in task 1177
![IMG_2135](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/5a1578eb-3a93-4477-b950-c8a6f71f1de6)
![IMG_2136](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/3da262b9-f8ed-4f85-9934-42dd011d29d5)
![IMG_2138](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/ce03738c-ffb1-41fd-8ace-f283441f64b0)
![IMG_2139](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/32a9015c-ca55-4ddc-8e3e-663994629a22)
![IMG_2140](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/79401d5f-b6f0-4d77-99f1-5af921ee055e)
![IMG_F37F8A02AE75-1](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/b2543424-7f52-44fe-add7-425db89b667c)

**Comment by ThaoNguyen998** [comment]
@lw-cdm Please help me handle automatically select accounts in case only 1 account is eligible for the feature when in All accounts mode
- Unstake
- Claim reward
- Cancel unstake

**Comment by ThaoNguyen998** [comment]
Version test: PR #1231 9:49 11/12/2023
Device test: Samsung S20 FE 5G

Validation passed in case:
- Stake more
- Unstake
- Claim reward
- Cancel unstake
