### ISSUE TITLE
Apply static content for T&C

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1211]
**Describe the task**

- [x] Apply static content for T&C
- [x] Fix bug do not show scroll icon in case below
   - Steps: 
     - Install app
     - On the T&C popup, click on button "Scroll"
     - Out focus to close T&C popup
     - Click on any button to re-open the T&C 
   - Actual: Do not show scroll icon
   - Expect: Show scroll icon

**Comment by ThaoNguyen998** [comment]
Version test: PR #1237 17:44 12/12/2023
Device test: IP 11, S20 FE 5G

Validation passed in case
- Apply static content 
- Fig bug do not show scroll icon

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/87e029f7-c259-473c-a196-8f0cef1571ce
