### ISSUE TITLE
Re-check don't display list token when search token

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1213]
**Describe the task**
Re-check bug don't display list token when search token

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/ea584dcf-8402-42b3-be7e-f09d8287226a)

User feedback:

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/128490ee-bdfd-4a73-a0ed-35813e5bbd18)

**Comment by Quangdm-cdm** [comment]
Please recheck this issue. If the error cannot be reproduced, please close this issue as it has been tracked since version 1.1.15.

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.66(401)
Device test: IP 11
I can't reproduce the bug on the newest version
The search screen is blank in case the account has no balance and the show zero balance button is disabled
