### ISSUE TITLE
Add pop-up to request rating on mobile app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1216]
**Describe the task**

- [x] Add pop-up to request rating

Expect: Once the user finishes withdrawing the unstake amount, a pop-up will appear asking the app to rate the user
- Popup content: 
  - Header: Rate our app!
  - Content:  If you find SubWallet helpful, please take a moment to rate it in the App Store. We appreciate your ratings and your feedback, as we strive to make SubWallet better everyday.
  - Button: Rate SubWallet / Send feedback / Not now
    - Rate SubWallet: Open popup Rate app
    - Send feedback: Open the popup to write feedback and send to email SubWallet (user not rate)
    -  Not now: Close alert

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/4b5c7d6d-2a64-42fa-8dfc-07a6a24172d1)

- [x] Update setting screen
  - Add the "Rate our app" option on Setting screen
  - Add the "Request a feature" option on Setting screen
  - Merge "terms of service" + "privacy policy" thành “Term of use”
    - Click on "Term of use" -> Redirect to ""

Link doc: https://www.notion.so/subwallet/T-nh-n-ng-Rate-our-app-tr-n-mobile-app-9a8fe31cf41d43d5a42e546cf69e4b5a?pvs=4
Link design:

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.17(270)
Device test: MI 8 Lite, S20 FE 5G

Validation passed.
