### ISSUE TITLE
Automatically switch all accounts mode when connect or perform transaction via WalletConnect

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1221]
**Describe the bug**
Automatically switch all accounts mode when connect or perform transaction via WalletConnect

**To reproduce the behavior**
- Version test: v1.1.16 (266)
- Device test: IP 8 Plus (15.5)

**Steps:**
1. Connect to react-app.walletconnect.com via WalletConnect successful
2. Switch to specific account
3. Perform any action on React page to sign via WallectConnect
4. Observe the app 

**Actual:** Automatically switch all accounts mode

https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/e21097c6-d668-40ec-98f8-e98de499247d

**Expect:** Keep the current account

**Comment by ThaoNguyen998** [comment]
Version test: PR #1247 12:41 15/12/2023
Device test: IP 11

Validation passed. 
https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/EUCJL7384VxMt8RkqKMVE_oBWFJYpoICTCO9MQG2UIocJA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=ZerbUe
