### ISSUE TITLE
Do not connect with new token standard eip-6963

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1222]
**Describe the bug**
Do not connect with new token standard eip-6963

To reproduce the behavior
1. Open browser in app
2. Access to https://eip6963.org/ 
3. Observe the screen

**Actual:** Do not show SubWallet to connect 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/dcd9207c-2a9b-4a1b-bc76-4fff24876557)

**Expect:** Show SubWallet to connect

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.16(267)
Device test: IP 11

Validation passed. 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/f80ab816-66be-458d-8814-fa057b2cb344)
