### ISSUE TITLE
Update UX in case transfer all

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1224]
**Describe the task**
Update UX in case transfer all

- [x] Case 1: Remain amount < ED -> Show alert with information

- Header: Pay attention! 
- Message: Performing this transaction will freeze your account as it makes total balance lower than minimal required balance ([ED]). After the transfer, you won't be able to perform transactions that need gas fees like unstake or withdraw. Transfer all [Max Amount] or cancel
   - For example, Performing this transaction will freeze your account as it makes total balance lower than minimal required balance (10 VARA). After the transfer, you won't be able to perform transactions that need gas fees like unstake or withdraw. Transfer all 11.45 VARA or cancel
- Button: Cancel, Transfer all
  - Cancel: Close alert
  - Transfer all: Redirect user to the Approve transaction confirmation screen
Screen flow: 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/bd6f19c2-6264-467c-b67b-87ee81eb9cfd)

------

- [x] Case 2: User click Max button mannually**

Expect: When user click Max button then show alert like above

**Comment by ThaoNguyen998** [comment]
Version test: PR #1242 19:24 13/12/2023
Device test: IP 11

- [ ] Navigate incorrect when sign transaction
Steps: 
1. Perform send fund any token
2. On Confirmation screen, click on Approve button
3. Observe the displayed screen
Actual: Back to Amount screen

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/4a12ed53-20b3-4889-a53a-369af0ad594f

Expect: Navigate to Success screen

**Comment by ThaoNguyen998** [comment]
Version test:
Device test: 
@Quangdm-cdm Please re-check this issue

- [ ] The receiving account does not have enough balance to keep the account live
Steps:
1. Perform Transfer transaction 
2. Select account with no balance
3. Input Amount < ED
4. Touch Transfer button & observe the displayed screen

Actual: Do not show message error
Expect: Show message: "You must transfer at least {} to keep the destination account alive"

- [ ] Perform transfer local token but native token does not have enough balance to pay the fee
Actual: Do not show message error
Expect: Show message: Insufficient balance

**Comment by Sokol142196** [comment]
Continue implementing in https://github.com/Koniverse/SubWallet-Mobile/issues/1285
