### ISSUE TITLE
Mobile - Disable button "Continue" if do not load Available balance

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1225]
**Describe the task**
Disable button "Continue" if it does not load the Available balance when withdrawing or unstake or claim reward with All accounts mode

To reproduce the behavior
Steps:
1. Switch to "all accounts" mode
2. Go to staking menu then Open the withdraw/unstake/claim rewards screen
3. In case can not get balance, select account then click on "Continue" button

**Actual:** The application crashes on the input screen and is no longer usable

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/b004f18c-a3cf-4e9c-81a6-250681e08a8f)

**Expect:** If do not get balance then still disable button Continue

**Comment by haiyenvu23** [comment]
Version test : PR #1453 02/03/2024 4:29 PM
Device test : IP 6S
Validation passed in case : 
- Disable button if it does not load the Available balance : 
+ Start earning
![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/6df19cad-d714-41fc-9150-2290c6e581f0)

+ Unstake
![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/a9c3e5cd-680e-467e-a0a0-2b6e99ef4af6)

**Comment by haiyenvu23** [comment]
Version test : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-315-1435-merge-2024-02-15T11-21-46.apk
Device test : Samsung

- [ ] Re-check icon (->) to disable on Withdraw and Claim rewards screen


![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/a80a4b3a-0f6c-41a3-b8a8-ba619bc8b296)


![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/d11f8476-14b9-4cf0-afb4-412c1f9c4e96)

**Comment by haiyenvu23** [comment]
Version test : 
- Android : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-315-1435-merge-2024-02-16T08-04-44.apk
- IOS : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-315-1435-merge-2024-02-16T08-07-24.ipa
Validation passed in case : Disable button if it does not load the Available balance 

- Start earning


![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/adb6b54f-dd55-4b4f-aa8e-ae5a4bd9cc46)

- Unstake


![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/55fb7ff7-55d5-4225-8068-4e2e9f424a19)

- Claim rewards


![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/3e0bc38b-84c7-4596-9e01-deefa44e2ac7)

- Withdraw


![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/12c4178f-59b9-4cb4-80b0-14b204f899d7)
