### ISSUE TITLE
Add the earning status on pool details screen and update filter criteria

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1226]
**Describe the task**

- [x] Add the earning status on pool details screen (Earning, Not earning)

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/76b81f7b-fd6d-4f93-9264-7ab3d0005603)

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/262171b7-1c7d-4b32-b5a3-948b2b937011)

- [x] Update filter criteria
  - On list pool: Change "Active" to "Open"

- [x] On list validator/collator/dApp: Add the sorting criteria is "Nomination"
  - When user sorting with "Nomination" then order the nominated validator/collator/dApp on top
![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/78ea179e-f39a-4a49-8cf1-7f88dbd056c1)

**Comment by ThaoNguyen998** [comment]
Version test: 
Device test: MI 8 Lite

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/52bfcf57-2629-4652-bc7a-0910a550d6da)

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/356c757f-05ea-45bc-ad0c-638083dc835d)

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/273ce7e8-4096-40a7-acb5-c2b9541e432e)
