### ISSUE TITLE
UI bug on some devices

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1228]
**Describe the bug**

- [x] UI bug Login screen on Android

https://github.com/Koniverse/SubWallet-Extension/assets/117999489/45ada0fd-f419-4f37-b6e8-7de220b4cdb8

- [x] UI bug on IP SE

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/e30100b8-25ba-4ff1-ac05-d4ac8d0887ea)

- [x] UI bug send NFT screen

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/ca5f39a0-4cb4-493e-894c-cfdf6db4893c)

- [x] Still enable button Connect when do not select account
  Steps: 
  1. Go to browser in app
  2. Visit to connect.subwallet.app page
  3. Connect to EVM account successfully then observe the popup connect Substrate account

  Actual: Still enable button Connect although do not select account
![image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/0c9f3cba-3db0-484b-9c00-99b02822c282)

  Expect: Only enable Connect button when selected account

- [x] Still show virtual keyboard when open QR code from Account Selector screen in case search account
  - Expect: Automatically close virtual keyboard
![image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/5a4a1846-fcf5-48b6-ac9a-4cadecf57e90)

- [x] UI bug on  IP SE 2022

https://github.com/Koniverse/SubWallet-Extension/assets/117999489/282d4013-b61b-4a16-9405-aee3be272026

- [x] Re-check bug UI on Redmi note 7, Galaxy Note 8

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/a774f597-f1db-40fe-9426-8ad6b3f6bb15)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/edfdb1ec-56e4-49d7-85c3-272b8f0e67a5)

- [x] Toast show incorrect location

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/60928346-5f43-4545-bd3e-447a552020e1)

- [x] Substrate -> Polkadot

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/92b6ac31-8a4a-401c-8b3d-a349d7a0c370)

**Comment by Quangdm-cdm** [comment]
- Toast show incorrect location: Please re-check some screen: Validator Selector (Stake), Receive Modal, StakingDetailModal
- Re-check bug UI on Redmi note 7, Galaxy Note 8: just got this error in emulator device
- Still show virtual keyboard when open QR code from Account Selector screen in case search account: Please re-check some screen have Token Selector or Account Selector
@ThaoNguyen998

**Comment by ThaoNguyen998** [comment]
Version test: PR #1246 18:38 19/12/2023
Device test: Samsung S20 FE 5G

Validation passed in the above cases
