### ISSUE TITLE
Show incorrect transaction status beetwen detail screen and list screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1232]
Describe the bug
Sometimes, Show incorrect transaction status beetwen detail screen and list screen
![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/1472e210-e6aa-49d1-8816-a2ccd3aff437)

**Comment by ThaoNguyen998** [comment]
Version test: PR https://github.com/Koniverse/SubWallet-Mobile/pull/1240 12:13 13/12/2023
Device test: IP 11, SS S20 FE 5G
Validation passed in case:

Transaction performed on wallet
Transaction on Subscan
