### ISSUE TITLE
Mobile - Update the Token details screen for mobile app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1235]
**Describe the task**
Update the Token details screen
**Expect:** Only show accounts have balances on the Account details tab
- If No accounts have balances then show message
  - Header: No account with {token} balance found
  - Content: Switch to another token to see account balance
  - CTA: Back to home

Tiếng Việt:
Header: Không tìm thấy tài khoản có số dư {token}
Content: Vui lòng chọn token khác để xem số dư tài khoản
Button: Trở về trang chính

Tiếng Trung:
Header: 未找到有{token}余额的账户
Content: 请选择其他代币查看账户余额
Button: 返回主页

**Comment by haiyenvu23** [comment]
Version test : PR #1457 02/07/2024  6:57 PM
Device test : IP 6S

- [ ] Screen displays an error when clicking on the EVM type token

https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/3a720d59-db5f-4edd-a7ae-80f5bb504b29

**Comment by haiyenvu23** [comment]
Version test : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-315-1457-merge-2024-02-15T05-43-53.apk
Device test : Samsung

- [ ] Improve UI for Token details screen

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/20f553c1-7cdd-4b96-8f37-c19b683a25f0)

**Comment by haiyenvu23** [comment]
Version test : 
- Android : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-315-1457-merge-2024-02-16T09-39-21.apk
- IOS : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-315-1457-merge-2024-02-16T09-41-39.ipa
Validation passed in case : 

- Only show accounts have balances on the Account details tab
![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/85c3d1cc-cb57-4a9e-95a5-fb09c0878178)

- No accounts have balances then show message
![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/e22ebfaf-dbce-4c32-9975-3c1cff85c6f2)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-315-1457-merge-2024-02-16T09-41-39.ipa
Device test: IP 11

@Quangdm-cdm Please handle touch on Back to home button -> navigate to Token detail

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-317-1457-merge-2024-02-20T08-07-53.ipa
Device test: IP 11

Validation passed in these case.
