### ISSUE TITLE
Add default subject in email feedback in app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1245]
**Describe the task**
Add default subject in email feedback in app

**Expect:** Default Subject = [SubWallet In-app Feedback]

**Comment by ThaoNguyen998** [comment]
Version test: PR #1248 12:58 15/12/2023
Device test: IP 11

- [ ] Do not navigate when click Request a feature on IOS 

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/4ec0d839-7021-4491-9520-4c33504392b0

**Comment by ThaoNguyen998** [comment]
Version test: PR #1248 15:15 15/12/2023
Device test: IP 11, MI 8 Lite

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/1f0ac319-ac7c-4578-89cd-7d3b4860cdbf)
