### ISSUE TITLE
Follow case transfer max in case send DOT on BD account

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1249]
**Describe the task**
Follow case transfer max in case send DOT on BD account

**To reproduce the task**
Steps: 
1. Go to Transfer screen
2. Select token DOT and Max transferable
3. Peform sign transaction successfully and obserse the displayed screen
4. Check amount on receive address

Actual: The amount on the receiving address is different from the amount recorded in history
https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/Eb8eTC4Fd9hEmKQzGHJ2ag0BaUymf-mTflDHBAcXx6nZhA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=HWFE9K

**Comment by Sokol142196** [comment]
@ThaoNguyen998 please verify this issue

**Comment by ThaoNguyen998** [comment]
I can't reproduce this issue on the newest version -> Close issue
