### ISSUE TITLE
Bugs related to new history feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1250]
Describe the bug

- [x] Do not show Transfer NFT transaction
  Steps:
  1. Perform transfer NFT
  2. On the transfer NFT result screen
  3. Click on "View transaction" to view history details screen
  4. Observe the screen displayed

  Actual: Do not show history details screen
    - Do not navigate account & network 
    - Record file: https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/EUXstt51hPRAm--kFwe6ZM0Buc7MRN7vme3BmDwBrqMgug?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=av0CDK
  
  Expect: Show history detail screen 

- UI bug when scrolling the history screen on iOS device

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/c9ab1245-c96a-4185-9223-2a30e9c744f3)

-> Move to https://github.com/Koniverse/SubWallet-Mobile/issues/1318

**Comment by ThaoNguyen998** [comment]
Version test: PR #1293 17:48 27/12/2023
Device test: IP 11

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/140cc23e-d9d2-4fdd-98c3-56b7386ba6d3)
