### ISSUE TITLE
[Mobile] Migrate `Staking` to `Earning`

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Mobile#1251]
- [x] Add screen Earning Token List
- [x] Adjust screen Earning Pools List 
- [x] Add screen Basic Earning Info
- [x] Adjust screen Earning transaction
- [x] Adjust start earning flow
- [x] Adjust screen Earning Position Detail
- [x] Add extra info to transaction screens
- [x] Minor fixes

**Comment by nampc1** [comment]
- [ ] Start earning confirmation
- [ ] Update data for tx history
- [ ] Check tx history subscription
- [ ] Check cron job for unclaimed rewards (it seems slowed)
- [ ] Fix bug not showing parallel liquid staking

**Comment by nampc1** [comment]
- [ ] Update validation logic in basic earning info screen
- [ ] Update validation logic in start earning screen
- [ ] Migrate warnings and alerts from before

**Comment by Sokol142196** [comment]
Earning screen:

- [ ] Remove "Yealy rewards, Estimated earnings" 
- [ ] Show incorrect "Estimated fee" value in case stake more
- [ ] Show duplicate err message when stake in case Insufficient balance
- [ ] Handle case switch account
  To reproduce the behavior
  Steps:
  1. Go to the staking screen of the any account
  2. Switch to another account
  3. Observe the screen displayed

  Actual: Show black screen
  Expect: Switch account and back to list pools or list earned

**Comment by nampc1** [comment]
@S2kael 
- [ ] Change tag Native staking -> Direct nomination
- [ ] Change tag Native staking for Astar -> dApp staking

**Comment by nampc1** [comment]
- [ ] Fetching earning rewards from SubScan

**Comment by Sokol142196** [comment]
- [ ] Do not update "Minimum active stake" when select validator/collator/dApp
  
![image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/91691d4f-acf4-404a-919c-ec1951cbb495)

**Comment by nampc1** [comment]
- [ ] Add reward payout info
- [ ] Add reward assets for Stellaswap

**Comment by nampc1** [comment]
- [ ] Review total balance 
- [ ] Withdrawal history - wrong unit
- [ ] Wrong redirecting after withdrawing all

**Comment by nampc1** [comment]
- [ ] Add going back while in the middle of the earning process
- [ ] Fix bug processing steps when going back while earning

**Comment by nampc1** [comment]
- [ ] Bug redirecting upon switching to all account mode
