### ISSUE TITLE
Add hyperlink when connect Polkadot Vault

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1261]
**Describe the task**
Add hyperlink when connect Polkadot Vault

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/08e735ec-2c26-427f-b1ec-79b13d3a2e58)

**Comment by Quangdm-cdm** [comment]
@ThaoNguyen998 I have completed this section for the ConnectKeystone feature too. Please check it when you test this issue

**Comment by ThaoNguyen998** [comment]
Version test: PR #1317 12:52 03/01/2023
Device test: IP 11

Validation passed. 
https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/EUsCUVb_qghEtrTOC0pAIrgBKZ7dNwjgllzFG0LS0LXcag?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=dZhaep
