### ISSUE TITLE
Bugs related to Access Camera permission when using WalletConnect feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1267]
**Describe the bug**
Bugs related to Access Camera permission when using WalletConnect feature
- [x] Do not show popup Access camera permission when using the WallectConnect feature
Case 1: Access permission
Steps:
1. Open the SubWallet app
2. Go to Settings then click on WalletConnect
3. On the popup Access camera setting then choose "Don't allow/Dismiss"
4. Observe the screen displayed 

Actual:
- iOS device: Show black screen -> Can't use app
- Android: Show "Camera not authorized"

Expect: Back to Settings screen

Case 2: After dismiss permission
Actual: Show black screen with message "Camera not authorized", do not show popup "Notifications"

Expected: Show popup "Notifications", redirect user go to Setting device to edit permission (refer camera access with other feature)

https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/6bb2bf05-f58c-4196-b668-adf6301c8a61

-------
- [x] Show a grey screen when disconnecting the WalletConnect connection while standing on the "Manage connection" screen
Pre-condition: Performing connected to WalletConnect
Steps:
1. Go to the manage WalletConnect connection screen (dApp on desktop)
2. Go to dApp page, perform disconnect 
3. Back to mobile app then observe the screen display

Actual: Show black screen
Expect: Back to the Settings screen

https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/c33e3093-a9ac-489a-ba92-e721776c9edf

Notes for Tester @ThaoNguyen998 : after fixed these bug, re-check all feature using Camera

**Comment by ThaoNguyen998** [comment]
Version test: PR #1290 12:06 26/12/2023
Device test: MI 8 Lite

- [ ] Show popup access camera when cancel
Steps:
1. Install SubWallet app
2. Go to WalletConnect 
3. On the popup access camera, select Cancel 
4. Observe the displayed screen

Actual: Show popup access camera
Expect: Back to Setting screen

**Comment by ThaoNguyen998** [comment]
Version test: PR #1290 19:28 27/12/2023
Device test: IP 11, SS S20 FE 5G, Mi 8 Lite 

Validation passed.
