### ISSUE TITLE
Fallback t&c content incase static content offline

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1276]

**Comment by ThaoNguyen998** [comment]
Version test: PR #1277 15:52 21/12/2023
Device test: IP 11, MI 8 Lite

Validation passed in case
- Upgrade
- Install 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/cea3980d-468c-46d8-a94b-e48f0be2220c)
