### ISSUE TITLE
Update new layout for mission pool

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1280]
- Update new layout mission pool list item 
- Add status to disable join now button

**Comment by nguyenduythuc** [comment]
@Quangdm-cdm disable mission pool on browser to finish this issue

**Comment by ThaoNguyen998** [comment]
@Quangdm-cdm Please update list dApp recommended on Browser

**Comment by ThaoNguyen998** [comment]
Version test: PR #1297 16:06 03/01/2023
Device test: IP 11, S20 FE 5G

Validation passed. 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/a3bd3da9-4ac8-45d7-b387-e0f06f5cd65c)

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/450bb27d-d2dc-4cd0-819a-54d0994922ca)
