### ISSUE TITLE
Bug related to EVM history

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1283]
**Describe the bug**
Bugs related to the history of the EVM account

**To reproduce the behavior**
Steps:

1. Open SubWallet
2. Performing transfer token transactions successfully (Moonbase, Moonbeam)
3. Observe the history of the account
Actual:
- [x] Show incorrect transaction fee of the history from Subscan
- [x] Show duplicate transactions in case have both local history and online history

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/5463aa93-fafc-4a3d-ac4a-70051a138ef9)

**Comment by nguyenduythuc** [comment]
This will be fixed in #1263

**Comment by ThaoNguyen998** [comment]
Version test: PR https://github.com/Koniverse/SubWallet-Mobile/pull/1293 17:48 27/12/2023
Device test: IP 11

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/abfa8633-46d3-4562-90ec-5b4fc40d69de)

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/87c82e53-f3a5-43ba-b2ab-79bb62109685)
