### ISSUE TITLE
Re-check the duration of the toast

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1288]
**Describe the task**
Re-check the duration of the toast

**Actual:** 
- Sometimes, do not apply duration incorrectly
- Need to increase the duration to 4s

**Comment by ThaoNguyen998** [comment]
Waiting issue #1281

**Comment by ThaoNguyen998** [comment]
Version test: PR https://github.com/Koniverse/SubWallet-Mobile/pull/1298 02/01/2023
Device test: IP 11, S20 FE 5G

Validation passed.
