### ISSUE TITLE
Add Seed phrase T&C for case create one

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1289]
**Describe the task**
Add Seed phrase T&C for case create one

**To reproduce the behavior**
1. Open the SubWallet app
2. Import/attach account successfully without EVM account
3. Go to Browser tab
4. Visit to any EVM dApp
5. On the popup connect, click on "Create one" then observe the screen displayed

**Actual:** Do not show Seed phrase T&C
**Expect:** Show the T&C seed phrase

**Comment by nguyenduythuc** [comment]
Can't reproduce, need to recheck again! @Sokol142196
