### ISSUE TITLE
Add flag "not show again" for MKT Campaign when resetting event iOS 17 is triggered

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1291]
- Add flag when user click action on MKT Campaign popup. This flag is campaign's slug, sent from background.
- When the app's opened, checking campaign data sent from background has this condition: background.slug = flag.slug, if the condition match, we will not show campaign again

**Comment by ThaoNguyen998** [comment]
Version test: PR #1292 13:17 26/12/2023
Device test: IP 11

Validation passed. 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/df46dd82-a5c2-420d-bf40-614a5d5a094a)
