### ISSUE TITLE
Re-check show popup Back-up your seed-pharse on Android

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1294]
**Describe the bug**
Re-check show popup Backup your seed phrase on Android

**To reproduce the bug**
Steps: 
1. Perform upgrade version 1.1.22(283)b-v8  to 1.1.22(284)b-v8 successfully
2. Re-open app and observe the displayed screen 

Actual: Show popup backup

Expect: Do not show popup

**Comment by nguyenduythuc** [comment]
I've prevented showing this popup on Android. This bug doesn't often occur, so I'll recheck the code, and we'll keep following this issue for a while.

**Comment by nguyenduythuc** [comment]
@ThaoNguyen998 This could be occurred after change web runner online to offline or downgrade web runner version. If you haven't seen any case of losing data after a month, i prefer close this issue. Thanks!

**Comment by Quangdm-cdm** [comment]
@ThaoNguyen998 close this issue because we use Marketing Campaign to show Backup seed phrase now!!!
