### ISSUE TITLE
Add swipe down to reload balance on Crowdloan screen

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1296]
**Describe the task**
Add swipe down to reload balance on Crowdloan screen

**Comment by nguyenduythuc** [comment]
Fixed in #1152

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-297-1370-merge-2024-01-18T09-43-03.ipa
Device test: IP 11

Validation passed. 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/a4bfc1ac-f1c2-4fcd-a41f-a96340c2eaf7)
