### ISSUE TITLE
Multilingual processing for Terms of use on mobile app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1299]
**Describe the task**
- Multilingual processing for Terms of use on mobile app
- Update fallback content

**Comment by nguyenduythuc** [comment]
@Quangdm-cdm pls, use this url (https://github.com/Koniverse/SubWallet-Static-Content/tree/main/data/term-and-condition) to create markdown file. On mobile, you need to detect current language for markdown file

**Comment by ThaoNguyen998** [comment]
Version test: PR #1300 12:43 29/12/2023
Device test: IP 11

- [ ] Do not show T&C when changing language
Step: 
1. Install app SubWallet successfully
2. Open app and on Welcome screen, change Language English -> Vietnamese
3. Observe the displayed screen 

Actual: Do not show T&C

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/154cf8e5-302e-474a-89a9-e04285ef25b4)

Expect: Display T&C in the newly changed language

**Comment by nguyenduythuc** [comment]
Wait for language contents

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-297-1300-merge-2024-01-18T02-15-40.ipa
Device test: IP 11 

- [ ] Re-check bug do not show T&C when network is not stable network is not stable

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/5d36ba4e-35df-4e67-94ea-1bedb7b98d95)

- [ ] Handle the case of multingual for T&C when fallback 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/2dd2f344-a774-46f0-a7a8-3bf039eeefdb)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-301-1300-merge-2024-01-23T08-01-27.ipa
Device test: IP 11

Validation passed. 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/31479faa-cad7-4125-b9ea-232122c35b36)
