### ISSUE TITLE
Can not connect WalletConnect

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1321]
**Describe the task**
Can not connect WalletConnect

**To reproduce the task**
Actual: Can not connection mobile via Wallet connect from some app like https://zealy.io/

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/702667e5-a99d-48bc-abea-695496182846)

**Comment by saltict** [comment]
It may be fixed with web-runner 1.1.31 please check this @ThaoNguyen998

**Comment by Sokol142196** [comment]
This feature is resolved when updating web-runner v1.1.31 => Close issue
