### ISSUE TITLE
Update web runner v1.1.30

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1322]
- Return error code when staking with interrupted connection
- Show popup turn on chain when lost network connection

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-286-1327-merge-2024-01-06T04-59-48.ipa
Device test: IP 11

Validation passed

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/d2bb1940-8b47-43b3-b9c3-ac05bc73d909)
