### ISSUE TITLE
Handle bug undefined error when perform transaction

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1328]
**Descibe the bug**
Handle bug undefined error when perform transaction

**To reproduce the bug**
Actual: Show message undefined error when perform transaction

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/3d5fb4aa-fd09-4258-bb87-b88bbe75087b)

Actual: Show alert update network 
English: 
Title: Update network
Content: Your selected network has lost connection. Update it by re-enabling it or changing network provider.
Action: Update 

Tiếng Việt:
Title: Cập nhật mạng
Content: Mạng bạn chọn đã mất kết nối. Vui lòng cập nhật bằng cách bật lại mạng hoặc đổi provider.
Action: Cập nhật

Tiếng Trung:
Title: 更新网络
Content：您选择的网络已失去链接。通过重新启用它或更改网络提供商来更新它。
Action：重新网络

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-286-1327-merge-2024-01-05T05-18-27.ipa
Version web-runner: https://65954d411f616696751c1409--sw-web-runner.netlify.app/

- [ ] Re-check the status network after updating the network
Steps: 
1. Perform staking with any token
2. On the popup update network, select action update
3. Turn the network back on and return to the staking screen
4. Observe the displayed screen
Actual: Unable update network

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/1c888ae0-eec2-4d3b-82fa-67b2563512a3

**Comment by nguyenduythuc** [comment]
This was fixed in #1322

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-286-1327-merge-2024-01-06T03-50-13.ipa
Device test: IP 11 

- [ ] Show message Enable network in case of sign transaction when transfer all
Steps: 
1. Perform transaction transfer all
2. Obserse the displayed screen 

Actual: Show message require enable network

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/a32923e4-b8fd-4135-8016-51cb5b6ffc0e

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-286-1327-merge-2024-01-06T04-59-48.ipa
Device test: IP 11

Validation passed.

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/3252852d-b045-49cf-bdad-9efb3b07af83
