### ISSUE TITLE
Update hyperlink instruction for some screens

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1329]
**Describe the task**
Update hyperlink instructions for some screens:

- [x] Add hyperlink for "this instruction" on the Import account by QR code screen
  - Link: https://docs.subwallet.app/main/mobile-app-user-guide/account-management/import-restore-an-account#import-by-qr-code 

- [x] Update hyperlink for "this instruction" on the Connect a Keystone device
  - Link: https://docs.subwallet.app/main/mobile-app-user-guide/account-management/connect-keystone-device 
 
- [x] Update hyperlink for "this instruction" on the Connect a Polkadot Vault account
  - Link: https://docs.subwallet.app/main/mobile-app-user-guide/account-management/attach-a-polkadot-vault-previously-parity-signer-account

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.24(288)
Device test: S20 FE 5G

Validation passed in case: 
- Import nug QR code
- Connect a Polkadot vault
- Connect a Keystone device
