### ISSUE TITLE
Implement auto recover on android and ios lower than 17

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Mobile#1330]
- After backup & restore is working stably on iOS 17, we continuing apply this feature on Android and iOS lower than 17

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-288-1335-merge-2024-01-09T04-33-21.apk
Device test: S20 FE 5G

- [ ] Unable to turn on/off network

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/2ce0652f-41c6-4654-905d-e5dbe3a8ba2d

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-288-1335-merge-2024-01-09T04-33-21.apk
Device test: S20 FE 5G

Validation passed in case: 
- Install 
- Upgrade version
