### ISSUE TITLE
[Earning] Fix some UI bugs

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Mobile#1334]
- Update loading UI when first tap on Earning tab (fix later)
- [x] Update logo for earning pools
- [x] Update APY tag in basic earning info screen
![image](https://github.com/Koniverse/SubWallet-Mobile/assets/44641118/106f34ce-2cb0-4b0c-bb1e-90ba74d2db49)
- [x] Update screen title

**Comment by nampc1** [comment]
- [ ] Update FAQ URL
- [ ] Sort native staking pool to bottom

**Comment by Quangdm-cdm** [comment]
[] Add Claim Reward info box

**Comment by nampc1** [comment]
- [ ] Add reward history for direct nomination

**Comment by nampc1** [comment]
- [ ] Update showing unstaking info when there's no waiting time

**Comment by nampc1** [comment]
- [ ] Add reward history for direct nomination
- [ ] Update wording for Interlay lending (earning detail)
- [ ]  Add to bond screen title -> Start earning

**Comment by nampc1** [comment]
- [ ] Handle showing error Insufficient balance

**Comment by nampc1** [comment]
- [ ] Improve performance handling network toggling (showing double loading)
