### ISSUE TITLE
Add desktop mode for dapp browser

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1338]
- Inject javascript to add a meta tag, to define screen width

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-293-1358-merge-2024-01-17T02-31-43.ipa
Device test: IP 11

Validation passed in case: 
- Open in desktop view
- Zoom in/ Zoom out
- Perform transaction

Discuss: Save config Open desktop view when re-open dApp

**Comment by Sokol142196** [comment]
Version test: 1.1.27(298)

- [ ] Don't apply desktop mode on some dApp
  - Check with Manta dApp (airdrop.manta.network)
  
https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/EVd11UqoaC9JnucHsiFQWIEBRFoYXgMs2cm6xpwXDK8QBw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=JhUcgI

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.27(299)
Devices test: IP 11

Validation passed. 
- Manta dApp
- Zenlink dApp
- Acala dApp 
- Karura dApp
