### ISSUE TITLE
Do not show message in case send VARCH token

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1340]
**Describe the bug**
Do not show message in case send VARCH token

**To reproduce the bug**
Version test: 1.1.25(289)
Device test: IP 11

Steps:
1. Perform send fund VARCH token
2. Input Amount < Transferable
3. Observe the displayed screen

Actual: Do not show message  error
Exxpect: Show message: "This feature is not available with this token"

**Comment by nguyenduythuc** [comment]
Also add support i18n for T&C popup's label

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-289-1343-merge-2024-01-13T04-47-51.ipa
Device test: IP 11

Validation passed.

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/fbe3b0ce-c01e-477e-9399-7218cc75eb3a
