### ISSUE TITLE
A bug of history filter

### ISSUE THREAD

**Issue by mezrin** [Koniverse/SubWallet-Mobile#1345]
Case 1 - no filters are used.
All works correctly

<img src="https://github.com/Koniverse/SubWallet-Mobile/assets/2777812/cd58f821-63db-4e95-a718-f73dd2e6d810" width="135" height="300" />

<img src="https://github.com/Koniverse/SubWallet-Mobile/assets/2777812/d78e604b-8e7d-433a-8812-1de0e39475cc" width="135" height="300" />

Case 2 - "Send tokens" selected.
All works correctly

<img src="https://github.com/Koniverse/SubWallet-Mobile/assets/2777812/4ae5b3c4-fa61-436f-80a7-248a149ae87e" width="135" height="300" />

<img src="https://github.com/Koniverse/SubWallet-Mobile/assets/2777812/4f8e08e8-df02-4e34-b847-67f3a75f1cc8" width="135" height="300" />

Case 3 - "Successful" selected.
All works correctly

<img src="https://github.com/Koniverse/SubWallet-Mobile/assets/2777812/f4b41dde-eac1-42fe-aeb8-c721d0a4ae7a" width="135" height="300" />

<img src="https://github.com/Koniverse/SubWallet-Mobile/assets/2777812/33ea4ba5-b9c7-440b-b789-6faac9e40450" width="135" height="300" />

Case 4 - "Send tokens" and "Successful" selected.
As you can see on the screenshots below, some events are displayed twice.
To be precise: if an event matches both conditions "Send tokens" & "Successful" - it's displayed two times. 

<img src="https://github.com/Koniverse/SubWallet-Mobile/assets/2777812/6aab8961-89b4-44a7-9979-7994e3904d8a" width="135" height="300" />

<img src="https://github.com/Koniverse/SubWallet-Mobile/assets/2777812/c98b97d0-f1b8-474a-b7cb-799280268435" width="135" height="300" />

-----

P.S. It would be great to visually separate the filter of event type (send receive NFT stake claim) and the status of transaction (successful failed).

**Comment by saltict** [comment]
Hi @mezrin, we really appreciate your feedback. 

In the near future, we also have a roadmap to further improve the History feature. I will add your suggestions to these tasks.

Have a nice day!

**Comment by mezrin** [comment]
@saltict Hi. Good to know that! :)

We are currently working on a Substrate-based chain for games. SubWallet looks really good and provides great support for tokens and especially NFTs. So it’s becoming the wallet of choice for us - we will recommend SubWallet to the users of our chain when we release it.

Meybe we even will come up with the PRs&improvements to the wallet in the coming weeks :) Lets keep in touch

**Comment by saltict** [comment]
@mezrin, I also look forward to receiving contributions from the community and great developers like you.
