### ISSUE TITLE
Add banner in token detail

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1346]
- Show banner (Mkt campaign) right after last item in token details screen

**Comment by ThaoNguyen998** [comment]
Version test: 
Device test: IP 11, S20 FE 5G

Validation passed in case: 
- Token detail

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/1a3fdfe6-e008-4247-a324-14efcd2c2d90)
- Tokens

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/a7ac7302-381d-46a2-952f-2144f77c6ec8)
- Crowdloans

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/ad8f2fbf-6a80-4c70-a4d0-427c3faabd60)
