### ISSUE TITLE
Add support i18n for T&C popup's label

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1347]

**Comment by djhatrang** [comment]
Tiếng Việt:
- Tôi đã hiểu và đồng ý với bản Điều khoản sử dụng, và chấp thuận rằng tất cả các điều khoản kể trên áp dụng cho việc tôi sử dụng SubWallet và toàn bộ tính năng của ứng dụng này
- Cuộn xuống để đọc toàn bộ nội dung
- Tôi hiểu rằng SubWallet không thể khôi phục mật khẩu này cho tôi. 
- Tìm hiểu thêm
- Xác nhận đã đọc
- Vui lòng đánh dấu vào ô "Tôi đã hiểu và đồng ý với bản Điều khoản sử dụng, và chấp thuận rằng tất cả các điều khoản kể trên áp dụng cho việc tôi sử dụng SubWallet và toàn bộ tính năng của ứng dụng này" để đi tiếp
- Tôi đã hiểu
- Vui lòng đánh dấu vào ô "Tôi hiểu rằng SubWallet không thể khôi phục mật khẩu này cho tôi" để đi tiếp
- Tôi đã hiểu

**Comment by djhatrang** [comment]
vi: Tôi đã hiểu và đồng ý với bản Điều khoản sử dụng, và chấp thuận rằng tất cả các điều khoản kể trên áp dụng cho việc tôi sử dụng SubWallet và toàn bộ tính năng của ứng dụng này
zh: 我理解并同意本协议的条款，该条款适用于我对 SubWallet 及其所有功能的使用
jp: 私は、SubWallet とそのすべての機能の使用を規定する本契約の条件を理解し、これに同意します

**Comment by djhatrang** [comment]
**vi**: Cuộn xuống để đọc toàn bộ nội dung
**zh**: 滚动阅读所有部分
**jp**: スクロールしてすべてのセクションを読みます

**Comment by djhatrang** [comment]
**vi**: Tôi hiểu rằng SubWallet không thể khôi phục mật khẩu này cho tôi.
**zh**: 我了解 SubWallet 无法为我恢复此密码。
**jp**: SubWallet ではこのパスワードを回復できないことを理解しています。

**Comment by djhatrang** [comment]
**vi**: Tìm hiểu thêm
**zh**: 了解更多
**jp**: もっと詳しく知る

**Comment by djhatrang** [comment]
**vi**: Xác nhận đã đọc
**zh**: 确认阅读
**jp**: 読み取りの確認

**Comment by djhatrang** [comment]
**vi**: Vui lòng đánh dấu vào ô "Tôi đã hiểu và đồng ý với bản Điều khoản sử dụng, và chấp thuận rằng tất cả các điều khoản kể trên áp dụng cho việc tôi sử dụng SubWallet và toàn bộ tính năng của ứng dụng này" để đi tiếp
**zh**: 请选中“我理解并同意本协议的条款，该条款适用于我对 SubWallet 及其所有功能的使用”框以继续
**jp**: 「私は、SubWallet とそのすべての機能の使用を規定する本契約の条件を理解し、これに同意します」ボックスにチェックを入れて続行してください

**Comment by djhatrang** [comment]
**vi**: Tôi đã hiểu
**zh**: 我明白
**jp**: なるほど

**Comment by djhatrang** [comment]
**vi**: Vui lòng đánh dấu vào ô "Tôi hiểu rằng SubWallet không thể khôi phục mật khẩu này cho tôi" để đi tiếp
**zh**: 请选中“我了解 SubWallet 无法为我恢复此密码”框以继续
**jp**: 「SubWallet ではこのパスワードを回復できないことを理解しています」ボックスにチェックを入れて続行してください

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-289-1343-merge-2024-01-13T08-08-32.ipa
Device test: IP 11

Validation passed.
- English
- Vietnamese
- Chinese
- Japanese
![image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/29503212-bee9-4133-b7a1-e454709b6fe3)
