### ISSUE TITLE
[Earning] Improve showing unclaimed rewards (nomination pools) in all account mode

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Mobile#1352]
We expect to show the sum of unclaimed rewards from all accounts. We allow users to click on "claim rewards" button then choose an account to claim reward from

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-292-1357-merge-2024-01-15T11-31-37.ipa
Device test: IP 11

Validation passed.

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/999116a7-bee4-42cb-9f4c-74ba495f9234

**Comment by Quangdm-cdm** [comment]
- [] Alert Reward < Fee: smaller than to -> small than / equal to
- [] Hide button when Reward is zero -> when Reward is zero, onPress Claim Reward button show Alert
