### ISSUE TITLE
[Earning] Adjust redirecting when in all account mode

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Mobile#1353]
When in all account mode, going back in the Action Details (Stake, Unstake,...) screen will redirect to the Position Details screen. We expect it to be back to the Earning tab

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-292-1357-merge-2024-01-15T11-31-37.ipa
Device test: IP 11

Validation passed in case: 
- Staking
- Stake more
- Unstake
- Cancel unstake
- Withdraw
- Claim reward
