### ISSUE TITLE
[Earning] Fix bug UI showing selected validators

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Mobile#1354]
When in all account mode, nomination info screen will encounter a bug if the selected validators list is too long

**Comment by nampc1** [comment]
Check with this address: 5DRewsYzhJqZXU3SRaWy1FSt5iDr875ao91aw5fjrJmDG4Ap

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-292-1357-merge-2024-01-15T11-31-37.ipa
Device test: IP 11

Validation passed. 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/ad073d90-de1a-4844-aaba-c70e3c136d24)
