### ISSUE TITLE
[Earning] Update logic and UI follow by feedback

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Mobile#1356]
- [x] Unstake: amount > staked with `Interlay` network
- [x] Update insufficient balance for liquid and lending pool
- [x] Missing reward history with dApps pool

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-292-1359-merge-2024-01-15T12-42-22.ipa
Device test:  IP 11

- [ ] Re-check cron job reward history
- [ ] Update message in case "Amount must be equal or less than 0" -> Alert

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/43faa968-7ac4-4c7f-a440-cfbd24cdb852)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-293-1359-merge-2024-01-17T05-31-23.ipa
Device test: IP 11

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/91d6a951-ead7-49db-be58-c171130ecd9d)
