### ISSUE TITLE
[Earning] Improve StaticContent for Earning

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-Mobile#1365]
- [x] Improve Static content for Earning

**Comment by Quangdm-cdm** [comment]
@ThaoNguyen998 wait issue #1421

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-318-1394-merge-2024-02-22T02-19-57.ipa
Device test: IP 11

Validation passed.
- Install app(Enable dev mode)
- Update app
- Update content Intruction
