### ISSUE TITLE
Bug cannot connect WalletConnect from external Browser

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-Mobile#1373]
Cannot connect WalletConnect from external browser (Chrome, Brave,...) from react-app.walletconnect.com

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-299-1385-merge-2024-01-22T04-50-19.apk
Device test: IP 11, S20 FE 5G

- [ ] Do not show confirmation screen when connect WalletConnect from external browser
https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/ETMYgqv68S1CqAfXM2o5000B67CP60ZsM8Q1qDOZAi7K_Q?e=3AZixf

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-301-1392-merge-2024-01-23T08-49-58.apk
Device test: MI 8 Lite, IP 11

Validation passed in case: 
- App to app
- Browser in app
- Web to app

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/aa1a01d6-b898-477e-8ad6-282af44aa61e
