### ISSUE TITLE
Fix bug Android can't show Buy and Browser tab

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1374]

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-299-1375-merge-2024-01-19T05-06-34.apk
Device test: S20 FE 5G

Validation passed. 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/36ef3de7-f24f-41c9-871d-e272bd2fad39)
