### ISSUE TITLE
Add CTA "Earn now" on the "Your earning positions" screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1379]
**Describe the task**
Add CTA "Earn now" on the "Your earning positions" screen
- Click button: Navigate to the "Earning options" screen
_- Refer Import NFT_

**Comment by Quangdm-cdm** [comment]
@ThaoNguyen998 this issue is fixed from PR #1398. Content for button is confirm
![image](https://github.com/Koniverse/SubWallet-Mobile/assets/85857151/4709b978-d276-463a-81c8-7252aa9d1676)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-306-1412-merge-2024-01-29T07-32-24.ipa
Device test: IP 11

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/a7159fb4-b13f-4463-b5d1-c7ceb7467358)

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/a5d083f0-f330-42e0-bc86-96678e985fe1)
