### ISSUE TITLE
Support desktop mode for dapp require agent config like airdrop.manta.network

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1380]
- Normally, websites on mobile devices just need to scale down to see all content of a page. But some need to setup user agent to "desktop" to work correctly. 
From issue #1338

**Comment by nguyenduythuc** [comment]
This issue was fixed and built directly to upgrade_ui branch on 1.1.27 (299)

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.27(299)
Device test: IP 11

Validation passed. (Zenlink, Manta)

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/9384750d-b711-4690-8193-01847dbc2d30)

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.27(299)
Device test: IP 11

Validation passed. (Zenlink, Manta)

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/9384750d-b711-4690-8193-01847dbc2d30)
