### ISSUE TITLE
Re-check bug reset data on IOS 17

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1381]
**Describe the task**
Follow-up bug reset data on IOS 17

 **To reproduce the task**

Version test: v1.1.27(299)
Device test: IP 11(IOS version 17.2)

**Comment by nguyenduythuc** [comment]
- [ ] Restore old backup data when remove an account
- [ ] Restore old backup data when import from JSON file
