### ISSUE TITLE
Mobile - Show incorrect unclaimed rewards after remove account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1383]
**Describe the task**
Show incorrect unclaimed rewards after remove account

**To reproduce the behavior**
Steps: 
1. Attach account have unclaimed rewards to wallet
2. Switch to All accounts 
3. Go to the Position detail screen then observe unclaimed rewards displayed
4. Remove account
5. Back to Position detail screen then observe unclaimed rewards displayed again

**Actual**: Show incorrect unclaimed rewards
- Record file: https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/EVU2qzqkrF5PtPEHGnUjnW4B3jkpGD5uFiG6PQEAbDjgkw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=ccu0Wc 
- Other actual: Do not show Unclaimed rewards (show loading icon)

Please re-check job to get rewards

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-299-1387-merge-2024-01-22T02-39-13.ipa
Device test: IP 11

Validation passed.
https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/EcrgMw2BHYVBnPw8C-7KfEUBvl2QsQY4CPwFeJfOjlNBdw?e=aPfcpU
