### ISSUE TITLE
[Earning] Show Rewards on Direct nomination of the Parachain (Vara, Creditcoin)

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1384]
Describe the task
Show Rewards on Direct nomination of the Parachain (Vara, Creditcoin...) although these pools do have no unclaimed rewards

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/51cd3abe-f7e5-4885-854d-55600973a287)

Expect: Hide this information

**Comment by ThaoNguyen998** [comment]
Waiting issue #1372

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-306-1400-merge-2024-01-29T08-54-59.apk
Device test: S20 FE 5G

Validation passed. 
- All account
- Specific account

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/0390bf73-88c4-44e3-b3c2-4ae3a7b913ae)
