### ISSUE TITLE
Add a temporary popup to introduce the earning feature

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1388]
- Header: Introducing Earning feature
- Content: SubWallet's **Staking** feature has been updated to become **Earning** feature. Now, you can earn yield with native staking, liquid staking, lending, and staking dApp on SubWallet. 
- Button: Dismiss / Earn now

* Note: When campaigns are running, showing this temporary popup first. Every campaign popup will be shown in next login.
Design: 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/6987808/cbda21e1-41dd-4d23-bb43-7b50c476c688)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-301-1392-merge-2024-01-22T11-29-55.ipa
Device test: IP 11

- [ ] Error page in Token Detail screen

  https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/498d3748-c9bd-40d5-bd29-c357747e4c54

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-301-1392-merge-2024-01-23T08-49-58.apk
Device test: IP 11, S20 FE 5G, MI 8Lite

Validation passed in case:
- Install
- Upgrade version
https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/EccBxBRhOftIqDB5J_vWgroB7AwgGqO_L-XNJhex-FZ85w?e=ukyBTn
