### ISSUE TITLE
Mobile - Add "time-out" status for transaction history

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1396]
**Describe the task**
Add "time-out" status for transaction history

**Actual:** The history show status = Failed if timeout (2 minutes)
**Expect:** 
- Show status = time-out for this case
- Sync status with Subscan to show correct status

Link design: https://www.figma.com/file/mfCcK60D4OWv42MlVvrJF4/SubWallet-UI-Base-1.0.1?type=design&node-id=2967-40372&mode=design&t=JHo7dD7CTbYYGOKY-0

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-308-1415-merge-2024-01-31T04-26-50.ipa
Device test: IP 11

- [ ] Do not sync transaction status with Subscan

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/75accd90-2381-4f8d-b9c7-aa0953666b7f)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-309-1415-merge-2024-02-01T10-40-22.ipa
Device test: IP 11

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/ca77b80f-cd20-4ac4-b607-9de512ab6085)
