### ISSUE TITLE
Bug performance on Start eanring screen with direct nomination

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1399]
**Describe the bug**
Bug performance on Start eanring screen with direct nomination

Actual: When open the start eanring screen of any direct nomination item then user encounters lag app
- Check with address 5DRewsYzhJqZXU3SRaWy1FSt5iDr875ao91aw5fjrJmDG4Ap on PDEX 
- Record file: https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/EaXa9_6p7LpJtbjM-Id_sNcBFrcoCnokKHuYKwDXtl5Gmw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=WcsoJ8

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.29(307)
Device test: IP 11

Validation passed. 

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/37a5b49c-fb1f-4747-b021-a109ed6b16e2
