### ISSUE TITLE
Mobile - Add price_id on Token details screen

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1407]
**Describe the bug** 
Show incorrect tag token on Token details screen

**To reproduce the bug**
Check with token BNCS, VARCH, cDOT-7/14
Actual: Show tag = Testnet
![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/68c28da6-5491-4227-99d5-821c0337ba2e)

-> Handle on web-runner 1.1.33

**Comment by Sokol142196** [comment]
- [ ] Please add "price_id" field on token details screen to update price_id

**Comment by ThaoNguyen998** [comment]
Wait update web-runner 1.1.38

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-315-1472-merge-2024-02-16T08-18-03.ipa
Device test: IP 11

- [ ] Add price_id field on Import token screen

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/bba37343-a86d-4a2d-8c33-b75d87b04a9d)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-318-1472-merge-2024-02-21T07-52-14.ipa
Device test: IP 11

@Quangdm-cdm Please fix bug unable to edit price-id on token detail(Custom token)

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/54eb779a-527b-4cee-98d2-bdda98d5fa49)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-318-1472-merge-2024-02-23T04-19-07.ipa
Device test: IP 11

Validation passed. 
- Add/Edit/Delete/Detail token

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/7186e300-c27d-4ef0-a93a-e5e81612725c)
