### ISSUE TITLE
Improve navigation and animation

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1409]
- List token animation
- Screen navigation animation

**Comment by Quangdm-cdm** [comment]
Need to implement this issue with 2 phrase: 
 - Phrase 1: https://github.com/Koniverse/SubWallet-Mobile/issues/1767
 - Phrase 2: https://github.com/Koniverse/SubWallet-Mobile/issues/1768

**Comment by nampc1** [comment]
Will be resolved in phases as mentioned above
