### ISSUE TITLE
Mobile - Add popup want to user claim reward when Astar update dApp staking v3

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1410]
**Is your feature request related to a problem? Please describe.**
Add popup want to user claim reward when Astar update dApp staking v3
- Case 1: Show when open app
  - Condition to show: User have dApp staking 
- Case 2: User click on dApp staking details (ASTR, SBY, SDN)

Content: 
- Header: Claim ASTR staking rewards
- Message: Astar dApp staking V3 is launching in early February. Make sure to claim any ASTR rewards before the launch or they will be lost.
  - Add hyperlink to "Astar dApp staking V3"
  - Hyperlink: https://docs.astar.network/docs/learn/dapp-staking/dapp-staking-faq/#q-what-about-unclaimed-rewards
- Button: Dismiss / Claim now
  - Dismiss: Close popup
  - Claim now: Redirect user to Astar Portal (https://portal.astar.network/) in browser in-app
  
 Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=16743-144961&mode=design&t=FefFPGnsCxNeJ4Xq-4

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.29(308)
Device test: S20 FE 5G

Validation passed. 
- Install
- Upgrade version

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/fde0ca8b-e22e-4e91-877e-d2d99031377f
