### ISSUE TITLE
Mobile - Handling Access Permission for Camera

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1417]
**Describe the task**
Handling Access Permission for Camera

**To reproduce the task**

Actual: After granting permission for the application to access the camera, users need to tap on the feature once again to open the QR code scanning screen(WalletConnect, Import by QR code,...)

Expect:  After granting permission for the application to access the camera, the QR code scanning screen will open automatically

**Comment by Quangdm-cdm** [comment]
Please check 
- Wallet Connect list in Setting
- InputAddress in SendFund
- InputConnectUrl in ConnectWalletConnect
- QrSigner account signing
- Import Account by QR code
- Import QrSigner account
- Button Scan in Header of Tokens screen
@ThaoNguyen998
