### ISSUE TITLE
Bug can not display NFT Video on Android

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Mobile#142]

**Comment by Sokol142196** [comment]
Version test: v1.0.13 (205):
- NFT is showing but showing NFT Collection image, do not show mp4

**Comment by ThaoNguyen998** [comment]
Version test: 
MI 8 Lite: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-205-938-merge-2023-08-11T04-31-00.apk
IOS: IP 11
Device test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-205-938-merge-2023-08-11T04-34-24.ipa
Validation passed.
