### ISSUE TITLE
Update method get static content for Earning, General T&C

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-Mobile#1421]
- [x] Update method get static data for Earning Pool Detail modal
- [x] Update method get static data for General T&C Modal

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-311-1394-merge-2024-02-03T08-21-04.ipa
Device test: IP 11

- [ ] Do not show Earning info

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/da34c4c3-247d-4d67-952f-d8393b6126b0)

- [ ] Do not update content after edit term_and_condition

**Comment by Quangdm-cdm** [comment]
> Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-311-1394-merge-2024-02-03T08-21-04.ipa Device test: IP 11
> 
> * [ ]  Do not show Earning info
> 
> ![Image](https://private-user-images.githubusercontent.com/117999489/304947574-da34c4c3-247d-4d67-952f-d8393b6126b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNTE1NzAsIm5iZiI6MTcwODA1MTI3MCwicGF0aCI6Ii8xMTc5OTk0ODkvMzA0OTQ3NTc0LWRhMzRjNGMzLTI0N2QtNGQ2Ny05NTJmLWQ4MzkzYjYxMjZiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQwMjQxMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjI2ZGIxNjc4YzNjNzkwNzFkOWExM2VkYTM4YzhiMzU3NTMwYjZiZjM2OWQxMTg0YzA2ZTFlMTUxNTNjOWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7Ub9CwRDHxuUMir0C3_-DB8Lu49CHTcoycQPSN9Rq0E)
> 
> * [ ]  Do not update content after edit term_and_condition

Pls enable dev mode and check again

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-318-1394-merge-2024-02-22T02-19-57.ipa
Device test: IP 11

Validation passed.
- Install app(Enable dev mode)
- Update app
- Update content Intruction
