### ISSUE TITLE
Add alert warning when user select yy validator although re-commended xx validators (xx > yy)

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1424]
**Describe the task**
Add alert warning when user select yy validator although re-commended xx validators (xx > yy)
- Apply for Direct nomination with relaychain

Header: Pay attention! 
Message: You are recommended to choose xx validators to optimize your earnings. Do you wish to continue with yy validator(s)?
Button: Go back / Continue
- Ciick Go back -> Close alert, back to Start earning screen
- Click Continue -> Navigate to the approve transaction

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-311-1432-merge-2024-02-03T09-59-55.ipa
Device test: IP 11

- [ ] Update text when select 1 validator
- [ ] Remove bold  for 'Go back'

**Comment by ThaoNguyen998** [comment]
Version test: 
Device test: IP 11

Validation passed in case: 
- Stake
- Stake more
