### ISSUE TITLE
Mobile app - Update web-runner v1.1.35

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1426]
**Describe the task**
Update web-runner v1.1.35

Details: https://github.com/Koniverse/SubWallet-Extension/releases/tag/v1.1.35

**Comment by ThaoNguyen998** [comment]
Version test: build 311
Web-runner: https://65bdb5f692a9333fbfb4b31f--sw-web-runner.netlify.app/

Validation passed in case: 
- Fixed bug not showing GENS token from Genshiro (https://github.com/Koniverse/SubWallet-Extension/issues/2540)
- Update unstaking request info for KREST, AMPE (https://github.com/Koniverse/SubWallet-Extension/issues/2544)
