### ISSUE TITLE
Mobile - Error page on Earning screen

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1427]
- When pool info get fail, value is undefined
- Also fix bug: auto reset selected pool to default

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-309-1428-merge-2024-02-01T09-00-10.ipa
Device test: IP 11, S20 FE 5G

Validation passed in case: perform all action earning
