### ISSUE TITLE
Mobile - Do not display the default desktop mode of some dApps

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1431]
**Describe the bug**
Do not display the default desktop mode of some dApps

**To reproduce the bug**

Version test: v1.1.29(308) - App store
Device test: IP 11
Actual: Check with Acala

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/8fb7e987-9abd-4d2d-af8a-bfc52571bb70)

**Comment by nguyenduythuc** [comment]
Released in 1.1.30 (311)
