### ISSUE TITLE
Mobile - [Earning] Improve navigation and animation PositionList and GroupList when Change Account or Pull to Refresh

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-Mobile#1433]
Improve loading screen when change account, pull to refresh in PositionList

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-309-1434-merge-2024-02-02T05-44-19.ipa
Device test: IP 11

- [ ] Error page when open Earning tab

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/e9c47205-e436-4be8-b167-b79e2bbec826

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-309-1434-merge-2024-02-02T05-44-19.ipa
Device test: IP 11

Validation passed. 
https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/Ec5EslLZvXBBqCQHSDe93O0Bk4roLmGVuo4qU8nENbns0A?e=rzFZkJ
