### ISSUE TITLE
Mobile - Error page on History screen

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1436]
**Describe the bug**
Error page on History screen

**To reproduce the bug**
Version test: v1.1.29(308)
Device test: IP 11

Steps: 
1. Perform earning successfully
2. Obserse the displayed screen

Actual: Error page
Note: After re-check  history screen ->error page

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/c8a092c3-2360-43f6-8a21-49e6ddea3937

**Comment by nguyenduythuc** [comment]
This will be fixed in #1396

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-309-1415-merge-2024-02-01T10-40-22.ipa
Device test: IP 11

Validation passed. (I can't reproduce the bug on the pr #1415)
