### ISSUE TITLE
DApp name is overlapped by tags in Browser DApp tab

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1437]
Fix this issue by following this ux: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=4956-322959&mode=design&t=9KJa6MjicK7WBVHh-4

**Comment by haiyenvu23** [comment]
Version test : PR #1454 02/07/2024 3:32 PM
Device test : IP 6S

- [ ] Re-check tag display in some dApps
![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/a7a1e902-e008-4ffb-a8ee-4e75536d813d)
