### ISSUE TITLE
Mobile - [Earning] Handle the case of switch tab on menu

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1439]
**Describe the task**

Handle the case of switch tab on menu

Expect: When in the details screen in the Earnings tab, switching to another tab and reopening will display the earning positions screen

**Comment by nguyenduythuc** [comment]
@ThaoNguyen998 pls, move case 2 to another issue. The issue need more time to be figured out

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-311-1446-merge-2024-02-03T11-02-43.ipa
Device test: IP 11

Validation passed in case: 
- Earning option
- {Token} Earning option 
- Earning position detail
