### ISSUE TITLE
Alert popup display continuously when turn on chain in earning pool

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1440]
**Describe the bug**
Alert popup display continuously when turn on chain in earning pool

**To reproduce the bug**
Device test: IP 6s
Actual: Show alert pop-up continuously when turn on chain get fail in Earning Pool List and Earning Group List

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/15f0dda2-a9ed-46cb-b244-2d6af46bcfeb

**Comment by ThaoNguyen998** [comment]
Follow-up on IP 6s

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-311-1441-merge-2024-02-03T09-31-05.apk
Device test: MI 8 Lite

Validation passed.
