### ISSUE TITLE
Add action close modal when click back virtual button

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-Mobile#1444]
Actual: press virtual back button will back to previous screen or exit app when open modal
Expect: close modal when click virtual back button

**Comment by haiyenvu23** [comment]
Version test : PR #1445 02/03/2024 4:37 PM
Validation passed

**Comment by haiyenvu23** [comment]
Version test : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-311-1445-merge-2024-02-03T09-37-07.apk

- [ ] Can not close Select network modal  when click virtual back button 


https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/55bb4e64-08f0-4b1e-93ac-f6976e3645d2

**Comment by haiyenvu23** [comment]
Version test : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-315-1445-merge-2024-02-15T07-52-15.apk
Device test : Samsung
Validation passed

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-315-1445-merge-2024-02-15T07-52-15.apk
Device test: S20 FE 5G

- [ ] Navigate incorrect screen in case create new account
Steps:
1. Perform create a new account
2. On Keep your seed phrase safe screen, click back button 
3. Observe the displayed screen 

Actual: Display Your seed phrase screen

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/d24119a7-9aa2-4221-947a-c5c35b067ac1

Expect: Navigate to Home screen

**Comment by haiyenvu23** [comment]
Version test : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-317-1445-merge-2024-02-19T10-52-25.apk
Device test: S20 FE 5G

- [ ] Navigate incorrect screen on Select pool and Select validator screen
**Steps:**
1. Stand on Select pool screen/Select validator screen
2. On Filter screen/Sorting screen/Pool details screen, click back button
3. Observe the displayed screen
Actual: Display Select pool screen/Select validator screen



https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/2f3dc7a2-00f8-4244-b577-8f5d3ac4fc9a

**Comment by haiyenvu23** [comment]
Version test : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-318-1445-merge-2024-02-21T02-49-34.apk
Device test : Samsung
Validation passed all case close modal when click back virtual button
 

https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/1648d103-3e72-43a2-86e9-70370d2dc8ae
https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/e3a84195-1de1-4eec-bf26-90503fb592b3
