### ISSUE TITLE
Mobile - Flash screen when re-open Crowdloans tab

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1448]
**Describe the bug**
Flash screen when re-open Crowdloans tab

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/afe659d5-91a0-42d1-ada0-456ca82a8206

**Comment by haiyenvu23** [comment]
Version test : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-317-1476-merge-2024-02-17T08-41-23.apk
Validation passed


https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/f0d2f41f-7435-4f23-a2fe-8c8484bf35a1
