### ISSUE TITLE
Mobile - Update UX turn on network when perform liquid staking, lending staking

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1453]
Describe the task
Update UX turn on network when perform liquid staking, lending staking
- Docs: https://www.notion.so/subwallet/Other-notes-5968b0d4f34349f8963167001315214a?pvs=4#3906ae9c025e4675bdf66af8f60e9af2

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.31(315)
Device test: IP 11

Validation passed.
