### ISSUE TITLE
[Mobile] Update position and options actions for Astar Staking DApp

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Mobile#1455]
Update UX for Astart Staking before support in SubWallet
Expect:

With option record have slug "ASTR___native_staking___astar", "SDN___native_staking___shiden", link to DApp
With position record has slug "ASTR___native_staking___astar", "SDN___native_staking___shiden" hidden number and show content "waiting for content"
Click to option or position => Popup show reason (waiting for content) => Dismiss or go to Astar Portal

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-313-1456-merge-2024-02-07T02-32-05.ipa
Device test: IP 11, S20 FE 5G

Validation passed
- Earning position
- Earning option
- Check with: ASTR, Shiden, Shibuya
