### ISSUE TITLE
Mobile - Update UI when transfer token for EVM chains

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1459]
**Is your feature request related to a problem? Please describe.**
Update UI when transfer token for EVM chains

- [x] Disable/hiude button Max when transfer native token of the EVM chains
- [x] Add warning when network is busy

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.31(315)
Device test: IP 11

Validation passed. 
![image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/b74e5be0-33f9-4dec-a4be-3eae8a296c44)
![image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/d2b8db40-2873-4df3-be89-7eba9665589d)
