### ISSUE TITLE
Mobile - Bug Failed to get data when stake more from position details screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1461]
**Describe the bug**

- [x] Do not get earning data when stake more from position details screen

To reproduce the behavior
Steps:
1. Go to the position details screen
2. Click on + or "stake more" 
3. Observe the screen displayed

**Actual:** Show "Failed to get data" although the network is connected
**Expect:** Get data successful then next step

- [x] Update UX when click on earning options
  - Actual: Show "getting data" then show start earning screen
  - Expect: Do not show "getting data" again

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-315-1466-merge-2024-02-15T05-25-57.ipa
Device test: IP 11

Validation passed. 
https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/Eal5h1Ucl0dOllQ6olaTBk0BCHhso1lPWlZf5CEgnmGg5A?e=ZHRNsT
