### ISSUE TITLE
Mobile - Bug do not show token on token details screen and search

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1462]
**Describe the bug**
Do not show token

When i reproduce this behavior, i derived a new account and setting "show zero balance" is ON.
Record file: 

https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/4abfed9c-23b9-44a1-953b-cd97e966e63b

**Comment by Quangdm-cdm** [comment]
Can't reproduce this issue in current version. Please check and close this issue.
