### ISSUE TITLE
Mobile - Update content for earning feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1463]
**Describe the task**
Update content for earning feature

- [x] Message in case Enter Amount > Available Balance (Available Balance > 0)
  - Actual: 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/a0b019b9-4070-4311-a4da-8ed506938395)

  - Expect: Show popup error:
    - Header: Insufficient balance
    - Content: Insufficient balance. Amount must be smaller than available balance
    - Button: I understand

- [x] Unstaking period info
  - Actual: Bifrost 7 days
  - Expect:
    - Bifrost: "up to 7 days"

**Comment by Sokol142196** [comment]
> @Sokol142196 Error message when Selected pool is undefined need time to verify. Please move this issue to new task

I moved this issue to https://github.com/Koniverse/SubWallet-Mobile/issues/1470

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-315-1468-merge-2024-02-15T10-42-42.ipa
Device test: IP 11

- [ ] Update unstaking period info for Liquid staking 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/4d210729-42d2-4282-9430-e2ba34e61101)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-315-1468-merge-2024-02-16T09-34-00.ipa
Device test: IP 11

Validation passed. 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/b0cc0096-eb90-4f64-b979-e495ecaa7b77)

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/fe2dd4fb-a8ae-454a-8474-8ad16fdaab54)
