### ISSUE TITLE
Mobile - UI bugs

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1464]
Describe the bug
- [x] Update text: "recovery phrase" -> "seed phrase"

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/55e212f5-a309-4501-99ef-758a3dbce0f4)

- [x] UI bug on NFT detail screen
  - [x] When scroll

    https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/31171b37-9269-4ab3-8ff1-62dc0c919073

  - [x]  Properties 

    ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/1fb2740d-c26a-4b41-846b-4ff9b72e5de7)
  - [x] UI bug on list NFT Conlection detail

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/53f24caf-3781-4e84-a73b-bb0d9abd1330)

- [x] UI bug when turn on network
  - Expect: Show only 1 toast
![image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/82e1edd8-03a6-4bb4-aeb6-452fd0d1f756)

- [x] UI bug Mission Pools detail screen on IOS

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/00c68bd3-9351-4885-912c-deb25fc39ac4)

- [x] Show blank screen when cancel Wallet Connect app to app
  Steps:
  1. On the SubWallet app, open Scan QR screen on WalletConnect
  2. Perform connect WalletConnect app to app
  3. Cancel request and observe the displayed screen

  Actual: Show blank screen

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/c19ff68f-b292-4a19-948d-1f8b7e438dc0

  Expect: Display Settings screen when there is no connection, display Connection List when there is at least 1 connection

**Comment by haiyenvu23** [comment]
Version test : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-317-1487-merge-2024-02-20T05-46-31.ipa
Device test : IP 7+

- [ ] UI bug when turn on network
Expect : If popup Connected appeared then popup Connecting close


https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/b1e37cda-ddfd-4dbb-9227-c0a7dd2b6fc7

**Comment by ThaoNguyen998** [comment]
@Quangdm-cdm Please update icon when search on Earning positions, Earning options

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/5502bb51-4289-4e3a-9318-03d8677657e8)

**Comment by haiyenvu23** [comment]
Version test : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-323-1487-merge-2024-02-26T04-09-28.ipa
Device test : IP 7+

- [ ] Change text color

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/be9ac53c-c77f-44d3-a7ca-b61d60caa195)

**Comment by haiyenvu23** [comment]
Version test : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-325-1487-merge-2024-03-01T11-54-50.ipa
Device test : IP 7+

- [ ] Update font-size seed phrase
**Expect** : Font-size = 12 according to design

**Comment by haiyenvu23** [comment]
Version test : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-326-1487-merge-2024-03-04T09-02-28.ipa
Device test : IP7 +

- [ ] Error when input Verify seed phrase
https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/98dbee3b-011b-4e28-9da9-b4113f11c9b8

**Comment by haiyenvu23** [comment]
Version test : 
- IOS : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-332-1487-merge-2024-03-11T03-32-36.ipa
- Android : https://www.diawi.com/qrcode/link/VowMxd
Device test : IPHONE 7+, SAMSUNG

- [ ] Update text color on IOS

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/898f222f-2752-4596-8b5e-1635fa99bdf5)

- [ ] UI bug of button Stake more

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/7c1fb402-70e0-4fc7-8234-c735a621eadc)

**Comment by haiyenvu23** [comment]
Version test : https://www.diawi.com/qrcode/link/FwjnFY
Device test : IP 7+
- [ ] Check if the seed phrase has duplicate characters


![Image](https://github.com/user-attachments/assets/f4159b19-a4b1-4626-ab51-41b423ddf50e)

- [ ] UI bug


![Image](https://github.com/user-attachments/assets/5dde5237-4269-495a-bc1d-5c4ebd35074d)

Expect : 


![Image](https://github.com/user-attachments/assets/c62b693a-64dc-4b4b-80f9-99150eaef135)

- [ ] Ui bug on Mission pools detail screen


![Image](https://github.com/user-attachments/assets/667e7a7a-68f8-4a14-b16c-25b3868a22a2)

- [ ] Re-check Align text and icon on button Stake more
Expect : Align = center


![Image](https://github.com/user-attachments/assets/619f08d2-bae9-471d-8159-398097180e79)

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/eJiCYm
Device test: IP 11, MI 8 Lite

Validation passed in these case.
