### ISSUE TITLE
Mobile - Setup default filter on earning options screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1465]
**Describe the task**

- [x] Setup default filter on earning options screen = "Main net"
- Update UI when filtering -> Move to #1473

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-315-1467-merge-2024-02-15T07-25-50.ipa
Device test: IP 11

- [ ] Do not show earning option = Testnet in case choose all

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/d4f9d787-dc65-4e04-8cc9-ea183946871e

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-315-1467-merge-2024-02-16T10-08-20.ipa
Device test: IP 11

Validation passed. 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/1abf6ced-c05a-403b-8c4d-05dfe4cf1fac)
