### ISSUE TITLE
Mobile - Turn off popup "Remind claim rewards for dApp staking"

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1481]
**Describe the task**
Turn off popup "Remind claim rewards for dApp staking"

**Expect**: Now that dApp staking v3 has been released => need to turn off popup "Remind claim rewards for dApp staking"

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/e9bb359f-2d19-4e6c-9267-13f34ae577db)

**Comment by haiyenvu23** [comment]
Version test : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-317-1483-merge-2024-02-19T11-17-49.apk
Device test : Samsung
Validation passed in case : 
- Update version
- Open new app
- Close then re-open app
- User click on dApp on Earning options screen
- Check case when user click on non-dApp staking details
- Reset all


https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/7c6a00f8-9348-49af-ae6a-3342b87f1032
