### ISSUE TITLE
Mobile - Update app for Staking Rewards

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Mobile#1484]
- [x] Support Deeplink for this features
- [x] Support earning preview
- [x] Support stake action with predefined validator, auto select address
  - [x] Auto select account
  - [x] Auto select validators
  - [x] Auto enable network
  - [x] Auto focus on amount

Flow: https://www.figma.com/file/b2n8Lz15UKwS5BG2y5dxgc/User-Flow---Staking-Rewards?type=whiteboard&node-id=0-1&t=yrQLxVKWIWYJEhGP-0
Preview data: https://github.com/Koniverse/Static-Data-Caching/tree/main/data/earning/targets

BA docs: https://www.notion.so/subwallet/Integration-with-Staking-rewards-2b63d60534fa4e4da4b17dd047ca84bd

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-319-1494-merge-2024-02-23T12-24-27.ipa
Device test: IP 11

- [ ] Navigate incorect screen

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/9266b392-9531-4c7f-8809-12f8532af7d0

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-324-1510-merge-2024-02-29T08-29-30.ipa

Please check issues:

- [ ] Handle case has no account in wallet
  - Actual: Navigate to the Earning tab but no account
  - Expect: Navigate to the Earning Preview screen (Instruction on Earning Preview)
    - Refer flow: https://www.figma.com/file/b2n8Lz15UKwS5BG2y5dxgc/User-Flow---Staking-Rewards?type=whiteboard&node-id=0-1&t=yrQLxVKWIWYJEhGP-0
 
- [ ] Update message in case Invalid account type
![image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/cc57c3e9-33e3-4399-b197-82d7a86b69d6)

**Comment by ThaoNguyen998** [comment]
Version test:  https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-326-1510-merge-2024-03-04T11-20-33.ipa
Device test: IP 11

- [ ] Do not navigate Select validator screen 

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/0fdf751a-1d2d-4149-b64b-86f9d7f843f8

**Comment by haiyenvu23** [comment]
Version test : 
- Demo page: https://h5tyq5.csb.app/

- [ ] 1. Update logic when using invalid accounts 

**Steps** : In the case when the wallet does not have an account
1. Stand on popup Instrucsion earning
2. Click button Start to earn -> Navigate to Welcome screen to Create account/Import account/Attach account
3. Perform Import account/Attach account invalid
4. Click button Finish

**Expect** : 
- Option 1 : Navigate to Earning options screen , display popup Invalid account type
- Option 2 : Navigate to Start earning screen , display popup Invalid account type

- [ ] 2. Update logic for previously staked account

**Steps** 
1. Stand on popup Instrucsion earning
2. Click button Start to earn 
3. Navigate to Start earning screen

**Expect** : 
-  When the account has been nominated => show popup Pay attention
-  When the account has been pooled => show popup Pay attention

- [ ] 3. Updated case Account has unstake all (Active stake = 0)

**Expect** : 
Show popup with information : 
 - Header: Pay attention
- Message: This account is unstaking all stake and can't nominate validators. You can change your account on the Account tab or try again after withdrawing unstaked funds
- Button: I understand

**Comment by haiyenvu23** [comment]
- [ ] Can not display validator name

**Comment by ThaoNguyen998** [comment]
Version test:

- [ ] Can't turn off Intruction in case Create new on popup Invalid account

https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/EYsOZhSYDd1Bkzisv1cymX0BZHUyezvvXUNFYMTTyVCWBw?e=avANwa

**Comment by haiyenvu23** [comment]
Version test : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-333-1510-merge-2024-03-12T02-33-46.apk
Link demo : https://h5tyq5.csb.app/

- [ ] In case the wallet does not have an account
Steps : 
1. Choose validator invalid from deeplink 
2. Select Create a new account on Welcome screen
3. After create account, navigate to Start earning screen
4. Observe the display screen
Actual : Don't show popup Unrecommed , auto select invalid validator
Expect : Show popup Unrecommend 

https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/e112c90d-fd18-407d-b5ed-8d45040cbdcc
