### ISSUE TITLE
Mobile - Update tabbar

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1485]
**Describe the task**
Update tabbar:
- Rename "Browser" to "dApps"
- Include tabbar: Tokens, NFTs, Earning, dApps, Crowdloans
- Update icon for Earning  
  - Icon: 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/7e1c094a-a5c9-41d7-8f0a-1df791f8a6bf)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-317-1486-merge-2024-02-20T04-08-17.ipa
Device test: IP 11

Validation passed

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/36079a1f-11ec-42b9-984c-3a59c5fd9ee9)
