### ISSUE TITLE
Move mission pool into dapp browser

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1488]
- List out mission pool in dApps browser tab
- Remove mission pool from setting
- Remove dApp url and move dApp tags to bottom of dApp item

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-318-1490-merge-2024-02-21T03-17-29.ipa
Device test: IP 11

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/2b606091-f261-4923-8bf3-5b403a932804)

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/974389e0-fd0f-4dcc-bb57-07d27e31d9b0)
