### ISSUE TITLE
Mobile -  Display error of popup to introduce the earning feature

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Mobile#1489]
**Describe the bug**
- [ ] Display error of popup to introduce the earning feature
Expect : Popup Introducing Earning feature displays on the Home screen

https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/cfdde3f4-2b17-43b6-9dee-819613c0ae1d

**Comment by Sokol142196** [comment]
Can't reproduce this behavior on v1.1.80
