### ISSUE TITLE
Mobile - Timeout when re-open the app

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Mobile#1491]
**Describe the task**
Time-out when re-open the app

**Steps** : 
1. Setup time on Require unlock screen
2. Exit the app and wait according to the previously set time
3. Re-open app, observe the displayed screen

**Expect** : When re-open app, must display the Unlock screen

https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/a23d49e3-e420-4df2-805b-90be1683f013

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/PPKuSc
Device test: IP 11

- [ ] Re-check case lock app the first time in case change Require unlock Always -> 1 minute
Actual: Do not lock the app

**Comment by Quangdm-cdm** [comment]
> Version test: https://www.diawi.com/qrcode/link/PPKuSc Device test: IP 11
> 
> * [ ]  Re-check case lock app the first time in case change Require unlock Always -> 1 minute
>   Actual: Do not lock the app

- In this case, when locktime = Always, as soon as you finish unlocking the app, the app will lock the keyring immediately. So, after you put the app in the background, the app will be locked. 
- When you change the locktime from Always -> 1 minute, the first time you put the app in the background the app will still lock immediately, the next time it will be locked according to the new locktime.
@ThaoNguyen998

**Comment by Sokol142196** [comment]
Version test: v1.1.80 (431)
Device test: IP 8 Plus (16.8)

Please check issues:
- [ ] Error occurs when setting "Require unlock" = "Always"
  - Example: Derive account and perform send token
  - Actual: Show infinite popup request to unlock
  
  https://github.com/user-attachments/assets/71d1a9d3-5b93-4cd7-8abb-20723098444e

  https://github.com/user-attachments/assets/6fa82f00-05d6-4722-862b-f3488680080b

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/jJyu4d
Device test: IP 13

Validation passed

**Comment by ThaoNguyen998** [comment]
Version test: 
Device test: IP 13

- [ ] Request to unlock multiple times before the time to lock the app
  Steps: 
  1. Setup time requires unlock = 1 minute
  2. Exit the app and wait according to the previously set time
  3. Re-open app and observe the displayed screen
  
  Actual: Request to unlock multi times

  https://github.com/user-attachments/assets/f1e280e9-3e6e-406a-b5f6-037404b667ef
