### ISSUE TITLE
Mobile - Turn off userAgent when desktop mode is disabled

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1492]
- On some dApp detecting user agent to show layout matching with device size, we need to disable user agent to let the dApp detect right device size.
- Action: check if desktop mode is disabled, turn off user agent.
- To reproduce this issue, check Bifrost dApp

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-318-1493-merge-2024-02-23T03-34-24.ipa
Device test: IP 11

- [ ] Unable to connect airdrop.manta.network

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/ea17d91b-2be5-4391-8d6d-0ab00a9d5e24)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-318-1493-merge-2024-02-23T04-53-14.ipa
Device test: IP 11
Validation passed. 
Re-check with other dApp: Acala, Karura, Mangata, ...
![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/6f44456f-1f4b-4afc-8ea9-67b9764769a3)
