### ISSUE TITLE
Mobile - Update web-runner 1.1.39

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1497]
**Describe the task**
Update web-runner 1.1.39
- Adjust showing/validating address on Send fund (logic)
- Update IPFS domain for NFTs from Unique network
- Update filtering out blocked validators
- Update validation logic for Chainlist
- Fixed bug show incorrect token in case the wallet has only 1 account type

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-324-1508-merge-2024-02-29T05-33-12.ipa
Device test: IP 11

Validation passed in case: 
- Adjust showing/validating address on Send fund (logic)
- Update IPFS domain for NFTs from Unique network
- Update filtering out blocked validators
- Update validation logic for Chainlist
