### ISSUE TITLE
Mobile - Restructure Settings screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1498]
**Describe the task**

- [x] Restructure Settings screen

Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=14361-193742&mode=dev

- [x] Add "Contact support" option
  - Expect _(refer Request a feature option)_
   - When click on this option then show Open mail to send email
   - Subject mail: [In-app Support]
   - To: agent@subwallet.app

**Comment by haiyenvu23** [comment]
Version test : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-323-1509-merge-2024-02-27T12-10-13.ipa
Device test : IP 7+

- [ ] Update icon 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/12d4fcdb-3564-4ab2-9d6e-89b4fa769b99)

- [ ] Navigation error when clicking on X(Twitter)

https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/8e59eb70-279f-4a70-9073-dfada09f8b34

**Comment by haiyenvu23** [comment]
Version test : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-324-1509-merge-2024-02-29T08-43-50.ipa
Device test : IP 7+

Validation passed in case : 
- Add "Contact support" option

https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/e98025f6-8d25-4909-a4ca-cbc65458bfba

- Navigation when clicking on X(Twitter)

https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/cda9aeef-6db0-49c2-a9c2-c95d085b674e

**Comment by ThaoNguyen998** [comment]
@Quangdm-cdm Please update icon WalletConnect

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/292b11d8-c19b-4cd9-b6ee-a84ca488e1ac)

**Comment by haiyenvu23** [comment]
Version test : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-325-1509-merge-2024-03-01T03-15-06.ipa
Device test : IP 7+ 
Validation passed 
https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/c0af4417-3878-4804-8cc1-90fdcbd5ce9a
