### ISSUE TITLE
Mobile - Adjust showing/validating address on Send token, Send NFT, History

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1499]
**Describe the task**
Adjust showing/validating address on Send token, Send NFT, History

Expect: Formatting address by Network address
- Refer Extension v1.1.39 to update this issue (https://github.com/Koniverse/SubWallet-Extension/issues/2628)

**Comment by nguyenduythuc** [comment]
Will be fixed in #1497

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-323-1508-merge-2024-02-28T04-48-23.ipa
Device test: IP 11

- [ ] Unable to send in case scan QR address

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/ec510426-d3fe-45c3-b537-c4ef1dd9c57c

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-324-1508-merge-2024-02-29T05-33-12.ipa
Device test: IP 11

Validation passed in these case.
