### ISSUE TITLE
Mobile - Update Error screen, recommend upload crash log

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1500]
- Add content to explain why we need to upload crashing log when it happens
- Add action to upload crashing log
- Add API to upload crashing log

**Comment by nguyenduythuc** [comment]
- Try to access data undefined in login screen:
![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/6987808/705825bf-0429-4505-beff-dd258e3235ca)

- Error screen displayed:
![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/6987808/64fe4b6b-764c-4bc9-9cae-95e352654ace)

- All error data was saved as expected:
![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/6987808/91b8adda-54b7-4563-b23c-da3fc6618113)

**Comment by haiyenvu23** [comment]
Version test : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-323-1503-merge-2024-02-27T08-13-30.ipa
Device test : IP 7+ 

- [ ] Update logic
      **Expect** : When click "Send report" button -> close Error screen and back to Home screen

- [ ] Remove toast
![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/8cbca495-0b94-4075-ae72-3e6091b48901)

- [ ] Updated according to design
      **Expect** : Add title screen :  "Unknown error"
![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/72471f80-e407-46da-b0fa-f0ea8d85edfe)

**Comment by haiyenvu23** [comment]
Version test : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-323-1503-merge-2024-02-27T10-40-15.ipa
Device test : IP 7+
Validation passed
https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/e4ea5031-b81d-4ec5-b8c1-ffef9af7ca9c

- Sent information has been received
![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/e26d4208-d5a4-440c-ac3c-aa02c5f595c6)
