### ISSUE TITLE
Mobile - Do not show "Cancel unstake" button incase have both Cancel unstake and Withdraw button

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1502]
**Describe the task**
Do not show "Cancel unstake" button incase have both Cancel unstake and Withdraw button

**Actual:** 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/4fe0fb05-a4b3-41a0-8a62-37429262abb8)

**Expect:** 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/dd955107-f9b9-41bc-b1f6-3e747ab8fae8)

**Comment by Quangdm-cdm** [comment]
This issue is close without PR because can not reproduce issue at newest version
