### ISSUE TITLE
Mobile - Update transaction result screen

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1506]
Update transaction result with content:

en, ja, ru: 
Header: Submitted
Message: 
- Transaction submitted! 
- Track transaction progress in the History tab or go back to home
vi:
Header: Gửi thành công
Message:
- Gửi giao dịch thành công!
- Vui lòng theo dõi quá trình thực hiện giao dịch trong mục Lịch sử hoặc về trang chủ
zh:
Header: 提交成功
Message：
- 交易提交成功！
- 请在记录页签中跟踪交易进度或返回主页

-----
**Japanese**
Header: 送信完了
Message:
トランザクションの送信完了！
履歴タブでトランザクションの進行状況を追跡するか、
ホームに戻ってください。

-----
**Russian**
Header: Отправлено
Message:
Транзакция отправлена!
Отслеживайте прогресс транзакции во вкладке История или вернитесь на главную страницу

**Comment by Sokol142196** [comment]
Waiting for updates other languages:
- Japanese
- Russian

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-327-1507-merge-2024-03-06T11-20-18.ipa
Device test: IP 11 
Validation passed. 
- Send fund
- Send NFT
- Stake/ Stake more
- Unstake/ Cancel unstake
- Withdraw
- Claim reward
![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/8731bc92-a20b-4e06-bec4-57f0859f9fd4)
