### ISSUE TITLE
Mobile - Auto detect mission pool status by timeline

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1511]
- Detect mission pool status in item's tag
- Filter mission pool tab by timeline
- Show status and "Join now" button status in mission pool detail

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-323-1512-merge-2024-02-28T09-27-09.apk
Device test: S20 FE 5G

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/13111f0f-6bb2-4fa7-9a13-e4deadc24f7b)
