### ISSUE TITLE
Mobile - Show incorrect token in case the wallet has only 1 account type

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1516]
**Describe the bug**

- [x] Show incorrect token in case the wallet has only 1 account type

**Actual:** Wallet have Substrate account but show tokens of the EVM chain

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/01fe8958-767d-4a68-96ff-c506c899e058)

Expect: Show correct token

- [x] Show incorrect list token in case select token earnings options when the wallet has only 1 account type

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/b79621c4-f7d7-4c3b-9c7e-a41758a87488)

**Comment by Quangdm-cdm** [comment]
@ThaoNguyen998 please re-check this issue and close. I can't reproduce this bug in latest version mobile app

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.74
Device test: IP 11, MI 8 Lite 

I can't reproduce this bug on the newest version  --> Close issue.
