### ISSUE TITLE
Mobile - Bug pool info is undefined

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1517]
- Check undefined pool info in Earning flow and earning transaction confirmation

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/6987808/1c1c809f-86f8-48e1-9be7-d50a028db2dc)

**Comment by ThaoNguyen998** [comment]
Version test: 
Android: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-325-1518-merge-2024-03-01T10-12-26.apk
IOS: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-325-1518-merge-2024-03-01T10-14-26.ipa

Validation passed. 
- Re-check with all action: Stake, Stake more, Unstake, Cancel unstake, Claim reward, WIthdraw
