### ISSUE TITLE
Mobile - Disable field Select token, Select network on Amount screen when Transfer

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1519]
**Describe the task**
Disable field Select token, Select network on Amount screen when Transfer

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/7a6447be-a207-4edf-bcfe-176e362a6d40)

**Comment by saltict** [comment]
Updated:
![simulator_screenshot_23D4FF08-0992-4DE2-A144-8B27D16B2F6B](https://github.com/Koniverse/SubWallet-Mobile/assets/11567273/b4c87216-4c7d-4490-a44a-0608a9bb4c7c)

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.36(326)
Device test: IP 11

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/0e687a2f-4bc6-4c07-80cf-a969cef7152e)
