### ISSUE TITLE
Update API get "buy token" from Strapi

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1527]
- Use Strapi to configure the "Buy" button: https://content-stage.subwallet.app/admin/content-manager/collectionType/api::buy-button.buy-button?page=1&pageSize=10&sort=version:ASC
- API to get the list of versions: https://demo-calculator.pages.dev/tokens/config.json

** After finishing the integration, switch to using the production API instead.

**Comment by Quangdm-cdm** [comment]
This issue has been implemented and put into use. Please close it @nampc1
