### ISSUE TITLE
Mobile - Do not show account on the Account's token details screen in case all balance is locked

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1529]
**Describe the bug**
Do not show account on the Account's token details screen in case all balance is locked

Actual:
https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/EUjKjRPFkBtJqEMhg9TBuSIBLjU98_3Ot8jXOGSzdRzxDQ?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=OnM7d2 

**Expect**: Show account

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-340-1550-merge-2024-03-27T09-37-16.ipa
https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-340-1550-merge-2024-03-27T08-57-37.apk
Device test: IP 11, S20 FE 5G

Validation passed.

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/c16071d6-86e1-4beb-8e56-45a0f7b68f4a
