### ISSUE TITLE
Mobile - Bug related to Staking rewards

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Mobile#1534]
**Describe the task**
Bug related to Staking rewards
- Demo page: https://h5tyq5.csb.app/
- Version test : 
  - Diawi QR (IOS): https://www.diawi.com/qrcode/link/g5P357
  - Diawi QR (Android) : https://www.diawi.com/qrcode/link/9zt28W
  
**To reproduce the bug**
- [x] 1.Hide button Random validator in Select validator screen

- [x]  2.Improve navigation after creating a valid account from the Invalid account type popup
**Expect** : Navigate to the Start earning screen after creation
  
  https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/0aab41a8-780b-42c2-a8e2-40ae4a079ff3

- [x] 3.On specific mode ( EVM) and have many valid accounts in app, after click from Staking Reward, can not navigate to Start earning screen
Expect : Navigate to Start earning screen and the user will proactively Select account 
 
   https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/7b9d70e5-8d5b-4fb3-a81a-0fecedb208e9
- [x]  4.Wrong screen navigation when click button Explore earning options
**Actual** : Navigate to Your earning positions screen
**Expect** : Navigate to Earning options screen

---------
### Improve later -> Move #1573 

-  5.In case account nominated with invalid validator, popup shows 2 times and display popup Unrecommend on Instruction screen (Sometimes it happens)
**Expect** : 
   - After click button Start to earn -> navigate to Start earning with popup Pay attention 
   - Click button Change validators -> show popup Unrecommend

- 6.Improve navigation after click button Create new on the Invalid account type popup
**Actual** : Navigate to Your seed phrase screen
**Expect** : Navigate to Account tab screen
- 7.Improve case auto enable network
**Actual** : Show popup Enable network
**Expect** : Auto enable network

- 8.The return value is correct but slow
**Expect** : Need to return value quickly
=> Related to issue #1535 
  https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/c8bf7719-5a2d-45cf-9a77-46ebf3cb5ec9

- 9.Show duplicate instruction 
  Actual: Displayed popup Pay attention

   ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/1e66971c-2d70-484a-a08a-7748a4e0af0b) 

  Expect: Do not show popup instruction

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-333-1510-merge-2024-03-14T08-12-59.ipa
Device test: IP 11

- [ ] Unable navigate to Start earning in case create new account on popup Invalid account
Actual: Display Verify seed phrase
https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/EbxdU2ScGeNOvtN2wofQsFoBTa4nhlQ_hUT8CxOQr8tLEA?e=92SI90

**Comment by ThaoNguyen998** [comment]
Version test:  https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-333-1510-merge-2024-03-15T04-36-58.ipa
Device test: IP 11

Validation passed in case 1,2,3,4

**Comment by haiyenvu23** [comment]
Demo page: https://h5tyq5.csb.app/
Version test : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-333-1510-merge-2024-03-15T04-36-59.apk
Device test : Android

- [ ] In case account nominated with invalid validator, display invalid validator


https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/19af32fe-f083-4270-be94-410ba3b9027e
