### ISSUE TITLE
Mobile - Disallow staking to collators/pools that maxed out member threshold (Implement UI)

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1536]
**Describe the task**
Implement UI in case Disallow staking to collators/pools that maxed out member threshold 
Refer: https://github.com/Koniverse/SubWallet-Extension/issues/2754

**Expect:**
- Grey item
- When click to select collator/pool then show message to warning to user

**Comment by haiyenvu23** [comment]
- [ ] Display wrong status color
Please re-check with Open/Locked/Destroying status color

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/7326ee5d-9c06-4662-8683-b086ca54edce)

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/34b1Sj
Device test: Ip 11 

- [ ] Update for Direct nomination - Relaychain
  - Still allow select
  - Add Nominator on the Validator detail

- [ ] Update for Direct nomination - Parachain
  - Still allow select
  - Add Delegator on the Collator detail

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/UszyyW
Device test: IP 11

- [ ] Re-check font size

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/cc7d2175-ac97-4f65-bf9e-81d5864e75fc)

- [ ] Update text

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/892ac8c7-0cf4-4cc8-b912-5a82deb723f3)

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/q3z9E8
Device test: IP 11

Validation passed in case: 
- Nomination pool

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/0b428230-b62b-42eb-baa2-71a3e1b039d8)

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/45bc4d9c-55a1-4b38-8bad-af4ab7b1ad1b)

- Relay chain 

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/ed6bdbec-c850-40ad-8c4c-312f2c9738bf)

- Parachain

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/beed24d0-dadf-4fc6-8467-95afba7162c3)
