### ISSUE TITLE
Mobile - Improve the Marketing Campaign application mechanism ( Phrase 1) 

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-Mobile#1538]
Improve Marketing Campaign application mechanism
Roadmap: https://xmind.ai/share/rw9QKKI1?xid=1z6I9jKT
Phrase 1: 

- [x] Build the core to manage online resources: 
 - Response is adjusted according to frequency
 - Displayed according to conditions from balance and earnings
 - Perform actions according to the settings
 - Supports instruction before performing actions

- [x] Supports App Popup display
- [x] Supports App Banner display

-------
- [x] Handle Balance conditions
- [x] Handle Earning conditions
- [x] Handle App popup/App banner display according to Frequency conditions
- [x] Add Title and media fields for Instruction
- [x] Design display style for popup (Displayed in each box)
- [x] Updated the display of banners in slide format, improving image loading time

Phrase 2:  Related to issue #1546

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-334-1540-merge-2024-03-20T03-07-19.ipa
Device test: IP 11

@Quangdm-cdm Please check: Add popup

- [ ] Show popup when re-open app(config Repeat= once )
  https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/ETepRKY8nkdCjWlvTxwR5_sBu-yMXosOgbDF_qBg98BK2Q?e=aM6Xuy

**Comment by haiyenvu23** [comment]
Version test : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-335-1540-merge-2024-03-21T09-39-05.ipa
Device test : IP 7+
- [ ] Show popup when re-open app(config Repeat= once )

https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/74688c4b-d727-4ad4-ac61-b75b9a2a59bf

**Comment by haiyenvu23** [comment]
Version test : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-335-1540-merge-2024-03-21T11-04-26.ipa

Device test : IP7+

- [ ] Error display popup (config Repeat= once )


https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/fa1f5958-7f69-4c9e-8bb7-95e219ce8d58

**Comment by haiyenvu23** [comment]
Version test : 
- IOS : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-335-1540-merge-2024-03-22T05-53-01.ipa
- Android : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-335-1540-merge-2024-03-22T05-52-28.apk

- [ ] Error when click back on device
**Expect** : When click back on device, popup must remain intact

https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/ffa684fd-e5b3-44bb-bb63-420413855018

**Comment by haiyenvu23** [comment]
Version test : 
- Diawi QR (IOS) : https://www.diawi.com/qrcode/link/fMzEYa
- Diawi QR (Android) : https://www.diawi.com/qrcode/link/w2yMtM

- [ ] Error showing wrong popup order

https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/60aa6dc6-fb4d-4783-a70e-711ad8ae84ee

- [ ] After click button Cancel on popup Intruction
**Expect** : Close popup

**Comment by haiyenvu23** [comment]
Version test : 
- IOS : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-339-1540-merge-2024-03-26T04-13-25.ipa
- Android : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-339-1540-merge-2024-03-26T04-13-23.apk

- [ ] In case install version, display the above 2 popups at the same time in the app


https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/8339ff10-118a-455b-b3d3-d763d4ae71f6

**Comment by haiyenvu23** [comment]
Version test : 
- IOS : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-339-1540-merge-2024-03-26T09-13-46.ipa
- Android : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-339-1540-merge-2024-03-26T09-14-02.apk

Validation passed in case : 
- Install/Update version
- Supports App Popup display
- Supports App Banner display



https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/86a152c6-6c54-474a-8f42-7ba46d05aa83

**Comment by haiyenvu23** [comment]
- [ ] Update Instruction for banner
- [ ] Update display conditions for banners

**Comment by haiyenvu23** [comment]
Problems resolved : 
- Supports App Popup display ( display on Token, NFT, Earning, Crowdloan screen)
- Supports App Banner display ( display on Token_detail, NFT, Crowdloan screen)
- Handle Balance conditions
- Handle App popup/App banner display according to Frequency conditions
- Add Title and media fields for Instruction


![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/bdb1f748-ea50-4bad-b607-a061c25bfcfd)


- Design display style for popup (Displayed in each box)


![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/1bb69ffa-8055-4aa4-9799-aa6b45d9ada7)


- Updated the display of banners in slide format


https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/894e1d82-2e5d-471a-b4ae-449470928bd2

**Comment by haiyenvu23** [comment]
There are still some errors listed in issue #1546
