### ISSUE TITLE
Mobile - Add Swap button

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1541]
**Describe the task**
Add Swap button for mobile app
- Click button then navigate to the Swap feature on SubWallet WebApp on browser in app
- Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=252-8888&mode=design&t=G7e7C0KVkIu1Gfl4-4

**Comment by haiyenvu23** [comment]
Version test : https://www.diawi.com/qrcode/link/xgJcWv


- [ ] UI bug

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/286f064a-a829-442b-b191-92d149936eb4)

**Comment by haiyenvu23** [comment]
Version test : 
- IOS : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-342-1551-merge-2024-03-29T04-23-31.ipa
- Android : https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-342-1551-merge-2024-03-29T04-17-26.apk

Validation passed 


https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/c00f2f2a-e60a-4d42-814c-0f5a2888a29e
