### ISSUE TITLE
Navigation support users by platform

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-Mobile#1542]
Navigation support users by platform:
- Android: navigate to agent@subwallet.app
- iOS: support@subwallet.app

**Comment by ThaoNguyen998** [comment]
Version test: 
Device test: S20 FE5G, IP 11

Validation passed.

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/bb437f06-a46a-4bcc-a9f0-ccfcb957ec61)
