### ISSUE TITLE
Mobile - Add some features of marketing campain ( Phrase 3)

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Mobile#1546]
**Describe the task**

- [x] Added checks for several types of conditions:
 - Crowdloan
 - NFT
 - Has money

- [x] Supports App Confirmation display

- [x] Re-check condition balance, earning on App banner, App 

- [x] Apply instructions online, change type markdown

- [x] Add position: earning, NFT, token for App banner

- [x] Improve multi-banner for App instruction

- [x] Add position params for NFT
- [x] Add banner for Mission pool

- [x] Improve time slider 3s -> 7s(dapps)

- [x] Fix bug when deleting an account that meets the conditions
  Actual: still show banner

- Error navigating from instruction screen to earnings option when the wallet has a different account type
Pre-condition: Instruction = AZERO, Wallet has account EVM
Actual: Show earning options blank
Expect: Navigate to the earning options
 
  ![image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/9dddd256-e98b-4022-9d79-6b54c7dc31e6)

- [x] Fix bug crash app when instruction have not URL and have not color

**Comment by haiyenvu23** [comment]
- [ ] Handle App popup/App banner display according to Frequency conditions
- [ ] Add Title and media fields for Instruction
- [ ] Design display style for popup (Displayed in each box)
- [ ] Updated the display of banners in slide format, improving image loading time

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/HkzKDh
Device test: IP 11

- [ ] Do not show banner in Current account in case account hasn't NFT
Pre-condition: Set up condition show banner: have NFT 
Actual: Do not show banner on Current account if the account hasn't NFT
Expect: 
Option 1: Keep the logic intact, only display the banner on accounts that meet the conditions and all account mode
Option 2: Display the banner if there is at least one account that meets the conditions. In case of an invalid account, redirect to the Token earning option screen and automatically switch to All account mode.

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/P8tEFw
Device test: IP 11

- [ ] Update UI in case multi banner
