### ISSUE TITLE
Mobile - Do not show confirmation in case perform transaction on dApp HydraDX

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1548]
**Describe the bug**
Do not show confirmation in case perform transaction on dApp HydraDX

**To reproduce the bug**
Steps: 
1. Connect dApp HydraDX with account EVM
2. Perform transfer WETH 
3. Sign transaction and observe the displayed screen

Actual: Do not show confirmation

 https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/EW0l5UDsBfNLtD27tKzqUtcBuQ9mDJ25B9kjq7F6qhbKcg?e=ZUeR2W

Check with account: 0xad5b1332faa1765f1d1e9f3b326a3c1ac2692f8b

**Comment by Sokol142196** [comment]
@ThaoNguyen998 please verìy this issue

**Comment by ThaoNguyen998** [comment]
I can't reproduce the bug on the newest version. -> Close issue
