### ISSUE TITLE
Mobile - Follow up and fix bug error page

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1549]
**Describe the task**
Follow up and fix bug error page

- [x] Cannot read property 'priceId' of undefined
- Invalid decoded address length
- Cannot read properties of undefined (reading 'toString')

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/3RWseu
Device test: IP 11

Validation passed in case: 
- Stake/ Stake more
- Unstake/ Cancel unstake
- Withdraw/ Claim reward
- Nomination pool
- Direct nomination
- Liquid staking
- Lending staking
