### ISSUE TITLE
Mobile - Implement Swap feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1554]
Describe the task
Implement Swap feature
- BA doc: https://www.notion.so/subwallet/T-nh-n-ng-swap-f71eec19664547d9800bf1dc1a0fa0d4?pvs=4 
- Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=19198-233563&mode=design&t=uHtRjhBx7DTYqSvo-4

**Comment by ThaoNguyen998** [comment]
- [ ] Update logo Chainflip on Swap quote detail 
- [ ] Show incorrect Slippage for Chainflip

**Comment by haiyenvu23** [comment]
Version test : http://192.168.10.193:9001/

- [ ] Change text 


![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/3bffe362-f511-48f1-9083-2ab65d9594ab)

**Comment by ThaoNguyen998** [comment]
- [ ] Do not save the address on Recent in case input a valid address
- [ ] UI bug on Instruction

   ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/3d36fd76-4842-4216-aedd-6bf0b7089047)

- [ ] Update transaction history
  
    ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/b7446620-ca0b-45ce-9201-6a8aa2db10af)

**Comment by ThaoNguyen998** [comment]
Version test: 

- [ ] UI bug in case input Custom slippage with decimal

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/13c0de11-0306-453b-bd32-335665c0b60f)

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/1a61a8e3-5e5d-47ad-bdfc-bf8846ebbcc6)

- [ ] UI bug

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/4b3ecdcb-a340-4539-a660-d80e6c81702e)

**Comment by ThaoNguyen998** [comment]
- [ ] Show incorrect message in case Specific account (EVM account)

    ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/a2774154-ad04-44d6-a694-ee7b0e973200)

    Expect: Show pair ETH -> DOT

**Comment by ThaoNguyen998** [comment]
- [ ] Show incorrect message in case swap to token detail
   Check with USDC

    ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/302bb2f8-500c-407c-8a83-f4a08326151a)

- [ ] Update default token in token detail(Select token)

    ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/fe8ee9e8-7214-4a1c-ad3a-7869fc68c312)

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.49(359)
Device test: IP 11
Validation passed in these case

Improve on #1587

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.49(359)
Device test: IP 11
Validation passed in these case

Improve on #1587
