### ISSUE TITLE
Mobile - Show Validator details pop up when navigating from the Staking Rewards page

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Mobile#1557]
**Describe the task**
Show Validator details pop up when navigating from the Staking Rewards page

**Actual:** Show Instruction popup
**Expect:** 
- When click on Stake with SubWallet on Staking rewards page then navigate user to the Earning-preview screen and show popup Validator details
https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=20068-164447&mode=design&t=3PCZeZWi3ZbIHM2x-4 
- User click "Stake to earn" on Validator detail popup then navigate to the Start to earn screen and show Instruction

**Comment by haiyenvu23** [comment]
Version test : 
- IOS : https://www.diawi.com/qrcode/link/aG41Dz
- Android : https://www.diawi.com/qrcode/link/M1VAwx

Validation passsed in case : 

- Account has nominated poool

https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/b1cdb988-791d-416a-9c3f-766a3b1336b4

- Account has direct nomination


https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/2121e12c-0b19-4dcc-a602-8fd9b128b680



- Account has unstake all



https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/3ba4405a-4d8e-4faf-8b4a-2cb232e2469c


- Choose invalid validator from deeplink



https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/523238aa-1bbe-46a0-9c64-6bb50322f844

-  When close popup Validator details, perform from Earning preview screen

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/aG41Dz
Device test: IP 11

- [ ] Show popup Invalid account type in case click Earning positions

   https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/70322422-2638-4f18-909d-42a13bad93a7

- [ ] Add content empty list of Earning preview
