### ISSUE TITLE
Mobile - Improve UX UI for earning feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1560]
**Describe the task**
**Update UI for earning feature**
- [x] Add tag "Mainnet", "Testnet" on Earning options, Earning positions screen
- [x] Show SubWallet pool to top list
- [x] Hide "Direct nomination" of the relaychain if available balance < min stake
- [x] Remove default "testnet" filter on Earning options screen
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/f53894ae-744a-411e-ab4e-ffaf53ebfc35)

- [x] Update UI for Start earning screen
  - Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3360-80540&mode=design&t=QhQxqqNgF6QYluNE-4
    - Remove "Auto-select Pool recommended" icon button
    - Change label from "Select pool" to "Pool"
    - Add "recommended" for SubWallet pool
-  Add the Minimum stake on the Start earning feature after select validator/collator -> Implement to #1562 
    - Actual: After select collator then do not show minimum stake on this screen
    - Expect: Always show min stake  
    ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/198d9ceb-559d-49e0-890a-f124a9e6c810)

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/8ptx9c
Device test: IP 11

@Quangdm-cdm Please update:
- [ ] Add tag "Mainnet", "Testnet" on Earning positions screen
- [ ] Update text recommend -> recommended
