### ISSUE TITLE
Mobile - Improve UX UI for earning feature (Round 2)

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1562]
**Describe the task**
- [x] Do not show token earning options of the Manta network
  - To reproduce the behavior
    - Pre-condition: Turn of Manta Pacific network
    - Go to the Earning position screen
    - Click on MANTA option then observe the screen displayed
  - Actual: Do not navigate to the token's earning options
  - Expect: Show token's earning options screen
  https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/b5bbab08-3e54-400e-8a13-5048c6799b6c

-----------------
**Improve later** -> Move to #1572 
-  Add the Minimum stake on the Start earning feature after select validator/collator

>   - NhungPTT comment: Encounter this issue with Relaychain's Direct nomination, please kindly check
          -> Re-check with Validator (Ternoa)
  - Actual: After select collator then do not show minimum stake on this screen
  - Expect: Always show min stake  
    ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/198d9ceb-559d-49e0-890a-f124a9e6c810)

- Show Direct nomination in case total tranferable of all account > min stake
  Actual: Show Direct nomination when transferable of all account > min stake

    https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/cfe83d37-1050-441e-93ba-57db6b33da04

  Expect: Do not show Direct nomination option

- Navigate to Start earning in case Transferable = 0 (Account have Direct nomination)
  Actual: Show token earning options
  Expect: Navigate to Start earning

**Comment by Sokol142196** [comment]
@ThaoNguyen998 please re-check this issue

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/eA4vBz
Device test: IP 11

Validation passed in case: Do not show token earning options of the Manta network
