### ISSUE TITLE
Mobile - Update tag Recommend for SubWallet's pool

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Mobile#1565]
**Describe the task**
Update UI for earning feature
Link design : https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=20941-310124&mode=design&t=M1bapyrZBftQFlmW-4
- [x]  Update Recommend for SubWallet's pool on Select pool screen

![image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/1573de82-a3a5-4ab5-8ebc-7ab8f9e1fad1)

**Comment by haiyenvu23** [comment]
Version test : 
- IOS : https://www.diawi.com/qrcode/link/hTGjcK
 
- [ ] Don't show icon "Like" 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/e219df16-c7e2-4ef2-b2fa-627c2ca1be30)

- [ ] Error when sorting Lowest total member


https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/108b756c-ac12-456d-b5aa-db9a6053b7cb

**Comment by haiyenvu23** [comment]
Version test : 
- IOS : https://www.diawi.com/qrcode/link/cz5J4k
- Android : https://www.diawi.com/qrcode/link/kDHRcv
Validation passed in case : 
- Update version
- Set default pool = "SubWallet Official 3" (Pool id = 62)


![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/f271849c-4083-4adc-ac1c-a16d5842bb3d)


- Sorting pool
- Filter pool


![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/0284f5fd-b274-4b8c-be9e-f4b72dd5e255)


- Search pool


![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/bb1385d3-9292-4e6f-844c-34d8f9ad0a62)

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/cz5J4k
Device test: IP 11

- [ ] Error page in case select pool not recommended

  https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/cda27498-a247-4a57-9df4-95d793954d01

**Comment by haiyenvu23** [comment]
Version test : 
- IOS : https://www.diawi.com/qrcode/link/KLx7X6
- Android : https://www.diawi.com/qrcode/link/R5qD6K

Validation passed in case : 
-  Select pool not recommended


https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/2f51bde4-aa65-4506-8fb3-89f4592e678f

- Set default pool = "Avail Space" for Avail turing


![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/d9018c53-6384-45dd-8d93-5d0d4efb0b80)



![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/5ed0538d-b4ef-4d00-9b41-df0b92111fa2)

- Sort/Filtet/Search/Select pool


https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/8c45ea53-aac6-4608-a157-208a2525d69b
