### ISSUE TITLE
Bug can not connect to Galxe Dapp from Mission Pool

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-Mobile#1566]
Can not connect to Mission pool url: https://bit.ly/stdot_stellaswap

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/3KfRPs
Device test: IP 11

- [ ] Can't connect dApp with WalletConnect (Re-check with other dapp connect susscessfully)
  
![image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/ce600565-215b-4b0c-ba0b-3a9614b30109)

**Comment by Quangdm-cdm** [comment]
Issue show error in Dapp's wallet connect and can't search wallet: This issue is related to WalletConnect or Dapp

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.48(358)
Device test: IP 11

Validation passed when connect Galxe dApp

https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/EZJsO1fPvipKoZEOebOukjABMhm2oHNcNFc_dHzoSWNHRQ?e=cdarz9
