### ISSUE TITLE
Mobile - Update message when navigate user to the Astar portal to stake

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1570]
**Describe the task**
Update message when navigate user to the Astar portal to stake

**English:**
- Header: Enter Astar portal
- Message: Navigate to Astar portal to view and manage your stake in Astar dApp staking v3
- Button: Cancel / Enter Astar portal

-----------
**Chinese**
- Header: 登录Astar portal
- Message: 请导航到Astar portal以查看并管理你在Astar dApp staking v3里的质押
- Button: 取消 / 登录Astar portal

-----------
**Vietnamese**
- Header: Truy cập Astar portal
- Message: Vui lòng chuyển hướng đến Astar portal để xem và quản lý stake của bạn trong Astar dApp staking v3
- Button: Huỷ / Truy cập Astar portal

**Comment by Sokol142196** [comment]
- [ ] Check bug do not show dApp staking option

**Comment by haiyenvu23** [comment]
Version test : 
- IOS : https://www.diawi.com/qrcode/link/74C7wj
- Android : https://www.diawi.com/qrcode/link/QdnJ4h
Validation passed 



![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/12441799-1f10-4bb6-8e2a-bbcafd6f1ff1)



https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/43f3dd15-a1b6-4ec5-97a2-37ee5a58a1d9
