### ISSUE TITLE
Mobile - Do not show dApp staking

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1575]
**Describe the bug**
Do not show dApp Staking on Earning options

**To reproduce the bug**
Steps: 
1. Go to Earning options screen
2. Observe the displayed screen

Actual: Do not show dApp staking

**Comment by haiyenvu23** [comment]
Version test : 
- IOS : https://www.diawi.com/qrcode/link/74C7wj
- Android : https://www.diawi.com/qrcode/link/QdnJ4h
Validation passed


https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/273415d5-db12-4ecc-9dc6-6acb3c0eabc9
