### ISSUE TITLE
Mobile - Re-check min active stake for Relaychain

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Mobile#1583]
**Describe the task**
Re-check min active stake for Relaychain

**To reproduce the task**
Actual: Show incorrect min active stake in case min validator < min network

https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/ec4ecc71-5037-4c85-8e25-76257b1ea35f

Expect: Min active stake  = Max {Min active stake network, Min active stake validator}

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/r23Sm4
Device test: IP 11
Validation passed.

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/88a0e2c7-39cb-4dcb-a963-f390b7486891
