### ISSUE TITLE
Mobie - Hide popup Introducing Earning feature

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1599]
**Describe the task**
Hide popup reminder Introducing Earning feature

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/f78e9212-8280-4f20-ab2f-4918f5c15292)

**Comment by haiyenvu23** [comment]
Version test : 
- IOS : https://www.diawi.com/qrcode/link/8EBvsB
- Android : https://www.diawi.com/qrcode/link/468yiM

- [ ] In case update version, update from the version with popup Introducing Earning feature to the hidden  popup Introducing Earning feature
**Actual** : Don't show new popup What's new running
**Expect** : Show new popup What's new running

**Comment by haiyenvu23** [comment]
Version test : 
- IOS : https://www.diawi.com/qrcode/link/o3Gs9D
- Android : https://www.diawi.com/qrcode/link/gUDxWr
Validation passed in case : 
- Install version 
- In case update version, update from the version with popup Introducing Earning feature to the hidden popup Introducing Earning feature
-> Show new popup What's new running



https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/957dd68e-4f8d-4a6c-8cb6-9972711b15b2
