### ISSUE TITLE
Mobile - Do not show message error in select many validators on Android

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1601]
**Describe the bug**
Do not show message error in select many validators

**To reproduce the bug**
Precondition: 
- Device: Android

Steps: 
- Check with: Azero, AMPE

Actual: Do not show message error
Expect: Show message error 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/c3c81574-49f9-42b7-aed7-8e78618f215b)

**Comment by Quangdm-cdm** [comment]
@ThaoNguyen998 please move this issue in to UI bug, because in this case, app still show Toast but keyboard is open in Android, make Toast do not show
