### ISSUE TITLE
Mobile - Update web-runner v1.1.58, v1.1.59

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1602]
**Describe the task**
Update web-runner v1.1.58, v1.1.59
Refer: https://github.com/Koniverse/SubWallet-Extension/releases

**Comment by ThaoNguyen998** [comment]
Version test:  http://file.cdmteck.com/s/QBy8maKBEy5QYXn
Validation passed in case: 
- Support staking for Avail Turing (https://github.com/Koniverse/SubWallet-Extension/issues/2963)
- Update chain-list (https://github.com/Koniverse/SubWallet-Extension/issues/2947)
  - Add support for Commune AI blockchain and COMAI token (Mainnet)
  - Add Block Explorer for Enjin Relaychain, Enjin Matrix
  - Add support for DBC network
  - Add support Avail Turing
- Fixed bug Do not show transaction history in case the sender account is null (https://github.com/Koniverse/SubWallet-Extension/issues/2955)
