### ISSUE TITLE
Mobile - Update web-runner v1.1.60

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Mobile#1608]
**Describe the task**
Update web-runner v1.1.60
Refer : https://github.com/Koniverse/SubWallet-Extension/releases/tag/v1.1.60

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/BThPLD
Device test: IP 11

Validation passed in case: Add support Mythos chain
