### ISSUE TITLE
Mobile -  Modal and popup are overlapping in some cases

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Mobile#1618]
**Describe the task**
Modal and popup Backup seed phrase are overlapping

**Expect** : When display popup, modal must be close

https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/82d6073b-44a6-4836-b439-75c46c4a200f

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/WN5iaR
Device test: IP 11
 
- [ ] Modal fullzise and popup are overlapping
