### ISSUE TITLE
Mobile - Update web-runner 1.1.62

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Mobile#1619]
**Describe the task**
Update web-runner 1.1.62
Refer: https://github.com/Koniverse/SubWallet-Extension/releases/tag/v1.1.62

**Comment by ThaoNguyen998** [comment]
Version test: 
IOS: https://www.diawi.com/qrcode/link/nv7Dq2
Android: https://www.diawi.com/qrcode/link/6zrxsd
Device test: IP 11, S20 FE 5G

Validation passed.
