### ISSUE TITLE
Mobile - Add message when perform connect and sign transaction with Moonbeam on Polkadot vault

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Mobile#1639]
**Describe the task**
Block attach account Polkadot vault for network Moonbeam, Moonriver, Moonbase
(Polkadot vault does not support Moonbeam, Moonbase, Moonriver)

**Actual**: Still allow attach account but can not sign transactions cause Polkadot Vault do not support
**Expect**:
- In case attach account: Show message: "Invalid QR code. EVM networks are not supported"
- In case attached account: When perform any transaction then show warning message do not supported :  "This feature is not available for EVM QR signer account. Change to another account type and try again."

**Comment by ThaoNguyen998** [comment]
Refer: https://github.com/Koniverse/SubWallet-Extension/issues/3056

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/8F7jqN
Device test: IP 11
 
- [ ] Unable to scan account Polkadot vault for Substrate
  Actual: Show message Unreadable QR code. Please scan another one

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/0a5f872e-f04b-4299-b587-a5a30bd1400d)

  Expect: Attach account successfully

- [ ] Update message in case scan account Polkadot vault Moonbeam
  Actual: Show message:  Unreadable QR code. Please scan another one
  Expect: Show message: "Invalid QR code. EVM networks are not supported"

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/BHczxS
Devices test: IP 11

- [ ] Error in case transfer NFT
Actual: Show confirmaion
Expect: Show toast

-----
Validation passed in case
- Attach account
  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/5dce282d-ecf6-4605-bce7-a21898a0bb85)

- Send token

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/5cf4d25f-2729-4e3d-9b97-4acdec76aff4)

- Swap

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/14db40de-32d2-45dd-87b8-d9f1d48d6e98)

- Earning
 
 ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/3686a04a-eb7d-4a50-a06d-ac2f21bb9f46)

- Sign request with dApp 

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/70d2a878-3ee1-4237-b643-6d8be7debe8c)

- Dev mode: Allow attach and perform all actions
- Production: Do not attach and not allow to perform any actions

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/Nm9ZLM
Device test: IP 11

- [ ] Error Unstake on evir production 

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/45d4b353-e0aa-4c31-994f-2b0041f1c434)

**Comment by Quangdm-cdm** [comment]
Please re-check some screens: 
 - Unstake
 - Claim Reward
 - Cancel Unstake
 - Withdraw

@ThaoNguyen998

**Comment by ThaoNguyen998** [comment]
Version test: https://i.diawi.com/bKhpVD
Device test: MI 8 Lite

Validation passed. 
- Attach account
- Transfer
- Send NFT
- Earning: Stake, Stake more, Unstake, Cancel unstake, Withdraw(Follow)
- Re-check with dev mode/ product
