### ISSUE TITLE
Mobile - UI bug

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1641]
**Describe the task**

- [x] Autofocus Search field on Export account screen
 Expect: Do not allow auto-focus Search 

- [x] Aligns the left on Select account, Export account
 
   ![image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/9ab5aa99-8fd6-4250-b540-9273eb084167)

  ![image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/90e78b58-72a4-4bec-88ec-6f75f51dfa25)

- [x] Bug UI on the Accounts screen 

   ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/5fc8a6d4-00c0-4f46-aae7-f4cc35f91722) 
 
- [x] Sort the list of disabled pools to the bottom of the list

  ![image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/16f56392-bf2c-4a46-9d2f-5d93321e408a)

**Comment by Quangdm-cdm** [comment]
Pls check some screen: 
 
- [ ] Wallet Connect Authorize (one or more networks)
- [ ] Account Screen
- [ ] Export All Account Screen
- [ ] Restore Batch Json
- [ ] Browser Tab

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/jR4m2E
Device test: S20 FE 5G

- [ ] Unable to scroll

  https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/a2e95c58-5294-45ef-a924-b75e12374332

- Error page in case touch on pool detail

  https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/8df0e277-fab2-40bd-9b01-99714bee1ad6

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/cC6rQ9
Device test: S20 FE 5G

Validation passed in case: 
- Do not allow auto-focus Search on Export multi-account
- Aligns the left on Select account, Export account

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/a966b9e6-1759-4e4a-9fc6-e1637d1116d7)

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/3c82d040-9eb4-49bf-b18d-dc0ac8f33700)

-  Bug UI on the Accounts screen

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/4ed26adc-def3-4f5b-ac04-b90444f3bcef)

-  Sort the list of disabled pools to the bottom of the list

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/89d924b3-5450-4b48-a31f-4b53a93ed93b)
