### ISSUE TITLE
Mobile - Add the "View on explorer" button on the Token details screen

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Mobile#1643]
**Describe the task**
Add the "View on explorer" button on the Token details screen

- [x] Add on the Token details screen in case specific account
- [x] Add on the Token details screen in case All accounts

Link design: https://www.figma.com/design/aEnkI859zkZaIpyzPidYwh/SubWallet-Apps?node-id=11742-356846&t=eg7PB3edkG4pgGnP-4

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/YSqSpn
Device test: IP 11

Validation passed. 
- Install/Upgrade version
- Token detail on current account
- Account details on Token details (All account mode)
- Search token
- Navigate to click View on Explorer
