### ISSUE TITLE
Mobile - Support GRC-20 token

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1644]
**Describe the task**
Support GRC-20 token standard
- Import token
- Show balance
- Transfer

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/uq6F7d
Device test: IP 11

Validation passed
- Import token
- Show balance
- Transfer

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/c07fc42a-d75a-4cbe-9d81-e99a1ee1aece)
