### ISSUE TITLE
Support using camera in Dapps for Android

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-Mobile#1657]
Can't use camera when using Dapp on Android.
Reproduce: Using https://mainnet.biomapper.hmnd.app/

**Comment by ThaoNguyen998** [comment]
Version test: 
https://www.diawi.com/qrcode/link/cbF2xp
https://www.diawi.com/qrcode/link/cbF2xp
Device test: IP 11, MI 8 Lite, S20 FE5G

Validation passed in case 
- Install
- Upgrade version
- Use camera when using dApp

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/3613111d-b8de-488a-821d-166d58c1ac4d)
