### ISSUE TITLE
Mobile - Handle bug error page in case Invalid decoded address length

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1663]
**Describe the bug**

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/dad8770f-fe9f-4da9-a637-b64ff184f5e6)

**Comment by Sokol142196** [comment]
Will follow-up and resoleve in https://github.com/Koniverse/SubWallet-Mobile/issues/1539
