### ISSUE TITLE
Mobile - Swap with HydraDX for Android devices

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1666]
**Describe the task**
Implement Swap feature with HydraDX for Android devices

**Comment by Quangdm-cdm** [comment]
Check WebRunner for all platforms:
 - iOS: 
   - [ ] ios >= 16.4 
   - [ ] iOS < 16.4

 - Android: 
   - [ ] Connect time
   - [ ] Stable
   - [ ] Swap feature

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/wkt9yR
Device test: S20 FE 5G

- [ ] Reset account in case upgrade version (1.1.11 -> 1.1.65)

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/bejKz7
Device test: S20 FE 5G, MI 8 Lite

Validation passed in case: 
 - Install
 - Upgrade version: 1.1.11, 1.1.20, 1.1.24, 1.1.28, 1.1.65
 - Re-check ios
 
----
Discuss: Implement UI in case copy web-runner
  Actual: Flash screen

  https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/74f5c919-a13a-45ff-b2d4-71165e46d414

**Comment by ThaoNguyen998** [comment]
- [ ] Add popup when copy web-runner
  Header: Restart your app
  Message: The latest version of SubWallet is installed on your device. Restart the app to complete the update
  Button: Restart app

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/GLCWKA
Device test: MI 8 Lite, S20 FE 5G

Validation passed.
- Install/ Upgrade version
- Show a popup when upgrading version

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/a3f0a0e0-6019-475c-aed6-777b051fbf1a)

  https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/88df57df-1b4d-4fc3-90f9-bba46b8cb2cd

- Re-check all action
