### ISSUE TITLE
Mobile - Update some message related to earning feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1670]
**Describe the task**
Update some message related to earning feature
**Describe the task**
Update some message related to earning feature
- [x] Message in case Insufficient balance when withdraw, claim reward and unstake
  - Actual: Show message "Your available balance is [Available balance], you need to leave [ED] as minimal balance (existential deposit) and pay network fees. Make sure you have at least [x tokens] in your transferable balance to proceed."
  - Expect: Change to message "You don't have enough [token] (network name) to pay gas fee. Top up your transferable balance and try again"

- [x] Message in case Insufficient balance when stake with Liquid staking (re-check lending staking)
  - Example: stake DOT (Acala) and account have xx ACA (xx > ED) and yy (DOT) then input stake amount: DOT > Total DOT on Acala and Polkadot
  - Actual: Show message "You don't have enough ACA (Acala) to pay gas fee. Lower your amount and try again"
     - Incorrect token
  - Expect: Show message "You can only enter a maximum of xx DOT, which is xx1 DOT (Acala) and xx2 DOT (Polkadot). Lower your amount and try again."

**Comment by Sokol142196** [comment]
Need to deploy #1669 first

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/sedcjJ
Device test: IP 11, S20 FE 

Validation passed.
- Message in case Insufficient balance when withdraw, claim reward and unstake

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/2a024177-4ebe-41be-96a7-bad25d6eae28)

- Message in case Insufficient balance when stake with Liquid staking

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/e8eab789-9b8f-4eef-94f4-39493f202b08)
