### ISSUE TITLE
Mobile - Unable to open link t.me on in app browser

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1674]
**Describe the bug**
Unable to open link t.me on in app browser
Actual: Show error page

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/02eba006-b7c9-468f-8681-da2c6318e2d2)

Expect: Allow open link t.me

-----
Other

- [x] Error in case the device doesn't Telegram app

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/7da1b035-104c-4ab6-bb31-f8b4ab2c53e9)

**Comment by Quangdm-cdm** [comment]
- [ ] Telegram: https://t.me/Playnation_bot/app?startapp=Z4QZc2zjw
- [ ] Twitter: https://x.com/BabyAlt001/status/1798607992537194831
- [ ] Youtube: https://www.youtube.com/@subwalletapp?app=desktop
- [ ] Reddit: https://www.reddit.com/r/CoinBase/comments/18eo3th/withdraw_vara_from_subwallet/
- [ ] Discord: https://discord.gg/8zd53qE6
@ThaoNguyen998

**Comment by Quangdm-cdm** [comment]
This issue will be fixed in Pr #1679
