### ISSUE TITLE
Mobile - Update main tabbar structure

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1680]
**Describe the task**
Update main tabbar structure
- Move Crowdloan to the Settings > General menu
- Move the Mission pool to the main menu
- Allow new category
- Support redirect page: create whitelist dApp to open external app #1674, use appConfirmation to support show extra info for campaign

**Comment by ThaoNguyen998** [comment]
- [ ] Do not show Crowdloan(check with account 5DRewsYzhJqZXU3SRaWy1FSt5iDr875ao91aw5fjrJmDG4Ap)

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/v22uwG
Device test: IP 11

Validation passed.
- Move Crowdloan to the Settings > General menu
  - Show Crowdloan
  - Show banner of Marketing Campaign 

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/b9fecaca-5daf-4fca-a7b8-4631c4e303fb)

- Move the Mission pool to the main menu
- Allow new category

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/43bfa9c4-4627-4ced-8dbc-17a5b8e3a593)

- Support redirect page: create whitelist dApp to open external app https://github.com/Koniverse/SubWallet-Mobile/issues/1674, use appConfirmation to support show extra info for campaign1680

  https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/894123ad-b458-4c03-b81b-efe4ef84345c

- Install
- Upgrade version
