### ISSUE TITLE
Mobile - Add popup warning when perform XCM transfer PAH <--> KAH, PAH <--> Ethereum

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1685]
**Describe the task**
Add popup warning when perform XCM transfer 

- [x] PAH <--> KAH
  - DOT: PAH --> KAH
  - DOT: KAH --> PAH
  - KSM: PAH --> KAH
  - KSM: KAH --> PAH

Popup content: https://www.notion.so/subwallet/SubWallet-Popup-update-Firefox-version-v-message-XCM-DOT-ETH-83fe173b7cea4d6b89bbc17e9116b108?pvs=4#5ef462a56c994cd4bf58656b788c015a

- [x] Snowbridge (PAH <--> Ethereum)
  - WETH: PAH --> Ethereum
  - WETH: Ethereum --> PAH
  - WBTC: PAH --> Ethereum
  - WBTC: Ethereum --> PAH

Popup content: Refer PAH --> KAH with fees:
  - 70$ for channels from PAH --> Ethereum
  - 5 $ for channels from Ethereum --> PAH

Reference: SubWallet extension v1.2.10

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.67(402)

- Add popup warning when perform XCM transfer PAH <--> KAH

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/9fae4816-c3b0-41ef-838b-7ed7c6d310ad)

- Add popup warning when perform XCM transfer Snowbridge (PAH <--> Ethereum)

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/490336f9-0f21-4326-b939-0c6ec8965e15)
