### ISSUE TITLE
Mobile - Update UI for blocked pool

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1686]
**Describe the task**
Update UI for blocked pool

Referance:
- Issue: https://github.com/Koniverse/SubWallet-Extension/issues/3043
- Design: https://www.figma.com/design/lsJoDNOy7hqT41tfiiAk1Z/SubWallet-UI-Base-1.0.1?node-id=7481-1718&t=IV8m1Hq0FLlF0roW-4

**Comment by haiyenvu23** [comment]
Version test : https://www.diawi.com/qrcode/link/BCdiSm

- [ ] Update sorting for pool block

**Comment by haiyenvu23** [comment]
Version test : 
- IOS : https://www.diawi.com/qrcode/link/jmzjZN
- Android : https://www.diawi.com/qrcode/link/bPAhMb
Device : IP 7+, Samsung 
Validation passed in case : 
- Install/Update version
- Gray item, show tooltip, sorting for pool has blocked state


![Image](https://github.com/user-attachments/assets/3854fd58-49bf-4ed4-a8eb-bed49ede1f44)


- Allow open Pool details


![Image](https://github.com/user-attachments/assets/d5d0ef1a-f12e-409c-b9dc-b1c3b4cbc866)


- Add filter Blocked


![Image](https://github.com/user-attachments/assets/9053a97e-3115-4a74-a71d-61dfe66f0e8f)

- Re-check sorting
- Re-check with direct nomination
