### ISSUE TITLE
Mobile - Improve Mission Pool

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1690]
**Describe the bug**
Improve mission pool

- [x] Show blank screen in case search Mission Pool

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/f8ccf11b-4b39-40eb-9d9a-f8f7161c982f)

- [x] Hide banner on mission pool
- [x] Sorting mission pool by status: Live, Upcoming, Archived
- [x] Hide the countdown mission pool in case the tab is already open

**Comment by haiyenvu23** [comment]
Version test : https://www.diawi.com/qrcode/link/NW1kdL

- [ ] Update text color for status on Mission detail screen
Link design : https://www.figma.com/design/lsJoDNOy7hqT41tfiiAk1Z/SubWallet-UI-Base-1.0.1?node-id=4350-900&t=6SDu9TR3lZPE1pfw-4


![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/dbdc7c38-4edc-4b9b-b9bd-b0efc69dd52d)

- [ ] Don't show list crowdloan
Account : 1CDTs83GrViMyHRnLnWon7SSvVwXfDxFmMMu6s1DHwKh2W9



![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/63e5652b-478f-4acd-a64e-f22cd3208c36)

- [ ] Align the mission name to the right


![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/6ac2b4f5-b7f0-4b6c-9e00-c81af839153e)

Expect : 


![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/155931563/03dd169f-e21a-484c-9e07-7c9ef8ee8b23)
