### ISSUE TITLE
Mobile - Support Asset Hub Swap

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1700]
**Describe the task**
Support Asset Hub Swap
- Refer issue: https://github.com/Koniverse/SubWallet-Extension/issues/2512

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/qvLkem
Device test: IP 11 

- [ ] Update logo for asset hub

  ![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/09f38864-bf27-4a28-844c-cced746d80e4)

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.69(409)
Device test: IP 11

Validation passed. 
- Swap DOT (Asset Hub) --> USDC: https://assethub-polkadot.subscan.io/extrinsic/0x63a0ab06d65e14f1dc18f73b778d5a68f99cc554de684a569a4f7662c5249c7f

- Swap DOT (Asset Hub) --> USDt: https://assethub-polkadot.subscan.io/extrinsic/0x5d364e989ddbc33691d283c4cbda77047a536f2f6fa013ec97650c35f74cb4ed

- Swap USDC (Asset Hub) --> DOT: Approve step

- Swap USDt (Asset Hub) --> DOT: https://assethub-polkadot.subscan.io/extrinsic/0xc670431045df01912bffce0b9e0f7f134a991fbef49badf8a6b7893609d45d04

- Re-check all validate
  - Amount = 0

    ![Image](https://github.com/user-attachments/assets/37444f94-8c50-494d-a5bc-3a7f78c33dbb)

  - Insufficient balance

    ![Image](https://github.com/user-attachments/assets/83165b76-02d9-430f-9434-6f13e28eda5a)

    ![Image](https://github.com/user-attachments/assets/9f576c8a-dee2-42a9-b5a7-a175ecd5c2f5)

   - ED of the local token

    ![Image](https://github.com/user-attachments/assets/cc1a9d6d-0683-4a00-b176-4cb742f6d0db)

  - Change swap pair

- Show low liquidity (Price impact < 0.15%)
Check page: https://app.dotacp.mvpworkshop.co/swap

    ![Image](https://github.com/user-attachments/assets/d9e13ae5-0a19-4259-b43b-b0986e3f7463)

- Add pay attention (auto-scroll)

  ![Image](https://github.com/user-attachments/assets/3d620062-29d4-4d26-b56c-89d91fd8a684)

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.69(409)
Device test: IP 11

Validation passed. 
- Swap DOT (Asset Hub) --> USDC: https://assethub-polkadot.subscan.io/extrinsic/0x63a0ab06d65e14f1dc18f73b778d5a68f99cc554de684a569a4f7662c5249c7f

- Swap DOT (Asset Hub) --> USDt: https://assethub-polkadot.subscan.io/extrinsic/0x5d364e989ddbc33691d283c4cbda77047a536f2f6fa013ec97650c35f74cb4ed

- Swap USDC (Asset Hub) --> DOT: Approve step

- Swap USDt (Asset Hub) --> DOT: https://assethub-polkadot.subscan.io/extrinsic/0xc670431045df01912bffce0b9e0f7f134a991fbef49badf8a6b7893609d45d04

- Re-check all validate
  - Amount = 0

    ![Image](https://github.com/user-attachments/assets/37444f94-8c50-494d-a5bc-3a7f78c33dbb)

  - Insufficient balance

    ![Image](https://github.com/user-attachments/assets/83165b76-02d9-430f-9434-6f13e28eda5a)

    ![Image](https://github.com/user-attachments/assets/9f576c8a-dee2-42a9-b5a7-a175ecd5c2f5)

   - ED of the local token

    ![Image](https://github.com/user-attachments/assets/cc1a9d6d-0683-4a00-b176-4cb742f6d0db)

  - Change swap pair

- Show low liquidity (Price impact < 0.15%)
Check page: https://app.dotacp.mvpworkshop.co/swap

    ![Image](https://github.com/user-attachments/assets/d9e13ae5-0a19-4259-b43b-b0986e3f7463)

- Add pay attention (auto-scroll)

  ![Image](https://github.com/user-attachments/assets/3d620062-29d4-4d26-b56c-89d91fd8a684)
