### ISSUE TITLE
Mobile - Update withdraw information for Acala liquid staking

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1720]
**Describe the task**
Update withdraw information for Acala liquid staking

- Refer: https://github.com/Koniverse/SubWallet-Extension/issues/2965

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.70(410)
Device test: IP 11

Validation passed. 

  ![Image](https://github.com/user-attachments/assets/6e0bc781-cdb2-4f63-88cb-fed639ab04e4)
