### ISSUE TITLE
Mobile - Show incorrect withdrawal information of the Bifrost liquid staking when all accounts mode

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1721]
**Describe the task**
Show incorrect withdraw information of the Bifrost liquid staking when all accounts mode
- Check with address: 
  - 5CFh4qpiB5PxsQvPEs6dWAhzgAVLHZa8tZKxeE9XsHBg4n9t
  - 5CAfi6MtzQBcw8iPniwxW8S8YHKEbGbqk8xSm6K9NzxxxLh7

![Image](https://github.com/user-attachments/assets/7d823fb9-6055-484a-a0f9-100995238eff)

**Comment by Sokol142196** [comment]
@ThaoNguyen998 please check this issue again
=> I remember this issue was resolved in webrunner v1.2.22

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.81(433)
Device test: IP 13

Can't reproduce this issue -> Close issue
Check with account: 
- 15tge4dhLYenMCU9SpW5R8NZV1y4W4eJ91bmAEyNA6TCmhsv
- 5Cf9V61adqFFCVimge6pa2vST5QwWjHdDAFNP9tu58VyuaZ7
