### ISSUE TITLE
Update target API level for Android App

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-Mobile#1727]
PlayStore requires updating target API to the 1 year of the latest Android release, before August 31, 2024
![Image](https://github.com/user-attachments/assets/517e05e4-4ea3-47cc-885d-40461033f977)

Please re-check all app and follow up after this update @ThaoNguyen998 and complete this issue before August 10, 2024

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/rnDXxp
Device test: S2 FE 5G

Validation passed.
- Install/ Update version
- Re-check all feature
