### ISSUE TITLE
Improve performance upon showing Marketing Campaign

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-Mobile#1746]

**Comment by ThaoNguyen998** [comment]
Version test: 1.1.76(423)
Device test: IP 11, S20 FR, 8 plus

Validation passed.
Checklist: https://www.notion.so/subwallet/Checklist-Marketing-campaign-ef6f5ce4471e41788f395af222ab5c83?pvs=4
(#3414)
