### ISSUE TITLE
Reduce the size of Mobile app

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-Mobile#1751]
Re-check:
- [x] Remove unused code
- [x] Remove unused package

**Comment by ThaoNguyen998** [comment]
Version test: 
https://www.diawi.com/qrcode/link/xMzSsQ
https://www.diawi.com/qrcode/link/L3Rg5J

Device test: MI 8 Lite, IP 13, IP 8+
Validation passed
- Do not support ios <16.4 (Flow: https://www.figma.com/board/35n8mGbMQp8fAq6pTi9sfj/IOS-16.4?node-id=1-979&t=BQC0s8s2NnU0CN39-4)
- Re-check all action
