### ISSUE TITLE
Mobile - Add warning in case user earn for both nomination pool and direct

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1765]
**Describe the task**
Add warning in case user earn for both nomination pool and direct

- Condition and content: https://www.notion.so/subwallet/Th-ng-b-o-warning-unstake-v-confirmation-cho-c-c-user-ang-c-c-pool-v-direct-c44ca43088b047488fce087cdfa5565e?pvs=4#ebd2f25b59af41c69734746cecd4fb85
_(Do chưa dùng được với Confirmation nên hot fix để làm in-app trước, cải tiến phần confirmation sau)_

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/1dntbX
Device test: S20 FE 

Validation passed
Checklist for issue: https://www.notion.so/subwallet/Checklist-theo-issue-13c9e3215ec24762973dc680aec67198?pvs=4#9762e2dcb8e4453c9f107a0af51c980f
