### ISSUE TITLE
Implement navigation and animation (Phrase 1)

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-Mobile#1767]
Tokens: 

- [x] List -> Detail screen: the experience is not smooth

Derive account: 

- [x] Show password modal with keyboard is not smooth

Accounts screen

- [x] UI bug when touch and slide Account Item

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/jmaZSC
Device test: S20 FE, MI 8 lite

- [ ] Re-check animation on token detail

**Comment by ThaoNguyen998** [comment]
Version test: 
Android: https://www.diawi.com/qrcode/link/7S746T
IOS: https://www.diawi.com/qrcode/link/Up7XFK
Device test: IP 8+, S20 FE

Validation passed.
- Tokens: List -> Detail screen

  https://github.com/user-attachments/assets/f68c5e26-c3b1-475b-9acb-b37460c83f87

- Show password modal with keyboard is not smooth

https://github.com/user-attachments/assets/1563419c-94e2-46cf-a4a1-48c475a8999c

- UI bug when touch and slide Account Item

https://github.com/user-attachments/assets/c533880e-f6a6-46d1-9335-b0a797a98560
