### ISSUE TITLE
Review app performance (v1.1.78)

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Mobile#1775]
Actual: 
- The app is slow when switching tabs between Tokens, NFT, Earning, ...
- When clicking on the Accounts screen, there is a delay before entering.

Expect: Make app smooth when do all above action

**Comment by Quangdm-cdm** [comment]
Please check carefully:
- Features related to Tokens screen
- Accounts screen
- Export All account
- MissionPools list screen
- Swap screen (Just check to see if the information displayed is correct)
@ThaoNguyen998

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/g3m5K4
Device test: IP 8+

- [ ] Re-check Mission pool list

  https://github.com/user-attachments/assets/da54e0af-bb22-43c4-8b29-fa3ad85b2dbf

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/YGmn4p
Device test: IP 8+
Validation passed

- Features related to Tokens screen: check all action
- Accounts screen
- Export All account
- MissionPools list screen
Swap screen (Just check to see if the information displayed is correct)
