### ISSUE TITLE
Add token Million

### ISSUE THREAD

**Issue by caybach** [Koniverse/SubWallet-Mobile#1790]
Mill Million

Asset Hub ID 22,222,070
Hydration ID 1000453

![1 M copy](https://github.com/user-attachments/assets/59a14f13-6dde-446b-9797-90f776a206e7)

**Comment by Sokol142196** [comment]
Hi @caybach, thanks for your request.
This token has been integrated into SubWallet in the latest version (v1.1.80)
![image](https://github.com/user-attachments/assets/56875d6e-8f7f-4dae-817d-fa3d6a4b4e37)
