### ISSUE TITLE
Mobile - Overview of the mobile app update supporting unified accounts

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1814]
**Describe the task**
Overview of the mobile app update supporting unified accounts

- [x] Review
- [x] List of task to implement

BA doc: https://www.notion.so/Master-acccount-d99f9e17956343e9a11cae981a2eadfa?pvs=24
Design: https://www.figma.com/design/aEnkI859zkZaIpyzPidYwh/SubWallet-Apps?node-id=27728-156041&t=nhEjX9BcHmPIvhl8-4

**Comment by Quangdm-cdm** [comment]
- Manage account: 
  - [ ] Get address
  - [ ] Account List
  - [ ] Account detail
  - Create acc: 
    - [ ] Create
    - [ ] Import Json
    - [ ] Import seedphrase
  - [ ] Migrate acc
  - [ ] Derive acc

- [ ]  History
- [ ] Addressbook
- Transaction
  - [ ] SendFund
  - [ ] Swap
  - [ ] Earning
  - [ ] Unstake
  - [ ] CancelUnstake
  - [ ] Withdraw
  - [ ] Claim reward

**Comment by Sokol142196** [comment]
Will resolve in 
- https://github.com/Koniverse/SubWallet-Mobile/issues/1826
- https://github.com/Koniverse/SubWallet-Mobile/issues/1827
- https://github.com/Koniverse/SubWallet-Mobile/issues/1828
