### ISSUE TITLE
Mobile - Implement TAO inapp staking

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1824]
**Describe the task**
Update web-runner to implement TAO inapp staking

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/hqufrG
Device test: IP 13

- [ ] Do not show earning possition
Check with the account: 5FCRFMiDpQNfExcnYYK9rfMjhebSn4YS9we7EGZnm4iXvMdM

- [ ] Do not show list validator when stake

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/W4kbMM
Device test: S20 FE 5G

- [ ] Error when unstake TAO

![Image](https://github.com/user-attachments/assets/910264d5-943e-4df3-8247-ccae064ecd7d)

**Comment by ThaoNguyen998** [comment]
Version test: https://www.diawi.com/qrcode/link/GABUUv
Device test: S20 FE 5G

Validation passed
- Install/Upgrade version
- Show Earning options/ Earning positions
- Stake/ Stake more/ Unstake
  - Main net (Approve steps)
  - Testnet: Successfully
