### ISSUE TITLE
Mobile - Unified account - Implement Manage Account features

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-Mobile#1826]
# **29/10/2024**
- [x] Account List
- [x] Account Detail
 
- [x] Get address
- [x] Create with new seedphrase

- [x] Import Json
- [x] Import seedphrase
- [x] Import private key
 

# **01/11/2024**
- [x] Import by QR code
- [x] Attach QR signer
- [x] Attach watch-only
 
- [x] Export account (Export & Export All)
- [x] Create with existing seedphrase
- [x] Derive account

**Comment by Sokol142196** [comment]
Link feedback: https://www.notion.so/subwallet/Unified-account-Mobile-b768df16eaae45eb95728578dc0d2762?pvs=4

**Comment by Quangdm-cdm** [comment]
- [ ] Improve migrate account

**Comment by ThaoNguyen998** [comment]
Version test: 
![Image](https://github.com/user-attachments/assets/bd612ce6-7fb1-4523-9850-866d65675c25)

-------
Improve round 2: https://github.com/Koniverse/SubWallet-Mobile/issues/1834
