### ISSUE TITLE
Mobile - Unified account - Implement Transaction features

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-Mobile#1827]
- [x] SendFund
 
- [x] Swap
 
- [x] Earning
 
- [x] Withdraw
- [x] Unstake
- [x] Cancel Unstake
- [x] Claim Rewards
- [x] SendNFT

**Comment by Quangdm-cdm** [comment]
Will back to this issue to fix swap feature after fix some major bug

**Comment by haiyenvu23** [comment]
Version test  : v1.1.84(440)b-v11

- Send funds

   - [ ] UI bug
   ![Image](https://github.com/user-attachments/assets/de16ab71-a29b-4c4d-9b79-6ac7c90619f3)

- Send NFT

   - [ ] UI bug
   ![Image](https://github.com/user-attachments/assets/65946a9e-1aeb-46bc-a828-0bfe15c5f808)

- Earning
   - [ ] UI bug on Pool details modal
   ![Image](https://github.com/user-attachments/assets/0b83022d-3334-46a7-8fee-3581deb36cd5)

   - [ ] UI bug on Stake transaction modal
   ![Image](https://github.com/user-attachments/assets/cc3006e6-912c-442f-91ad-78fd51ed7ac1)

- Unstake

   - [ ] Don't auto detect account when unstake
   Acc test : 5CFh4qpiB5PxsQvPEs6dWAhzgAVLHZa8tZKxeE9XsHBg4n9t

   ![Image](https://github.com/user-attachments/assets/1bf7ad1b-bc0a-489d-83a0-68f993a115d5)

   - [ ] UI bug
   ![Image](https://github.com/user-attachments/assets/ca0dedd5-7a3d-4a9a-a2f2-06de7ce3411d)

- Cancel Unstake

   - [ ] UI bug
   ![Image](https://github.com/user-attachments/assets/821b8ca7-ad50-42e8-b006-dab98f2c727d)

- Claim rewards

   - [ ] UI bug
   ![Image](https://github.com/user-attachments/assets/310ec986-f9d8-4d00-bf28-e1a1dd7fc398)

**Comment by haiyenvu23** [comment]
Version test: v1.1.84(440)b-v16

- [ ] UI bug on Earning position detail screen with long account name
   ![Image](https://github.com/user-attachments/assets/17ce3753-869b-43d9-a1ba-4af964bcc98c)

- [ ] Can't navigate to link explorer when click View on explorer on Earning postion detail screen
   ![Image](https://github.com/user-attachments/assets/2d6d5510-e74a-44cd-9528-3eb37858cfe3)

- [ ] Shows network enable popup multiple times even though network has been enabled before on Send fund and Swap features
   Actual : 

   https://github.com/user-attachments/assets/e8eece61-8f69-4295-9b6a-540984ea94f0

   Expect : Don't show when turned on

**Comment by giangtth17** [comment]
Device test: Samsung S20 
Version test: v1.1.84(440)b-v11

- [ ] Validate Address after click button Transfer
Reproduce the step: 
1. At Transfer screen, entering recipient account

Actual: Validation after input, highlight the error field
![image](https://github.com/user-attachments/assets/fbc2bf2a-6895-492b-9ad9-3ae91bed3046)
Expect: Validate after click Transfer

- [ ] Display wrong available balance on the Transfer screen
Reproduce the steps: 
1. Check the available balance of the token at the Token Detail screen
2. Select send token
3. Check show available balance can be send

Actual: show wrong available balance

https://github.com/user-attachments/assets/a291fda0-02dc-48ea-abbe-a97b17308b08


Expect: Displays the correct available balance for deposits

**Comment by Quangdm-cdm** [comment]
Error when perform Swap on ethereum network:Skip this bug because this related to Chainflip version, which will be fixed when update WR and Chainflip version

**Comment by ThaoNguyen998** [comment]
Version test: 
![Image](https://github.com/user-attachments/assets/f09eead5-6022-4c25-be09-8ecc2d949090)
Device test: IP 13

- [ ] Show incorrect available balance in case transfer: 
  Actual: Show incorrect available
  
  ![Image](https://github.com/user-attachments/assets/c3a34424-de94-4775-92ea-776506add94d)
  
  Expect: Allow transfer all
- [ ] Show incorrect balance on Earning options 
  Actual: Show incorect balance
  
  ![Image](https://github.com/user-attachments/assets/d26b5756-5db4-42d5-93dc-699599209065)
  
  Expect: Show balance support earning
- [ ] Unable to turn off Your address popup on token detail
  Actual: Unable to turn off popup
   
  https://github.com/user-attachments/assets/235560f5-de89-4e71-b450-f465483f90c3
  
  Expect: Allow turn off
- [ ] Show incorrect recent on Address book
  Actual: Show TON address
  
  ![Image](https://github.com/user-attachments/assets/6883b6ba-3add-4f74-a453-97bae392e28b)
  
  Expect: Do not show TON address

- [ ] Update UI on export multi account

  ![Image](https://github.com/user-attachments/assets/eb0f4768-f099-4f4c-82c5-f5adbc1af0d6)

**Comment by Quangdm-cdm** [comment]
Show incorrect recent on Address book: It can still be reproduced on the extension, but fixing it will take a lot of time and the problem may not be completely resolved. Suggest raising this error and fixing it on the extension first @ThaoNguyen998

**Comment by giangtth17** [comment]
Device test: Samsung S20 
Version test: v1.1.84(440)b-v11
Device test: IP 13 Version test: 
Validation passed: 
1. Show correct available balance in case transfer
2. Show correct balance on Earning options
3. Allow turn off Your address popup on token detail
4. Update content in case import duplicate account name
5. Popup remind backup account
