### ISSUE TITLE
Mobile - Unified account - Implement other fetures

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-Mobile#1828]
- [x] AddressBook

- [x] Manage website access
- [x] Connect App
 
- [x] Manage WalletConnect connection
- [x] Connect App via WalletConnect
 
- [x] History
- [x] Buy Tokens

**Comment by ThaoNguyen998** [comment]
- [ ] Show incorrect list account on address book
  Actual: Show account not support
  
  https://github.com/user-attachments/assets/23d932ab-fbda-410f-9696-9aec35205161

**Comment by ThaoNguyen998** [comment]
Version test: 
![Image](https://github.com/user-attachments/assets/b249391a-2ffc-451a-8eaa-a7ece2771074)
--> Close issue
Bug related to issue: 
- #1838 
- #1837 
- #1840 
- #1839 
- #1836
