### ISSUE TITLE
Mobile - Unified account - Bug related to keyring

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1833]
**Describe the task**

- [x] Validate account already exists in wallet when: import, attach account
- [x] Change version TON network
- [x] Number account connect in Manage Website Access

**Comment by giangtth17** [comment]
Version: SubWallet v1.1.84(440)b-v11
Device: Samsung S20

- [ ] Do not show button change TON version after change success in solo TON account

https://github.com/user-attachments/assets/88193a7f-e0aa-4012-8b03-a6a02219a378
Expect: Show button Change version

**Comment by giangtth17** [comment]
Still having error:  Do not show button change TON version after change success in solo TON account

**Comment by haiyenvu23** [comment]
Version test : v1.1.84(440)b-v11

- [ ] Add infor box Change version TON network in web view debugger ( reset static content)
- [ ]

**Comment by haiyenvu23** [comment]
Version test : v.1.1.84(440)b-v16
Test on android,ios device

- [ ] Don't display button change TON version after change success in solo TON account on account detail screen ( The problem happens the first time you enter the app)

Actual : 


https://github.com/user-attachments/assets/0f022844-a8bc-4b31-b4c3-3c2c396681f3

**Comment by giangtth17** [comment]
Version test : v1.1.84(440)b-v11

- [ ] Don't display button change TON version after change success in solo TON account on account detail screen  (Note the number of times the problem occurs)

Actual:  

- Happened the first time

https://github.com/user-attachments/assets/bb591108-9c6d-4c5f-bae6-47df9cc4720d

- Happened a second time

https://github.com/user-attachments/assets/1a0642da-4a4d-4135-ab43-6d99d650bd55

- [ ] Press button "back"  twice to return after Change version TON account successfully (The problem occurs in TON solo accounts on the account details screen
Actual: Press button “back” twice to return to the “Select account” screen.
https://github.com/user-attachments/assets/74577cc9-6812-4b11-982c-2bac7177a277
Expect: Just press once

**Comment by giangtth17** [comment]
Version test: SubWallet v1.1.84(440)b-v11
Device test: Samsung S20

**Validation passed:**

- Show message account existed when attach watch only an account, import by QR code
![image](https://github.com/user-attachments/assets/b5d79843-a257-450d-a933-afe1924fae7c)
![image](https://github.com/user-attachments/assets/88547627-6238-4323-b44f-b48aeb1e4efe)

- Show button change TON version after change success (Unified account and solo TON account) 

https://github.com/user-attachments/assets/78cd437c-763f-4dbc-a958-5b1b61a6842b


https://github.com/user-attachments/assets/c8f44a3d-3ace-48de-9eec-f119dda16d84

- Allow close popup get address after change version TON

https://github.com/user-attachments/assets/46e693af-4fd4-416f-b98a-f0f4d007e419

- Add box change version TON
![image](https://github.com/user-attachments/assets/f77a0d0e-2bad-403f-8edd-5706760a4d8e)

- Added infor box Change version TON network in web view debugger ( reset static content)

https://github.com/user-attachments/assets/473a6618-d001-4103-8b1e-7d3267b984e5

- Show infor box in case the wallet only has TON accounts, it is in all account mode

https://github.com/user-attachments/assets/608bccd8-856e-4474-b833-4280d3996d42

- Press the "back" button once to return after Change version TON account successfully
