### ISSUE TITLE
Mobile - Unified account - UI bug

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1834]
**Describe the bug**
### Round 1
- [x] Do not navigate in case click QR

  https://github.com/user-attachments/assets/b45b91e5-3ed5-454b-92ca-1b00dd8c045a

- [x] UI bug in case receive address
  
  ![Image](https://github.com/user-attachments/assets/c51f2d73-98ea-4f43-920e-e4876ea84359)

- [x] Update format for Select address

    ![Image](https://github.com/user-attachments/assets/98b99c88-cb0b-4288-acbe-de4b95e6b76c)

------
### Round 2
- [x] Add ToggleTip in case click on icon Duplicate account name when import account

- [x] Bug UI on input Account name
  Device: Redmi note 11
 
  https://github.com/user-attachments/assets/14a2fa81-560a-4694-b404-f3ff5a9acd01

- [x] Auto-add subfix in case import account export from Ledger recovery

  ![Image](https://github.com/user-attachments/assets/661b9de6-ebfb-4244-9b5b-e4fdc2090b47)

- [x] Hide All account in case have 1 account 

  ![image](https://github.com/user-attachments/assets/a14fb944-f016-44a6-9b3d-1e4bb9ed3deb)

**Comment by giangtth17** [comment]
Device: Samsung S20
Bug: No error message when entering an existing account name
**Reproduce the steps:**
1. Select import by private key 
2. Enter valid private key 
3. Enter an existing account name
4. Click Button Import account 
Actual: No error message when entering an existing account name
Expected:  Show notifications "Account name already in use"
Attach file 

https://github.com/user-attachments/assets/0965dc71-834a-4221-9301-83b87aef0c77

**Comment by giangtth17** [comment]
**Bug: Upload from photos error with invalid image format and invalid QR code**
Device: Android operating system
**Reproduce the steps:**
1. Select import by QR code 
2. Click Button Scan QR code 
3. Click Upload from photos
4. Upload invalid image format or invalid QR code

**Actual:** No error message is displayed
**Expected:** 
+ With invalid image format -> show error message: "Cannot read property "split" of undefined
+ With invalid QR code -> show error messgae: "Invalid QR code"

**Attach file**

https://github.com/user-attachments/assets/4196e553-c893-4efc-a6cd-fd2b58ca4b2f


https://github.com/user-attachments/assets/5405ad1b-bded-466f-beaf-b8e66f7feda3

**Comment by giangtth17** [comment]
Bug: UI screen Keep your seed phrase safe 
Device: SamSung S20 
![image](https://github.com/user-attachments/assets/231da52e-ddd4-4bc3-94ee-9cadf64a89f3)

**Comment by giangtth17** [comment]
**Bug: Missing the COPY button on the Export multi account screen**
Device: SamSung S20
**Reproduce the steps:** 
1. From the Select account screen → Select Export multi account
2. Check UI 

Attach file:

**Comment by Quangdm-cdm** [comment]
Do not navigate in case click QR: Remove this icon button because do not have any action related to this button
ScanQR when Upload from photos error with invalid image format and invalid QR code: This error is reproducible in the official version, so it should be separated into a separate issue and handled later
@giangtth17

**Comment by giangtth17** [comment]
- [ ] Bug UI ToggleTip in case click on icon Duplicate account name when import account
Device: SamSung S20

https://github.com/user-attachments/assets/53bca7f0-f515-4abb-a76e-5ef6e5a84040


- [ ]  Do not automatically remove spaces at the beginning and end of data when entering account name, attach watch-only acocunt

- Device: Samsung S20 - Version: SubWallet v1.1.84(440)b-v11
- Device: iPhone 8 Plus - Version:  ![image](https://github.com/user-attachments/assets/93592932-c614-41c1-b602-c81f47eaaef2)

Reproduce the steps:

1. On attach watch-only acocunt screen
2. Enter the valid private key 
3. Enter the account name containing spaces at the beginning and end of the data
4. Click button attach watch-only acocunt
5. Check UI

Actual: 

https://github.com/user-attachments/assets/5a409305-2909-4800-bda1-4385e18d201f


https://github.com/user-attachments/assets/8aba1aa3-24b3-4f95-84a1-adb409b1c6af


Expected: Automatically remove spaces at the beginning and end of data

**Comment by giangtth17** [comment]
- [ ] Bug UI show wrong placeholder
Actual: 
![image](https://github.com/user-attachments/assets/dab8a53a-3b22-4e18-8475-2f6437bfe8ad)
Expect: 
Show placeholder "Enter account name or address"

- [ ] Bug UI when add new contact

![image](https://github.com/user-attachments/assets/e1df4579-99e2-425d-987a-8bc030a3c8b0)

- [ ] Bug UI when input account name 
Device:  Redmi note 11
Actual: 

- With "create a new account " => sometimes it happens, sometimes it doesn't

https://github.com/user-attachments/assets/1b04ac98-c515-4ee4-b067-12aca4853882

- With " import by QR code", "Connect Keystone device", "Connect a Polkadot Vault account" => always happens
https://github.com/user-attachments/assets/e67d61c3-502f-4f17-809a-976cb42f040e

**Comment by Quangdm-cdm** [comment]
Bug UI when input account name: cannot represent this bug

**Comment by giangtth17** [comment]
Device test: Samsung S20 - Version test: SubWallet v1.1.84(440)b-v11
Device test: iPhone 8 Plus - Version test: SubWallet v1.1.84(440)b-v16
**Validation passed:** 

1. Fixed UI bug in case receive address

![image](https://github.com/user-attachments/assets/78891c02-a07a-4c66-bca4-c26851a0a9e4)

![image](https://github.com/user-attachments/assets/51a58467-439f-464d-84f1-5311d6b4d1d4)


2. Updated format for Select address

![image](https://github.com/user-attachments/assets/968fe19e-d147-4c92-bba5-055638d2f28e)

![image](https://github.com/user-attachments/assets/0d990c3b-e19d-466c-9249-b3282c081f40)


3. Added ToggleTip in case click on icon Duplicate account name when import account

![image](https://github.com/user-attachments/assets/f9cc9563-3835-4391-a500-1bdbfafe9448)

4. Do not automatically add subfix in case import account export from Ledger recovery
5. "All accounts" has been hidden in case there is only 1 account
6. Show error message "Account name already in use" when entering an existing account name
7. Fixed UI bug on Android
8. Fixed UI bug on export account
9. Fixed UI bug on popup Imcompatible seed phrase
10. Fixed UI bug on popup Duplicate account name
11. Automatically remove spaces at the beginning and end of data when import by private key
12. Fixed UI bug when show error message on Attach watch-only account
13. Automatically remove spaces at the beginning and end of data when entering account name, attach watch-only acocunt
14. Added search box account name on derived account tab
15. Updated version and show button change TON version after change success (in parent account on derived account tab)
16. Allows searching accounts by criteria "account name" and "account address"
17. Fixed UI bug when add new contact
18. Show correct tag account when import by private key (using Submit button on the keyboard (depending on the device))
19. Fixed UI bug display available balance
