### ISSUE TITLE
Mobile - Unified account - Bug related to Address book

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1837]
**Describe the bug**
- [x] Show incorrect list account on address book
  Actual: Show account does not support
  
  https://github.com/user-attachments/assets/23d932ab-fbda-410f-9696-9aec35205161
  
  Expect: Filter account by token
- [x] Do not save address TON 
  Actual: Show message Invalid contact address
  
  ![image](https://github.com/user-attachments/assets/5acfebd6-7f9b-4cbc-8593-92880dfe0abc)

  Expect: Allow input address TON

- [x] Show incorrect account when filter
  Actual: Show incorrect tag

  https://github.com/user-attachments/assets/4278020d-f474-4c6a-a611-d994d561ba7b

  Expect: Show correct account

**Comment by giangtth17** [comment]
Version test: SubWallet v1.1.84(440)b-v11
Device test: Samsung S20

**Validation passed:**

- Correctly displayed account list on address book

https://github.com/user-attachments/assets/6ce620b9-f501-4526-a30f-a2dd3563352e


- Allow input address TON when add contact address

https://github.com/user-attachments/assets/d61eea26-7b6f-473c-8a95-1027db2ecbf3

- Show correct account when filter

https://github.com/user-attachments/assets/c35ba94f-ee6d-498c-b4d1-ce7cf0f0ff97
