### ISSUE TITLE
Mobile - Unified account - Bug related to History

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1838]
**Describe the task**

- [x] Do not get history online
  Actual: Do not show transaction history only
  Expect: Get online transaction history on Subscan

- [x] Update UI on History details
  Actual: Do not show address
  Expect: Update UI

  ![Image](https://github.com/user-attachments/assets/5e679ec3-3b99-4408-87da-06761c210eae)

- [x] Update UI on History: Select token -> Select account
  Actual: Select account -> Select token
  Expect:
  
   ![Image](https://github.com/user-attachments/assets/d18fb84b-bd21-429b-8469-0f1c92fb0daf)

**Comment by haiyenvu23** [comment]
Version test: Test on IOS device

![Image](https://github.com/user-attachments/assets/b7df8b94-0186-418f-a99e-e518cf12fbae)

- [ ] Add group account type on Select account modal
   Actual : 
   ![Image](https://github.com/user-attachments/assets/afaab190-8b26-4ca4-bbb5-45dd1adff718)

   Expect : 

   ![Image](https://github.com/user-attachments/assets/21d9deca-d8c3-4025-9e2d-3c58a71841c4)

- [ ] UI bug with long account name 
   Actual
   ![Image](https://github.com/user-attachments/assets/66f55563-3245-4767-8a56-35586ed2a4da)

   Expect : 
   ![Image](https://github.com/user-attachments/assets/12813613-1e11-4e2c-ae39-451c63b8c46b)

**Comment by haiyenvu23** [comment]
Version test : v1.1.84(440)b-v16
Test on android, ios device
Validation passed in case : 
- Get history online
- Update UI on History details
- Add group account type on Select account modal
- Check history on setting screen
- Check history on Home screen

https://github.com/user-attachments/assets/31e2779a-1903-4cba-8d85-d565a090aef5
