### ISSUE TITLE
Mobile - Unified account - Bug related to Connect dApp

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1839]
**Describe the task**

- [x] Show incorrect status when connected dapp
  Actual: Show incorrect status connect

  https://github.com/user-attachments/assets/60ff3e41-0c28-4250-acb4-23567ea51cc3

  Expect: Display correct status
  
- [x] Show incorrect list account on popup connect account
- [x] Hide address on list account connect on dApp details
Actual: Show address

![Image](https://github.com/user-attachments/assets/f76272d5-2e8a-4bce-9dd1-58e3bb8f5444)

Expect: Hide address

- Show incorrect number account connected => Related to issue: https://github.com/Koniverse/SubWallet-Mobile/issues/1857
    Actual : 
   ![Image](https://github.com/user-attachments/assets/43472e18-4684-494c-9fef-63089916cdea)

   Expect : Show correct number

- [x] Re-check padding

   ![Image](https://github.com/user-attachments/assets/904ce30b-5698-4a61-aaa1-0f1e58adbf2b)

   ![Image](https://github.com/user-attachments/assets/91c166c0-31b1-436c-b264-ccbb4954af0d)

----------
**WalletConnect**

- [x] Improve UI on Select account modal
   Actual : Show duplicate unified account ( substrate and ton type)

   ![Image](https://github.com/user-attachments/assets/cb9a015d-86ca-4d16-afca-83312f898ada)

   Expect :Show account name
   

- [x] Improve UI on walletconnect details screen

   Actual : Show duplicate unified account ( substrate and ton type)

   ![Image](https://github.com/user-attachments/assets/4e5bed50-5e35-4a88-95e0-f6199217db6f)

   Expect : Show account name

- [x] Update content 's' for some screen 
   ![Image](https://github.com/user-attachments/assets/1e60b271-a283-4c2f-8860-3a2ec8c039b7)

   ![Image](https://github.com/user-attachments/assets/f70a7603-c565-4b36-a027-a406b0d7cd7e)

   ![Image](https://github.com/user-attachments/assets/c4280010-436a-4404-bc52-82f8db729da5)

- [x] Error show TON address when connect Ethereum and Polkadot network
   Actual 

   ![Image](https://github.com/user-attachments/assets/9f9cd2cc-2c80-4e22-8912-3492c3c22584)

   Expect : Show correct address

**Comment by giangtth17** [comment]
Still getting the error when retest: https://github.com/user-attachments/assets/a474e40e-188a-46fd-a508-218085139ba6

**Comment by Quangdm-cdm** [comment]
This bug is currently still reproducing on the Extension. It needs to be resolved on the extension first, this bug should be created as a separate issue and the current issue should be closed. @ThaoNguyen998

**Comment by giangtth17** [comment]
Version: SubWallet v1.1.84(440)b-v11
Device: Samsung S20
- [ ] Update content 's' for WalletConnect screen
**Reproduce the steps:** 
  1. At WalletConnect, connect to 2 networks:  EVM networks and Subtrate networks
  2. Select 1 account and click button Apply 
  3. Check UI
 Actual: 
 
![image](https://github.com/user-attachments/assets/5c3bd764-cbb7-465c-b34e-e0ecc040a626)

Expect: Omit "s" if <=1 account

**Comment by giangtth17** [comment]
**Version test:** 
1. 
 ![image](https://github.com/user-attachments/assets/ee9c4e89-63a7-4f3a-b071-9ac1bd28774e)

2. SubWallet v1.1.84(440)b-v11
**Device test:** 
1. iPhone 8 Plus
2. Samsung S20

**Validation passed:** 
1. Show correct status when connected dApp

https://github.com/user-attachments/assets/b8993017-26c1-4d34-bfde-3d5146fd86e8

https://github.com/user-attachments/assets/576ba987-5d86-4377-b147-b89aff7e447a


2. Show correct list account on popup Connect account

https://github.com/user-attachments/assets/b2b88270-66ee-4e6f-8697-448192f524f8

https://github.com/user-attachments/assets/141748ef-bf99-4f46-95e8-ec88ab1879da


3. Hide address on list account connect on dApp details

![image](https://github.com/user-attachments/assets/3a6cd0c0-9a2d-42d7-af34-d84b03b2e69b)

![image](https://github.com/user-attachments/assets/3e1aaed5-5589-43ec-a479-d363afb82f0a)

4. Padding

![image](https://github.com/user-attachments/assets/e9f4c2a2-d635-4594-b77a-5f8889097b22)

![image](https://github.com/user-attachments/assets/1cb0d2b7-f85b-4e56-b53c-e3035423ed41)

------------------
WalletConnect 
1. Improved UI on Select account modal => Show account name

![image](https://github.com/user-attachments/assets/e0c672ae-c699-47a7-9355-1ab8a7c505af)

![image](https://github.com/user-attachments/assets/325ce5bc-26da-462d-926c-bf9b2ef1a4b4)

2. Improved UI on walletconnect details screen => Show account name

![image](https://github.com/user-attachments/assets/472068b6-e33a-4f76-b747-b91d63cac547)

![image](https://github.com/user-attachments/assets/0a7dee39-d365-4eb9-a1ea-7c73b4b8fab0)

3. Updated content 's' for some screen
![image](https://github.com/user-attachments/assets/7265b2c4-7422-4ab8-80cd-acc1a9a7b95f)
![image](https://github.com/user-attachments/assets/cf31bd5a-a29c-4614-a887-8d1b9ebe5d64)


![image](https://github.com/user-attachments/assets/de4d5c95-e706-4a0a-be66-7dd4ee5eedd2)
![image](https://github.com/user-attachments/assets/f34ef486-f373-4b52-97ba-abb27255ffd9)


![image](https://github.com/user-attachments/assets/563ea8e2-191e-4e6d-843d-2050ea5b8c7c)
![image](https://github.com/user-attachments/assets/474f0784-8cf4-458d-84ad-713e2d4371aa)

4. Show correct address when connect Ethereum and Polkadot network
![image](https://github.com/user-attachments/assets/6f4d1c0c-854a-4824-afbb-28534e60a03b)
![image](https://github.com/user-attachments/assets/93632be1-6b2e-478c-afcd-64d36158a8f4)
