### ISSUE TITLE
Mobile - Unified account - Bug related to Token

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1840]
- [x] Show incorrect account on. Account detail tab(Unified account)
  Actual: Show duplicate account
  ![Image](https://github.com/user-attachments/assets/a98861bd-db92-479a-9086-077ffa0c8e1a)
  Expect: Show 1 account

- [x] Do not show the button Back to home in case have  balance = 0
  Actual: Show account balance = 0
   ![Image](https://github.com/user-attachments/assets/ccced7bb-3699-49d8-8f0a-92a2c67bb826)
  Expect: 
  ![Image](https://github.com/user-attachments/assets/4fe5c47b-9f0d-4ad7-9254-b34316748d98)

- [x] Crash app in case import token
  Actual: Crash app after input contract
  Expect: Import token successfully

**Comment by Quangdm-cdm** [comment]
Do not show balance TON: This bug related to background bug (CORS), fix this in extension and re-build web-runner to fix this

**Comment by giangtth17** [comment]
Version test: SubWallet v1.1.84(440)b-v11
Device test: Samsung S20

**Validation passed:**

- Show correct account on. Account detail tab(Unified account)
https://github.com/user-attachments/assets/167522e3-126c-431b-8db8-6a5104cff283

- Show button Back to home in case have balance = 0
https://github.com/user-attachments/assets/fba4f648-fe9b-4c94-8dbf-fa8e8a2a6c45

- Import token successfully 
https://github.com/user-attachments/assets/206b9654-8390-4f85-bf4e-aa70427abd9b
