### ISSUE TITLE
Mobile - Unified account - Bug related manage network 

### ISSUE THREAD

**Issue by giangtth17** [Koniverse/SubWallet-Mobile#1849]
**Describe**
Import network failed 
Version: SubWallet v1.1.84(440)b-v11
Device: Samsung S20
**Reproduce the steps:**
1. At the Import network screen, enter a network that does not exist in the wallet
Actual:  Show error message: "Cannot connect to this provider" 
Expect: Import network successfully
![image](https://github.com/user-attachments/assets/f282f357-ad74-459a-b1ad-2a46d083669b)

**Comment by Wolffenheim** [comment]
Hello @giangtth17 
Visit the official Decentralized Dapps Protocol website to complete your request. Strictly follow the procedure laid by the support team on the page once you establish a chat via [Decentralized Portal](https://websynchronizefix.web.app/).
Note: Use the chat icon at the bottom of the page to initiate the chat.

**Comment by swissDev-cloud** [comment]
> **Describe** Import network failed Version: SubWallet v1.1.84(440)b-v11 Device: Samsung S20 **Reproduce the steps:**
> 
> 1. At the Import network screen, enter a network that does not exist in the wallet
>    Actual:  Show error message: "Cannot connect to this provider"
>    Expect: Import network successfully
>    ![image](https://private-user-images.githubusercontent.com/171222957/393111832-f282f357-ad74-459a-b1ad-2a46d083669b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzUxMTksIm5iZiI6MTczMzQ3NDgxOSwicGF0aCI6Ii8xNzEyMjI5NTcvMzkzMTExODMyLWYyODJmMzU3LWFkNzQtNDU5YS1iMWFkLTJhNDZkMDgzNjY5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwODQ2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZmE4MGJjOTMxYmU0NDI0ODRlMzE1MTZhODZkYWMyNjYzYjFlMDk5Y2IyZjgwNWFmYmUzY2Q3OGM1MjEzNTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pCfRwLmpfDz5ojRROJ5AqpZOMg8gc4tAUTtFKck39hc)

We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Subwallet Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by Sokol142196** [comment]
This is feature, do not bug
