### ISSUE TITLE
Mobile - Unified account - Implementing validate for transfer TON feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1858]
**Describe the task**
Implementing validate for transfer TON feature
- [x] Add warning in case transfer to bounceable + inactive address
- [x] Allow transfer same address (sender = receiver)
- [x] Re-check input address for TON and TON testnet on transfer feature
  - Expect:
     - Distinction between mainnet and testnet addresses
     - Synchronize addresses in all steps: Input, Transfer Confirmation, History

**Comment by giangtth17** [comment]
Version: SubWallet v1.1.84(440)b-v11
Device: Samsung S20
- [ ] Add warning in case transfer to bounceable + inactive address
      Actual: Didn't show warning in case transfer to bounceable + inactive address

https://github.com/user-attachments/assets/f6ea482d-5c9c-4fc5-84e5-6b8aab094f58

      Expect: Add warning in case transfer to bounceable + inactive address
![image](https://github.com/user-attachments/assets/8754e596-c643-4a69-80d8-67732b1d9f42)

- [ ] Check to get transaction information in the History screen
       **Reproduce the steps:**
       1. Make valid transfer steps with TON account
       2. Check transaction information in the history screen
       Actual: 
-        At the history screen, the transaction status message is displayed as "Failed"
-        At the Token detail screen of TON shows that the token has been successfully traded
-        Check on the website [https://testnet.tonviewer.com/] that the transaction has been completed successfully
       Expect: Display correct transaction information
       Attach file: 
![image](https://github.com/user-attachments/assets/58781b75-e8b9-4459-9ae3-aa9f3430b1cf)

![image](https://github.com/user-attachments/assets/4bd26c33-0883-4792-8ad8-c5ab4fe04be4)

Uploading Movie001.mp4…

**Comment by giangtth17** [comment]
Version: SubWallet v1.1.84(440)b-v11
Device: Samsung S20
- [ ] Add warning in case transfer to bounceable + inactive address
      **Actual:** Didn't show warning in case transfer to bounceable + inactive address

https://github.com/user-attachments/assets/f6ea482d-5c9c-4fc5-84e5-6b8aab094f58

  **Expect:** Add warning in case transfer to bounceable + inactive address

![image](https://github.com/user-attachments/assets/8754e596-c643-4a69-80d8-67732b1d9f42)

- [ ] Check to get transaction information in the History screen
       **Reproduce the steps:**
       1. Make valid transfer steps with TON account
       2. Check transaction information in the history screen
      **Actual:**
      - At the history screen, the transaction status message is displayed as "Failed"
      - At the Token detail screen of TON shows that the token has been successfully traded
      - Check on the website [https://testnet.tonviewer.com/] that the transaction has been completed successfully
      **Expect:** Display correct transaction information
      **Attach file:** 
![image](https://github.com/user-attachments/assets/58781b75-e8b9-4459-9ae3-aa9f3430b1cf)

![image](https://github.com/user-attachments/assets/4bd26c33-0883-4792-8ad8-c5ab4fe04be4)

**Comment by ThaoNguyen998** [comment]
Version test: 
![Image](https://github.com/user-attachments/assets/f9adbe32-25f2-4322-aabb-3a8c93d4a47b)

- [ ] Hide popup warning transfer for TON networrk
  Actual: Show warning
  
  ![Image](https://github.com/user-attachments/assets/e76d4a12-8ce9-44c6-ad65-29361722bacb)
  
  Expect: Hide warning transfer max(Min amount TON = 0)
- [ ] Update logo account on history detail transfer TON
  Actual: Do not show logo
  
  ![Image](https://github.com/user-attachments/assets/e165ddd9-a609-4176-9b70-db0a0d16b1c3)
  
   Expect: Show logo

- [ ] Do not change version TON mainnet

**Comment by ThaoNguyen998** [comment]
Version test: 
![Image](https://github.com/user-attachments/assets/bf514112-ce75-49b8-b303-221d2f663529)
Device test: IP 13

Validation passed.
