### ISSUE TITLE
Mobile - Update some logic related to token balance

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1861]
**Describe the task**

- [x] Fix bug related feature for TAO
  - Related: https://github.com/Koniverse/SubWallet-Extension/issues/3809, https://github.com/Koniverse/SubWallet-Extension/issues/3788
- [x] Re-check and update foregin asset for Asset Hub (Relate: https://github.com/Koniverse/SubWallet-Extension/issues/3852)
- [x] Fix bug when transfering local token on Bifrost network (https://github.com/Koniverse/SubWallet-Extension/issues/3896)
- [x] Update chainlist: discuss more

**Comment by ThaoNguyen998** [comment]
Version test: ![Image](https://github.com/user-attachments/assets/49742dc3-b2ab-49c0-9eb2-17f457badf5e)
Device test: IP 13, Black shark 4

Validation passed.
- Re-check and update foregin asset for Asset Hub
- Fix bug when transfering local token on Bifrost network
- Fix bug related feature for TAO
