### ISSUE TITLE
Bug invalid character

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Mobile#193]
**Description the bug**
invalid character

**To reproduce the bug**
1. Open the app
2. Perform stake max balance then confirm transaction

Actual: When user enter password then confirm transaction -> Show message "invalid character"

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/4ea4d94a-08fe-42ba-b56a-a27b9eadf0e1)

**Comment by ThaoNguyen998** [comment]
Can't reproduce the bug on the new UI version.
