### ISSUE TITLE
Add the lost internet connection screen

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Mobile#199]
Description

- Add the lost connection screen
- Show status to user know disconnected provider

- With ListScreen: 

- [ ] Add No internet connection screen (no cache data)

- With Transaction screen: 

- [x] Add error message
- [x] show loading when no internet connection

- [x] make show/hide balance not depend on internet

**Comment by ThaoNguyen998** [comment]
@Quangdm-cdm Please update this issue follow by design

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-983-merge-2023-08-24T11-01-20.ipa
Device test: IP 11

- [ ] UI bug

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/3217d4f1-1e27-421b-9d2d-646e9f7055d6)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-984-merge-2023-08-25T10-13-04.ipa
Device test: IP 11

- [ ] Bug overlapped  in case re-connect 
https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-984-merge-2023-08-25T10-13-04.ipa

**Comment by Quangdm-cdm** [comment]
@sokol142 @ThaoNguyen998 this issue is related to background. So we need to improve background first

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-984-merge-2023-08-26T08-33-23.ipa
Devices test: IP 11

- [ ] Still show duplicate toast 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/4c6dd43b-1c3c-4201-8e6a-6eadea262be5)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-223-984-merge-2023-10-12T09-12-59.ipa
Device test: IP 11

@Quangdm-cdm Please re-check this issue

- [ ] Error page when opening the app

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/a691ac7d-6b7b-4e4c-8bcb-13cf3316c4a3)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-224-984-merge-2023-10-13T09-14-17.ipa
Devices test: IP 11

- [ ] Do not turn off Confirmation modal when re-connect internet in case Send NFT, sign with WalletConnect.

**Comment by Quangdm-cdm** [comment]
This issue need to implement from background @S2kael

**Comment by ThaoNguyen998** [comment]
Implement on issue https://github.com/Koniverse/SubWallet-Mobile/issues/1171
-> Close issue
