### ISSUE TITLE
Add the interrupted provider connection warning

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Mobile#216]
**Description the issue**
Add the interrupted provider connection warning
**Expect:** Show popup to update network, includes Content and Actions
- Actions: Cancel, Update
  - Update: open Manage Network screen for user to turn on/off or change network's provider 
  - Cancel: Close Warning
- Link design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=4943-313750&mode=design&t=VTsdmMcIT2Y6S4Sk-4

**Comment by saltict** [comment]
Should implement via transaction balanced view like an extension (https://github.com/Koniverse/SubWallet-Extension/issues/1554)

**Comment by ThaoNguyen998** [comment]
Version test: PR #1158 16/11/2023
Device test: IP 11

- [ ] Do not show popup Update network when rpc disconnected

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/7b1fbc54-a25d-4c86-8734-c005e9874f67

**Comment by Quangdm-cdm** [comment]
Wait for issue #2504 in extension

**Comment by nampc1** [comment]
This won't be necessary if we could handle network connection better
