### ISSUE TITLE
Do not update transferable value on the send asset screen

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Mobile#232]
**Description the bug**
Do not update transferable value on the send asset screen

**To reproduce the bug**
Steps:

1. Open the app then use app
2. Back to Home on the device
3. Lock the device screen
4. After one period (10-15p), re-open the app
5. Go to the send asset screen
6. Observe the transferable value displayed

Actual: Show transferable = 0 although transferable balance > 0

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/a4fd7d6b-42a6-48bf-83f6-47c4bbb394d3)

**Comment by sokol142** [comment]
@ThaoNguyen998 please verify this issue on the new UI version

**Comment by ThaoNguyen998** [comment]
Can't reproduce the bug on the new UI version.
