### ISSUE TITLE
Still show the error message although all data is valid in case of import NFT, import token

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Mobile#233]
**Description the bug**
Still show the error message although all data is valid in case of import NFT, import token

**To reproduce the bug**
Steps:
1. Open the app
2. Perform import NFT/ import tokens consecutively
3. Observe the result import

**Actual**: Show the error message although all data is valid: https://drive.google.com/file/d/1exlZqHQjKqqZ9GAj0Uxa4hhxT9zuwtBj/view?usp=sharing
**Expected:** Imported successfully

**Comment by sokol142** [comment]
@ThaoNguyen998 please verify this issue on the new UI version

**Comment by ThaoNguyen998** [comment]
Can't reproduce the bug on the new UI version.
