### ISSUE TITLE
Can't reload validator when using the app continuous

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#247]
**Description the bug**
Can't reload validator when using the app continuous

**To reproduce the bug**
Pre-condition:

Devices: IP11 / IOS 16
Version test: v0.2.2(104)

Steps: Use the app continuous 

Actual: Can't reload validator

![Image](https://user-images.githubusercontent.com/117999489/202945278-58c198cc-8429-4f7c-b60a-54d27a0608fb.png)

Expect: Display validator list

**Comment by sokol142** [comment]
@ThaoNguyen998 please verify this issue on the new UI version

**Comment by ThaoNguyen998** [comment]
Can't reproduce the bug on the new UI version.
