### ISSUE TITLE
Crash app when rejecting the connection confirm with alert

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Mobile#249]
**Description the bug**
Crash app when rejecting the connection confirm with dotinsights.subwallet.app

**To reproduce the bug**
Steps:
1. Open the app
2. Go to Browser tab
3. Visit to the "dotinsights-preview.subwallet.app"
4. On the connect popup, click on Reject button

**Actual:** Crash app

https://drive.google.com/file/d/1L4sNAPWU7Efm8a8LbvHxi-K6Rd-uHKgg/view?usp=sharing

**Expected:** Rejected successfully

**Comment by ThaoNguyen998** [comment]
Can't  reproduce the issue on the new UI version
