### ISSUE TITLE
Automatically back to the Sign transaction screen

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#273]
Description the bug
Automatic back to the sign transaction screen 

To reproduce the bug
Pre-condition: 

Steps:
Send funds using the QR singer account
Actual: Automatic back to the sign transaction screen 

https://user-images.githubusercontent.com/117999489/205283421-b1938ac0-48e2-4815-a77a-aef923c36552.mp4

**Comment by sokol142** [comment]
@ThaoNguyen998 please verify this issue on the new UI version

**Comment by ThaoNguyen998** [comment]
Can't reproduce the bug on new UI version
