### ISSUE TITLE
Implement Wallet Connect

### ISSUE THREAD

**Issue by lw-cdm** [Koniverse/SubWallet-Mobile#281]
Implement Wallet Connect following what implemented on extension (https://github.com/Koniverse/SubWallet-Extension/issues/1497):
- [x] Implement scanner
- [x] Implement deep-link

Detail: 
- Component:
 
- [x] Dual Logo (change the center icon for WalletConnect confirmation)
- [x] WCAccountSelect
- [x] WCNetworkSelect
- [x] WCNetworkSupported
- [x] WCAvatarGroup
- Screen: 

- [x] ConnectList
- [x] ConnectWalletConnect
- [x] ConnectDetail
- [x] WalletConnectConfirmation
- [x] ScanToConnectWalletConnect

**Comment by Sokol142196** [comment]
Version test:

Please check:

- [ ] Can not connect WalletConnect in case support both Substrate & EVM network
  - Actual: Do not show select account field

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/326f152e-1b29-434a-b7fc-e68f8ded2cf5)


- [ ] Still displaying submitting after connecting failed in case connection exists

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/62cef09f-245f-47b2-b713-041d2176424a)


- [ ] UI bugs

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/796e14a8-66f1-4aa9-9455-39978077ef38)



![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/6a76b01a-d15c-4e85-a25b-85351085cfbf)



![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/b1bcbb14-fc16-4b3b-88c5-bd710a71bde0)



![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/02d8c51c-eccd-4628-9b4f-0fd1b52083ae)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-204-911-merge-2023-07-27T06-13-58.ipa

Please check issues:

- [ ] Do not show the popup confirmation when opening modal (Scan QR code, Receive addess...)
  
  Reproduce the behavior
  Pre-condition: Connect with WallectConnect successfully

  Steps:
  1. Open the app
  2. Go to the Select token to get the address or Scan QR code...
  3. On the dApp, send a request to SubWallet (sign request)
  4. Observe the SubWallet

  Actual: Do not show popup confirmation
   - And: Do not redirect when accessing to Setting menu or browser

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-204-911-merge-2023-07-29T11-10-45.ipa

Please check:

- [ ] Handle case camera access permission
  - Actual: If user select denied permission then can not use app continuing

- [ ] Do not navigate in case modal overlap modal on iOS device
  Steps:
  1. Open the SubWallet app
  2. Connect to dApp via WalletConnect successfully
  3. On the SubWallet app, go to the History detail or QR code screen
  4. On the dApp, perform any transaction 
  5. On the SubWallet app: approve transaction then navigate to the other screen
  
  Actual: Do not navigate

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-205-911-merge-2023-08-07T02-44-00.apk
Device test: MI 8 Lite
 

- [ ] Do not show confirmation when connect wallet

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-205-911-merge-2023-08-08T12-30-11.apk

- [ ] Modal overlapped modal in case connect app to app

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/d546f15a-a714-47ce-9bb6-4f5b5393932a)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-205-911-merge-2023-08-10T09-38-11.ipa
Devices test: IP 11
Validation passed.
