### ISSUE TITLE
Add some dApps to browser's predefined list

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Mobile#282]
**Description the task**
Add some dApps to browser's predefined list:

- [x] Phala App: https://app.phala.network/
- [x] Zenlink: https://dex.zenlink.pro/#/swap
- [x] Avault: https://www.avault.network/vault
- [x] Panorama Swap: https://panoramaswap.app/
- [x] Taiga/Tapio: https://app.taigaprotocol.io/assets

**Comment by sokol142** [comment]
@Quangdm-cdm Please add some new dApp below:
- https://astr.domains/
- https://astr.domains/buy 
- https://tfalpha.xyz/
- https://event.tfalpha.xyz/

**Comment by ThaoNguyen998** [comment]
Version test: v0.2.4(117)
Validation pass.
