### ISSUE TITLE
Monitor app crash status in case search token when continuous use app or the app is running in the background

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#285]
Description the bug
Monitor app crash status in case search token when continuous use app or the app is running in the background

To reproduce the bug
Pre-condition: Use the app continuously or running in the background
Steps:

On the homepage screen, click on the search button

Actual: Crash app

**Comment by sokol142** [comment]
@ThaoNguyen998 please verify this issue on the new UI version

**Comment by ThaoNguyen998** [comment]
Can't reproduce the bug on the new UI version.
