### ISSUE TITLE
Combine QR screens

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Mobile#290]
Combine multi QR screen type into one or use fewer QR screen
- Scan QR screen when click on Scan QR button on header to sign message/sign transaction with QR-signer account
- Scan QR screen when attach QR-signer account
- Scan QR screen when import account by QR code
- Scan QR screen when attach read-only account

Separate action by data type:
- Account address: => User need to choose next action
  - Send Fund or XCM Transfer
  - Attach Read-only Account
- Scan Attach QR-Singer Data
- Scan Import Account By QR
- Scan signature payload

**Comment by Sokol142196** [comment]
Same as https://github.com/Koniverse/SubWallet-Mobile/issues/1162
