### ISSUE TITLE
Not allow back the previous screen when user swipes screen (iOS) or touch the back button (Android)

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Mobile#291]
**Description the bug**
Not allow back the previous screen when user swipes screen (iOS) or touch the back button (Android) in case stand on Submitting screen

- [x] Stake
- [x] Unstake
- [x] Compound: Create task
- [x] Compound: Cancel task
- [x] Send assets (send fund , xcm transfer)
- [x] Send NFT
- [x] Send NFT Result

**Comment by ThaoNguyen998** [comment]
Version test: v0.2.4(118)
Validation passed.
