### ISSUE TITLE
Support 3D NFT display

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Mobile#295]
Support 3D NFT display
_(Check with address: WWXSkTSd5jfK1hm63gmUR4my3DjNM5g9SdxihJokfMQoade36)_

![Image](https://user-images.githubusercontent.com/102292476/207529778-d79101a3-bacd-4d51-8bd0-1f895b5953e0.png)

**Comment by ThaoNguyen998** [comment]
Version test: PR #1114 18:23 01/11/2023
Device test: IP 11, MI 8 Lite

Validation passed.
https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/Ed-eRx0PZH9HiO0Q33hzEyABU7HEz5LQyklz3_gTVtxmwg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0RpcmVjdCJ9fQ&e=oPYI2f
