### ISSUE TITLE
Update logo for new networks on the mobile app

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Mobile#300]
**Description the task**
Update logo for new networks on the mobile app

**Comment by ThaoNguyen998** [comment]
Recheck network: 

- [ ] XX Network
- [ ] Watr Network
- [ ] Watr Network - EVM
- [ ] Subspace Gemini 3a
- [ ] Aleph Zero Smartnet

**Comment by ThaoNguyen998** [comment]
Version test:v0.2.4
Validation passed.
