### ISSUE TITLE
Update some information at the Select network to stake screen

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#301]
**Description the issues**
- [x] Do not show the expected return on the Select network screen to staking in case the expected return = 0 or have no expected return
- [x] Update title for the collator, dApp on the Select network screen to staking

**Comment by sokol142** [comment]
- [ ] Recheck APR on the Parachain (Turing, Bifrost Kusama, Calamari, Amplitude, KILT Peregrine)
- Expect: Show the Chain's APR and not show the Collator's APR

**Comment by ThaoNguyen998** [comment]
Version test: v0.2.4(118)
Validation passed.
