### ISSUE TITLE
Crash app in case of sending assets when using an EVM account that is not connected to any network

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#309]
**Description the bug**
Crash app in case of sending assets when using an EVM account that hasn't connected to any network

**To reproduce the bug**
Pre-condition: 
 EVM Account that hasn't connected to any network 

Steps:

1. Open the SubWallet app
2. Switch to EVM Account above
3. Touch on Send Assets button 

Actual: Crash app

https://user-images.githubusercontent.com/102292476/209269414-eb906256-5cea-43c8-aa85-399b1257cf89.mp4

Expect: 
Option 1: Display message "Please enable the network to continue."
Option 2: Still navigate to the Send Assets screen, placeholder: "Enable network"

**Comment by Quangdm-cdm** [comment]
Fix this bug with Option 1: Display message "Please enable the network to continue."
