### ISSUE TITLE
Do not show tooltips in case selecting a service on android when buy crypto

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#311]
**Description of the bug**
Do not show tooltips in case selecting a service on android when buying crypto

**To reproduce the bug**
Pre-condition: Use device Android

Steps:

1. Open the SubWallet app
2. Touch on the Buy button
3. Select Account/ Select tokens then Select service
4. On the select service page, touch on any service 

Actual: Do not show tooltips 
Expected: Display tooltips

**Comment by sokol142** [comment]
@ThaoNguyen998 please verify this issue on the new UI version

**Comment by ThaoNguyen998** [comment]
Follow-up after update UI Buy token on the new UI version.
