### ISSUE TITLE
Update web-runner for v0.2.5

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Mobile#320]
**Description the task**
Update web-runner for v0.2.5

**Comment by ThaoNguyen998** [comment]
- [ ] Crash app in case of change Token when XCM Transfer
Steps: 
1. Open the Subwallet app
2. Click on the Send button
3. Select Origin chain = Acala
4. Input valid To account
5. Destination chain = Moonbeam, Change Token = ACA
6. Click on the Continue button
7. Input amount = 0 -> click on the Continue
Actual: Crash app
https://share.icloud.com/photos/057Fvpbm-NiBgn2i4hIew_75w
