### ISSUE TITLE
Crash app when access to https://app.cosmize.io/ on IOS device

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Mobile#331]
Version test: v0.2.6 (128)

**Description the bug**
Crash app when access to https://app.cosmize.io/ on IOS device

**To reproduce the bug**
Steps:
1. Open the app
2. Go to the Browser tab
3. Access to https://app.cosmize.io
4. Connect wallet then observe the connection

**Actual**: Crash app

https://user-images.githubusercontent.com/102292476/217995541-e62010b0-8e6d-4d8c-869a-37cd73b7c27e.MP4

**Expected**: Access and connected successfully

**Comment by ThaoNguyen998** [comment]
Version test: v0.2.6(129)
Validation passed
