### ISSUE TITLE
Generated deeplink did not direct to dApp

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-Mobile#332]
**Is your feature request related to a problem? Please describe.**
The generated deeplink directed users to the search page instead of the dApp website.
See example on Android here: https://drive.google.com/file/d/1gRtn8X_fTiCL7oTc3__3YE_KCfnVJbVn/view?usp=share_link

**Describe the solution you'd like**
Please help fix this issue so the deeplink directs users to dApps. Thank you!

**Comment by ThaoNguyen998** [comment]
Follow-up after fix the issue #779
