### ISSUE TITLE
Re-check history list

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Mobile#335]
**Description of the task**
- Re-check the history list

**Actual:** Do not order the history

![Image](https://user-images.githubusercontent.com/102292476/226894602-aa1c5773-63cf-495f-b328-7164a47033ef.png)

**Expected**: order by transaction time

**Comment by sokol142** [comment]
@ThaoNguyen998 please verify this issue on the new UI version

**Comment by ThaoNguyen998** [comment]
Can't reproduce the bug on the new UI version
