### ISSUE TITLE
An error when the user swaps from StellaSwap

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Mobile#336]
**Description of the task**
An error when the user swaps from StellaSwap
- Actual: Loading infinitive

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/c4c3848d-82eb-4092-8790-a946fe8e3742)

**Comment by sokol142** [comment]
@ThaoNguyen998 please verify this issue on the new UI version

**Comment by Sokol142196** [comment]
Do not reproduce this issue on new UI version.
