### ISSUE TITLE
Update Login screen

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Mobile#430]
Apply login screen follow up design.
Need wait #444

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-203-835-merge-2023-07-24T03-52-46.ipa

- [ ] UI bug
![image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/3100da10-c1df-4024-9eca-2a8c42c05422)

- [ ] Show the message "Password is too short" when entering a password with < 6 characters
![image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/27b76a67-a0b1-46ee-aef3-647fe78cf540)

   - Expect: Do not validate min length, only check password matching and require

- [ ] Integrate the Reset Wallet feature

**Comment by nguyenduythuc** [comment]
This issue will be fixed in #444
