### ISSUE TITLE
Save Master Password in Keychain

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#444]
- Check() = check biometrics availability
- Set() = set credential to keychain
- Get() = get credential from keychain
- Reset() = Remove from keychain

User flows:

- Login screen/Unlock modal: 
  + Check() to show authenticate by biometrics
  + Call Get() for authenticate by biometrics
  + Auto migrate with Set() in case user update app and enabled biometrics before

- Turn on/off authenticate by biometrics:
  + Check() => Set() to turn on biometrics
  + Reset() to turn off biometrics

- Change master password:
  + Check() => Set()

`* Keychain use locally, not sync to cloud`

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-203-835-merge-2023-07-24T03-52-46.ipa

Please check the issues:

- [ ] Show the Login screen although do not create a master password yet
- [ ] Can not close the approve confirmation screen if close enter password modal
   - Record bug: https://share.icloud.com/photos/00fojiJrUcTfzzkiqdIcthnPw
   - Steps:
     1. Setting Face ID/ Touch ID is enable
     2. Go to the Send fund screen
     3. Input valid data for the all fields then touch on Submit button
     4. Then touch on Approve button
     5. Close the Enter password popup
     6. Observe the screen displayed

   - Actual: Can not close the confirmation screen
- [ ] Can't open app via Touch ID/Face ID although Face ID/ Touch ID setting is enable
   - Steps:
     1. Setting Face ID/ Touch ID is enable
     2. Close the app
     3. Re-open app
     4. Observe the screen displayed

   - Actual: Do not unlock wallet by Touch ID/ FaceID option
- [ ] Unable to lock wallet manually if Face ID/ Touch ID setting = OFF
   - Expect: Enable Lock wallet manually
- [ ] Unable to setting auto-lock timing if Face ID/ Touch ID setting = OFF
   - Expect: Enable setting auto-lock timing

**Comment by ThaoNguyen998** [comment]
@nguyenduythuc Please re-check this issue

Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-835-merge-2023-08-21T02-00-50.apk
Devices test: Samsung S20 FE 5G

- [ ] Do not input a password in case cancel biometric
Steps: 
1. Go to Send Fund screen
2. On the Confirmation screen, touch Cancel biometric
3. Observe the displayed screen

Actual: 

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/c76deb62-987e-416d-af6e-5590e2253149

**Comment by ThaoNguyen998** [comment]
@nguyenduythuc Please re-check
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-835-merge-2023-08-23T08-09-42.apk
Device test: MI 8 Lite

- [ ] Show message Un-lock failed
Steps:
1. Go to the Security settings screen
2. Enable config Face ID/ Touch ID
3. In input Touch ID screen, touch the Cancel button
4. Close the app and re-open the app
5. Observe the displayed screen

Actual: Show message Unlock false 

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/cbb47d1a-3e67-4c6a-9d07-63ea4e3ccd25

- [ ]Bug in case cancel config allow camera

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-212-835-merge-2023-08-31T09-37-38.ipa

Device test: IP 8 Plus (15.5)

Please check the issues:

- [ ] Bugs when connecting with WalletConnect
  - Actual: Screen keeps turning on/off multiple times: https://drive.google.com/file/d/18x38BZK7c7Dgbj5wYNnwT3aDjZ6N6F5u/view?usp=sharing
- [ ] Update the clickable area of the Forgot password button
