### ISSUE TITLE
No PIN code required after first access in case of version upgrade

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#492]
**Describe the bug**
No PIN code required after first access in case of version upgrade

**To reproduce the behavior**
**Steps:**
1. Installed v0.2.6 (131) and use PIN code to open the app
2. Upgrade version to v1.0.1 (134)
3. After upgrading successfully, open the app
4. Observe the screen displayed 
5. **Do not enter PIN code** and close the app
6. Re-open the app and observe the screen displayed

**Actual:** https://share.icloud.com/photos/060Y1D5b0CyUMSf9q40UPVr3g
- In Step 4: The enter pin code screen and the create master password screen are overlapped
- In Step 6: Do not require enter PIN code to open app.

**Expected:**
- In Step 4: Show the Enter pin code, after un-lock the app then navigate user to the create master password screen
- If the user does not enter the PIN code yet, still require PIN code

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.1(139)
Devices: IP 11
@Quangdm-cdm Please check: The enter pin code screen and the create master password are overlapped

https://user-images.githubusercontent.com/117999489/236418301-8740f935-1b02-4bf9-972e-1ff7e0f177c5.mp4

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.1(141)
Devices test: IP 11, MI 8 Lite
Validation passed.
