### ISSUE TITLE
Do not submit data when the user uses the Enter key on the virtual keyboard instead of the Enter/Apply key on the interface

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#494]
**Describe the bug**
Do not submit data when the user uses the Enter key on the virtual keyboard instead of the Enter/Apply key on the interface

- [x] Send fund
- [x] Apply master password
- [x] Import Secret Phrase
- [x] Import Private key
- [x] Attach ReadOnly
- [x] Send NFT
- [x] Import Network
- [x] Import Token
- [x] Import NFT

**To reproduce the behavior**
_Version test: v1.0.1 (134)_

**Steps:**
1. Go to the create a master password or migrate master password or import account screen, ...
2. After inputting valid data, the user uses the Enter key on the virtual keyboard
3. Observe the screen displayed

**Actual:** Display the submit effect at the Apply button on the interface but do not submit the information (the screen is closed).

https://user-images.githubusercontent.com/130966515/234516027-570b951f-6058-44d5-9d58-4bd2252ef7f0.MP4

**Expected:** Submit data successfully then navigate user to next step

**Comment by ThaoNguyen998** [comment]
- [ ] Send fund
- [ ] Apply master password

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.2(143)
Devices test: IP 11
Re-check issue in case 

- [ ] Import Token
- [ ] Import NFT

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.2(148)
Devices test: IP 11
Validation passed.
