### ISSUE TITLE
Crowdloan data is displayed incorrectly

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#497]
**Describe the bug**
Crowdloan data is incorrect

**To reproduce the behavior**
_Version test: v1.0.1 (134)_
_Check with address: 5HMkyzwXxVtFa4VGid3DuDtuWxZcGqt57wq9WiZPP8YrSt6d_

**Steps:**
1. Go to the Crowdloan tab
2. Observe crowdloan data of the account
3. Apply filter and observe the result

**Actual:** 
- In step 2: The chain of the project is displayed incorrectly
   +_Show the chain of the Project = Kusama (Correct chain = Polkadot)_
- In step 3: Do not show filter results when filtering by chain

![Image](https://user-images.githubusercontent.com/130966515/234532718-a6966dd7-5379-4cff-8c8f-a6a12de5bf1e.png)

**Expect:**
- The chain of the project is displayed correctly
- Show results when filtering by chain
- Add the Chain info for the project and update UI follow-up by design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=3647-406337&t=4loaJfXGyA7QNlVq-4

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.1(140)
Devices test: IP 11 
Validation passed.
