### ISSUE TITLE
Do not automatically reset the password after exiting the form

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#502]
**Description of the bug**
Do not automatically reset the password after exiting the form

Version test: v1.0.1(134)
Re-check all features that require a password

https://user-images.githubusercontent.com/117999489/234759316-540f7ca7-57c2-4c21-b37e-7986cdf567c3.mp4

Expect: Auto reset password

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.1(139)
Devices: IP 11
Please re-check in case the export account

https://user-images.githubusercontent.com/117999489/236599918-52e98f21-241b-42c1-b128-40e4f442834c.mp4

**Comment by S2kael** [comment]
Please test in new version

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.1
Devices test: IP 11
Re-check issue in case change Json file when import account

https://user-images.githubusercontent.com/117999489/236812721-190afbf7-7b58-4d1a-b7fb-69ed1446c072.mp4

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.1(142)
Devices test: IP 11
Validation passed.
