### ISSUE TITLE
Can not perform pool or nominate and other staking actions

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#503]
**Describe the bug**
Can not perform pool or nominate and other staking actions

**To reproduce the behavior**
_Version test: v1.0.1 (134)_

**Steps:**
1. Go to the staking tab
2. Click on + button
3. On the Add to bond screen, Input information to pool or nominate

**Actual:** 
- Can not Change token
- Can not Select pool/ validator
- Can not Close the Keyboard to next step

**_Similar to other actions_**

https://user-images.githubusercontent.com/130966515/234772366-a8a971bf-d745-45da-b14b-83ad31210c9d.mp4

**Expect**: Input information and stake/unstake/withraw... successful

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.1(140)
Device test: IP 11
Validation passed.
