### ISSUE TITLE
Update screen flow when making a transaction

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#504]
**Describe the task**
Update screen flow when making a transaction

**To reproduce the behavior**
User perform any transaction:
- [x] Send fund
- [x] Send NFT
- [x] Staking action: stake, claim, unstake, ...
- [x] Request transaction from dApp

Then observe the screen flow

**Actual:** Input screen -> Confirmation screen -> Enter password screen -> Confirmation screen ->Submitting screen ->  Result
Example with Send NFT: 

https://user-images.githubusercontent.com/130966515/234775533-e78211b8-2faf-4eaa-909f-d226bc54308b.mp4

**Expect**: 
1. Update to flow:
Input screen -> Confirmation screen -> Enter password screen -> Submitting screen -> Result

**Comment by S2kael** [comment]
Fixed in issue #496

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.1(140)
Devices test: IP11
Validation passed.
