### ISSUE TITLE
Transaction history displayed incorrectly

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#507]
**Describe the bug**
Transaction history displayed incorrectly
_Version test: v1.0.1 (134)_

- [x] Type of the Receive transaction and EVM Execute transaction displayed incorrectly

**Steps:**
1. Go to the Send token screen
2. Perform Send token in case of sending in the same wallet
3. After transfered successfully, go to the History sreen
5. Observe the Receive transaction history displayed

**Actual:** Show the type of the transaction = undefined

![Image](https://user-images.githubusercontent.com/130966515/234806714-0c3845ff-2cb0-4303-8389-8d78515d0414.png)

**Expect**: 
   - Receive transaction -> Show correct type = Receive
   - EVM Execute transaction -> Show correct type = Send

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.1(142)
Devices test: IP 11
Validation passed.
