### ISSUE TITLE
UI bugs related to History feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#508]
**Describe the bug**
UI bugs related to History feature

**To reproduce the behavior**
_Version test: v1.0.1 (134)_

- [x] History list is not sorted by date descending
   - Expect:  sorted by date descending
   ![Image](https://user-images.githubusercontent.com/130966515/234809231-b2d29cbe-7a8c-41d6-ab45-bc3eec836ad0.png)

- [x] UI bug on the History list

![Image](https://user-images.githubusercontent.com/130966515/234808660-7e41b9d7-ea69-4c59-b5b2-ba050e4f5b21.png)

- [x] UI bugs when scrolling

https://user-images.githubusercontent.com/130966515/234808815-8a322828-04d5-4f8e-bc09-d63e1ee0732b.mp4

- [x] UI bug when using Android

![Image](https://user-images.githubusercontent.com/117999489/234811275-208f4e6b-e578-4fad-a72b-2c70ff04245d.png)

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.1(137)
- [ ] Do not allow scrolling when the number of records is small

https://user-images.githubusercontent.com/117999489/236185981-b625afa0-f7bb-475a-bf40-7c1885762f2d.mp4

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.1(140).
Device test: IP 11
Validation passed.
