### ISSUE TITLE
Incorrect search results

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#509]
**Describe the bug**
Incorrect search results

**To reproduce the behavior**
_Version test: v1.0.1 (134)_

**Steps:**
1. Open the app
2. Perform search by keyword on the screens below then observe the result
   - Select token
   - History
 
**Actual**: Incorrect search results (have information but can't find it)

https://user-images.githubusercontent.com/130966515/234813487-206cdf31-8c18-4e2c-b5e4-93f8e8fabe20.mp4

https://user-images.githubusercontent.com/130966515/234813510-0b623c4a-1cec-4882-b2d0-a09e1556eb51.mp4

**Expect:**
- Show correct search result
- Re-check other screens

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.1(139)
Devices: IP 11
Please re-check the result when searching in the History screen

![Image](https://user-images.githubusercontent.com/117999489/236596471-6a7fbdba-599a-4f8c-86bc-53f598572650.png)

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.1(141)
Devices test: IP 11
Validation passed.
