### ISSUE TITLE
The list of networks that support import NFT, import token is displayed incorrectly

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#510]
**Describe the bug**
The list of networks that support import NFT is not displayed correctly

**To reproduce the behavior**
_Version test: v1.0.1 (134)
Pre-condition: Turn on all networks that support import NFT, import token_

**Steps:**
1. Go to the import NFT or import token screens
2. Touch on "Network" field then check list networks displayed

**Actual:** Show missing some networks
- Aleph Zero

https://user-images.githubusercontent.com/130966515/234821292-916f9f01-c261-4ebf-bf42-bbb8f07ed761.mp4

**Expect:** Show correctly list network

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.1(140)
Device test: IP 11
Validation passed.
