### ISSUE TITLE
Do not save PIN code setting

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#512]
**Describe the bug**
Do not save PIN code setting

**To reproduce the behavior**
_Version test: v1.0.1 (134)
Device test: iOS (IP 8 Plus)_

**Steps:**
1. Go to the Setting screen
2. Select Security and turn on PIN code setting
3. Create PIN code successfully
4. Setup App-lock = Immediatly
5. Close the app
6. Re-open the app then observe PIN code
7. Go to Security screen then re-check PIN code setting

**Actual:**
- In step 6: Do not require PIN code
- In step 7: PIn code setting = OFF

https://user-images.githubusercontent.com/130966515/234829299-20fbcfba-8997-4ad3-b2c8-faa04604830a.mp4

**Expect**: Save the PIN code setting and require PIN code when opening the app according to the configuration

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.1(139)
Validation passed.
