### ISSUE TITLE
UI bug when switch account in case standing on the Token Detail screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#513]
**Describe the bug**
UI bug when switch account in case standing on the Token Detail screen

**To reproduce the behavior**
**Version test: v1.0.1 (134)**

Steps:
1. Open the app
2. Stand on Substrate account
3. Search on Substrate token and go to the Token detail screen
4. Switch to EVM account then obsserve the screen displayed

**Actual:** UI bugs

![Image](https://user-images.githubusercontent.com/130966515/234833753-f9f7ef8f-1005-4957-ae91-8ea638bb74a0.png)

**Expect**: Back to Homepage screen

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.1(141)
Devices test: IP 11 
Validation passed.
