### ISSUE TITLE
Bugs related NFTs feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#519]
**Describe the bug**
Bugs related NFTs feature

**To reproduce the behavior**
_Version test: v1.0.1 (134)_

- [x] Do not show NFTs of some chains
- Actual: Do not show NFTs of the Moonriver:
   - Check with address: 0xe7a9a370747aab5e7ff1C621a9C337Ca5b8dEbAd

![Image](https://user-images.githubusercontent.com/130966515/235040126-ccb6fcc9-087f-44d5-b8ef-4b501e5d2c31.png)

- [x] Do not import NFT with PSP34 standard
   - Actual: Can not import
      - Import with address contract: 5DVG2kveDY5msL6stCh83QAz6pNN1yLa2D3yfJnLVprYWsAq (Aleph Zero Testnet)
      - Check for account: 5HbcGs2QXVAc6Q6eoTzLYNAJWpN17AkCFRLnWDaHCiGYXvNc

![Image](https://user-images.githubusercontent.com/130966515/235039436-31ddd5d2-dbcb-49c8-a14b-661643b07458.png)

- [x] Can not send NFT of Moonbase Alpha
   - Expect: Send NFT successfully

![Image](https://user-images.githubusercontent.com/130966515/235039406-33efc82a-1676-4059-bd3e-31bf91f02968.png)

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.1(140)
Devices: IP 11
Validatation passed.
