### ISSUE TITLE
UI bugs when configuring network

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#520]
**Describe the bug**
UI bugs when configuring network

**To reproduce the behavior**
_Version test: v1.0.1 (134)_

- [x] Button Cancel on the Add provider screen is disable and can not close the virtual keyboard

![Image](https://user-images.githubusercontent.com/130966515/235042197-acefe74a-3131-45a2-8ea1-8ed87a1b3369.png)

- [x] Navigate is incorrectly when user update network successfully
   - Actual: Still standing on Configure network

![Image](https://user-images.githubusercontent.com/130966515/235042149-adb42f8d-feec-4fb0-bb6e-73b4873048c3.png)

   - Expect: Save configuration and navigate to the list network screen

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.1(142)
Devices test: IP 11
Validation passed.
