### ISSUE TITLE
Do not save the updated network configuration

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#522]
**Describe the bug**
Do not save the updated network configuration

**To reproduce the behavior**
_Version test: v1.0.1 (134)_

**Steps:**
1. Go to Setting > Manage chain screen
2. Click on any network to update configuration
3. Perform: change provider, change explorer URL, change crowdloan URL
4. Click on Save button
5. Back to Manage chain screen then re-open the network above
6. Re-check configuration

**Actual:** 
- In step 4: Show message updated successfully
- In step 6: The changed configuration is reset

https://user-images.githubusercontent.com/130966515/235044342-446ade4b-1e62-405e-86ab-2f2f60e04de3.mp4

**Expect:** Save the updated network configuration

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.1(142)
Devices test: IP 11
Validation passed.
