### ISSUE TITLE
Re-check UI on different devices

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#545]
Description the bug
Version test: v1.0.1(137)
Devices: IP 8 Plus
- [x] UI bug

![Image](https://user-images.githubusercontent.com/117999489/236368931-3dfd793e-73d0-4963-9fc1-3d75f4868086.png)

- [x] UI bug Tab bar

![Image](https://user-images.githubusercontent.com/117999489/236597862-c5ee8990-47b1-4e09-8eff-7e9131e4184c.png)

- [x] UI Header

Version test: v1.0.1(136)
Devieces: Mi 8 Lite

![Image](https://user-images.githubusercontent.com/117999489/236610037-19f6d3be-0ec9-430a-ba2a-0670402c971f.png)

**Comment by Sokol142196** [comment]
Version test: v1.0.2 (145)

Validation passed on the device IP 8 Plus (15.5)

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/9ae547e6-bd47-4183-9dcc-8944a8b0105a)
