### ISSUE TITLE
Add support more languages

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Mobile#56]
# Update language
- [x] Chinese
- [x] Vietnamese: https://docs.google.com/spreadsheets/d/1bBh7zCe6MgBjJlrL7taUjt3CpvxMvBmV/edit?usp=sharing&ouid=114424137518903170251&rtpof=true&sd=true
- Russian / Ukrainian: https://github.com/Koniverse/SubWallet-Mobile/issues/905
- Japanese: https://github.com/Koniverse/SubWallet-Mobile/issues/906
- Portuguese: https://github.com/Koniverse/SubWallet-Mobile/issues/907

**Comment by Sokol142196** [comment]
Waiting issue https://github.com/Koniverse/SubWallet-Extension/issues/1532

**Comment by Sokol142196** [comment]
@nguyenduythuc apply for Vietnamese

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-197-886-merge-2023-07-12T03-03-12.ipa
Devices test: IP 11

 @nguyenduythuc Please re-check this issue
- [ ] Crash app in case you selected Language = Vietnamese


https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/6b6333ac-e657-4005-a8cc-0f07de0de895

**Comment by ThaoNguyen998** [comment]
@nguyenduythuc Please re-check: 
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-198-892-merge-2023-07-13T07-48-12.ipa
Devices test: IP 11

- [ ] Some screens still display English when Vietnamese is applied
After re-open app -> display Vietnamese
https://share.icloud.com/photos/054Y6jBN9TQUtikvpQUNh8UmA
