### ISSUE TITLE
Check case reload web-runner

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Mobile#562]
- Actual: Web runner lost connection after unused in 20m
- Expect: Web runner keep connection in all time
- Steps to reproduce:

  + Add 8 or more account => change password
  + Add a button on Home screen => add action call reload web runner to that button
  + or wait for 20m 
  + Follow up bug: https://github.com/Koniverse/SubWallet-Mobile/issues/539

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.4(173)
Devices test: IP 11, MI 8 Lite
