### ISSUE TITLE
Bugs related to migrate data in case upgrade version

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#573]
**Describe the bugs**
Bugs related to migrate data in case upgrade version

**To reproduce the behavior**
_Device test: IP 8 Plus_

**Steps:**
1. Install v0.2.6 (131)
2. Use app and create data on this version
3. Update version to v1.0.1 (140)
4. Check the data in app after upgrade successfully

**Actual:** Data has not been migrated
- The app's logo does not update if do not create migrate account yet
- Enable only default networks (Polkadot, Kusama, Etherium), other networks that were enabled before will be reset
- Do not show the local history
- The previously entered custom token, entered custom NFT lost
- The list of previously visited websites (Manage website access) is lost 

Expected: Data has been migrated
- The app's logo changed after upgrade successfully
- Enable the default networks (Polkadot, Kusama, Etherium), other networks that were enabled before will be kept
- Kept the local history
- Kept the previously entered custom token and entered custom NFT
- Kept the list of previously visited websites (Manage website access)

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.2(158)
Devices test: IP 11 
Validation passed.
