### ISSUE TITLE
Bugs when perform staking actions

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#585]
**Describe the bug**
Version test: v1.0.1 (142)
UI bugs:
- [x] Do not select pool when the user opens the Pool detail screen 
   - Actual: When closing the Pool details screen, the Select pool screen is also closed
   - Expect: Only close the Pool detail screen, back to the Select pool screen
   
https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/8de43a06-4022-49ad-9a86-de640c563761

- [x] Update clickable area to select pool/validator
   - Actual: When the user click on the button Select pool/validator then does not open the Select pool/validator
   - Expect: Open the Select pool/validator When the user click on the button Select pool/validator

- [x] Show incorrect account list in case change staking type
Steps:
1. Stand on All account mode
2. Click on the + button
3. On the pool tab, select any substrate account
4. Touch on the Nominate tab, go to the select account screen then observe the account list displayed

Actual: Do not show the EVM account
Expect: Displays a list of accounts that support nominate

https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/531f3193-d8ae-421e-b98b-c1f5eeb820c7

---------
Logic bugs
- [x] Not enough min stake error when pooling more
   - Check with the account: 5HbcGs2QXVAc6Q6eoTzLYNAJWpN17AkCFRLnWDaHCiGYXvNc

https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/12530bb6-2fcb-4d9e-b388-914e9a8afff6

- [x] Do not show the validator list of the networks:
   - [x] Turing/ Turing Staging
   - [x] Amplitude/ Amplitude Testnet
   - [x] Kilt/ Pilt
   - [x] Ternoa/ Ternoa AlphaNet
   - [x] Calamari/ Calamari Staging

- [x] Displayed incorrect amount when staking more

https://user-images.githubusercontent.com/117999489/237044189-4e178f2c-c0d0-4b0e-89f2-2a9bf718bd78.mp4

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.1(143)
Devices test:IP 11
Validation passed.
