### ISSUE TITLE
Crash app when click on the "Share" button on the Receive screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#587]
Describe the bug
Crash app when click on "Share" button on the Receive screen

To reproduce the behavior

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/519d7be1-9751-4434-82c6-a8e5df2a1db0

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.1(143)
Devices test: IP 11 
Validation passed.
