### ISSUE TITLE
Show incorrect list account when user receive address

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#595]
**Describe the bug**
Show incorrect list account when user receive address

**To reproduce the behavior**
_Version test: v1.0.1 (142)_
Steps:
1. Stand on All accounts mode
2. Go to the Token detail screen:
    - Case 1: Touch on any token which have token on Substrate chain and EVM chain
    - Case 2: Touch on search token button then select a token
3. Touch on Receive button
4. Observe list account and list token to get address displayed

**Actual:**
- Case 1:
   - In step 4: If token is native token of the Substrate chain (ex: DOT) -> Do not show EVM account, can't get xcDOT (Moonbeam) address

https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/4e9337ee-d139-4df0-8c40-1a8b12263188

- Case 2:
   - In step 4: Still show other token

**Expect:**
- Case 1: Show all account which have token
- Case 2: Only show selected token

Reference: SubWallet extension

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.2(148)
Devices test: IP 11
Validation passed.
