### ISSUE TITLE
Error page occurs when view NFT transaction from the Result screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#607]
**Describe the bug**
Error page occurs when view NFT transaction from the Result screen

**To reproduce the behavior**
_Version test: v1.0.2 (145)_

Steps:
1. Perform Transfer NFT (send with address: 5HbcGs2QXVAc6Q6eoTzLYNAJWpN17AkCFRLnWDaHCiGYXvNc)
   - Case 1: Send NFT of the Bit.Country Alphanet
   - Case 2: Send custom NFT of the Aleph Zero Testnet
      - NFT contract: 5DVG2kveDY5msL6stCh83QAz6pNN1yLa2D3yfJnLVprYWsAq
2. After approved transaction, on the Result screen, click on "View transaction" button
3. Observe the screen displayed

**Actual:** Error page occurs

https://user-images.githubusercontent.com/130966515/238194271-35d97b18-1058-4f49-b65a-3090ccc84307.mp4

**Expect:** View transaction successfully

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.2(150)
Devices test: IP 11 
Validation passed.
