### ISSUE TITLE
Amount displayed incorrectly when auto-converted to Transfer Max

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#609]
**Describe the bug**
Amount displayed incorrectly when converted to Transfer Max when user input Amount: Available - Amount - Fee < ED

To reproduce the behavior
Version test: v1.0.2 (145)

Steps:
1. Go to the Transfer screen
2. Input Amount: Available - Amount - Fee < ED
3. Input valid data for the remain fields
4. Touch on the "Transfer" button
5. Observe the balance displayed after auto-convert Transfer Max

**Actual:** Amount displayed incorrectly
   - Amount is not Max although button Transfer change to Transfer the full account

![Image](https://user-images.githubusercontent.com/130966515/238195807-e7ad693a-b7e6-499c-b960-b5de2d0a3989.png)

**Expect:**
- Amount show Max on the Transfer screen and the Confirmation screen 
_(Refer to the experience on the extension version)_

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.2(150)
Devives test: IP 11 
Validation passed.
