### ISSUE TITLE
Bugs on the Transfer screen when change account, change token

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#610]
**Describe the bug**
Bugs on the Transfer screen when change account, change token

**To reproduce the behavior**
_Version test: v1.0.2 (145)_

**Steps:**
1. Go to the Transfer screen
2. Select account, token, receive account
3. Input invalid Amount to show error message
4. Perform:
   - Change to valid token with Amount
   - Change to valid account with Amount

**Actual:** 
- In case change token: Some token verify Amount is incorrect (ex: change from DOT to NEER, NUUM)
- In case change account: Still show error message although valid data

https://user-images.githubusercontent.com/130966515/238196939-fcf00550-1960-403c-a3e8-545dde200f14.mp4

**Expect:** Validate correctly

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.2(149)
Devices test: IP 11
Validation passed.
