### ISSUE TITLE
Other UI bugs

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#611]
**Describe the bugs:**
_Version test:  v1.0.2 (145)_
- [x] Update QR code for Detail account screen

![Image](https://user-images.githubusercontent.com/117999489/236990391-f2aa3d3f-ee9d-455d-a9ad-796bdc193cbf.png)

- [x] The owner NFT do not show the account name
   - Expect: The owner NFT needs to show by format: Account Name (Account Address)
- [x] Update Welcome back screen

![Image](https://user-images.githubusercontent.com/117999489/236992141-bf3c3568-84ac-4cb4-83f4-2014cbed5728.png)

- [x] Update space of placeholder

![Image](https://user-images.githubusercontent.com/117999489/237040090-84a6ed40-d330-454d-84d3-dc11b2776ccc.png)

- [x] Update UI 

![Image](https://user-images.githubusercontent.com/117999489/236597184-0dfe8851-8537-411b-a4db-12553bc69c46.png)

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.2(151)
Devices test: IP 11, MI 8 Lite
Validation passed.
