### ISSUE TITLE
Re-check the Testnet and Custom tag of the token on the Configure token screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#612]
**Descrie the task**
Re-check and confirm the Testnet and Custom tag of the token on the Configure tokens screen

**Actual:**
- The custom token of the Testnet network => Show "Testnet" tag

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/1d0b08af-e7e6-4b76-a5b4-42e02c3f3ad4)

Reproduce with custom token below:
   - MFG: 0xb161b2da48de283ec22bafbc36e5551c892629a2 (Moonbase)
   - MFR: 0xd7d798825f4e0bc340f6ee38282f2a0455226a87 (Moonbase)
   - AVAT: 0x03065E84748a9e4a1AEbef15AC89da1Cdf18B202 (Astar-EVM)
   - PANX: 5DGHdeY4SXsZ2w8RZrgXXJwHXXe2Qg8LCnUoDTr3tnBnu2BC (Aleph Zero Testnet)

**Expect:**
- Custom token (Testnet or Mainnet)  => Show "Custom" tag

**Comment by saltict** [comment]
This information follow up token's  chain

**Comment by ThaoNguyen998** [comment]
This information updated by chain
