### ISSUE TITLE
Error page occurs when user delete the custom chain, token

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#613]
**Describe the bug**
Error page occurs when user delete the custom chain, token

**To reproduce the behavior**
_Version test:  v1.0.2 (145)_

- [x] The custom chain
- [x] The custom token

**Steps:**
1. Perform add network successfully
2. Go to the Manage chains screen
3. Search the custom chain above then turn on network
4. Go to the Chain detail screen
5. Click on Remove icon and confirm delete chain

**Actual:** After confirmed, the error page occurs

https://user-images.githubusercontent.com/130966515/238200061-4abd8cd6-5b3a-4831-8357-cd36fa85051a.mp4

**Expect:** Deleted chain successfully and visit Manage chain normaly

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.3(161)
Devices test: IP 11
Validation passed.
