### ISSUE TITLE
Some bugs when perform staking actions

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#614]
Describe the bugs
- [x] Do not show unstake data request of the relaychain on the select unstake request screen to cancel unstake request

https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/53f98310-62f3-496d-b8d7-308d41c29d76

- [x] UI bug on the select unstake request screen
![image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/97a5cef7-5149-4f17-81be-c15f85556926)

- [x] Do not reset data when change token

https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/d2f10e70-4b8b-4974-9605-a3bf8357a248

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.2(150)
Devices test: IP 11
Validation passed.
