### ISSUE TITLE
Consider handling in case validate amount

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#621]
Describe the bug
Version test: v1.0.2(143)
Devices test: IP 11

 Show the message Amount is valid in case the input comma

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/6765a39c-14ea-465e-acf9-b7e0092a96a6)

**Comment by saltict** [comment]
Apply validate lazy

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-187-814-merge-2023-06-29T03-20-19.ipa
Validation passed.
