### ISSUE TITLE
Missed the Scan QR screen when approving transactions of QR-signer account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#627]
**Describe the bug**
Missed the Scan QR screen when approving transactions of QR-signer account

**To reproduce the behavior**
_Version test: v1.0.2 (146)_

Steps:
1. Attach QR-signer account successfully
2. Go to the Send fund screen with QR-signer account above
3. Perform transaction
4. Scan QR code on the source device to receive the QR code to approve transaction
5. On the target device, click on Scan QR to publish transaction

**Actual**: Do not show the Scan QR screen.
- If the user does not bring the camera to the QR code scanning location, the transaction will not be approved

https://user-images.githubusercontent.com/130966515/238354553-9687bb8c-ae6a-4ab5-b2a7-2d1d68194d72.mp4

**Expect:**
- [x] Update UI of the Confirm screen
- [x] Navigate user to the Scan QR code when click on "Scan QR" button and approve transaction successfully

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.2(150)
Devices test: IP 11 
Please re-check: 
Navigate to approve screen then navigate to the Scan QR screen

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/842faf12-860b-4f20-aa6a-b47432d6cc1e

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.2(151)
Devices test: IP 11
Validation passed.
