### ISSUE TITLE
Can not approve transaction via QR code

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#628]
**Describe the bug**
Can not approve transaction via QR code

To reproduce the behavior
Version test: v1.0.2 (146)

Pre-condition: 
1. Device 1 (mobile) contains the source account
2. Device 2 contains the QR-signer account of the Device 1

Steps:
1. On the Device 2:
   - Go to the transfer screen then input valid data for the all fields
   - Click on Transfer button
   - Click on Approve button to generate QR code to approve transaction
2. On the Device 1, click on the QR button on the header
3. Observe the screen displayed

**Actual:** Can not scan the QR code to approve transaction

https://user-images.githubusercontent.com/130966515/238361334-d8752b6c-20b4-46ea-ae2c-85c485da0a1b.mp4

**Expect:** Scan QR code successfully and generate the QR code to publish transaction

**Comment by Sokol142196** [comment]
Notes: Do not implement this feature on new UI version

**Comment by ThaoNguyen998** [comment]
@Quangdm-cdm Please update:
If the wallet address is detected, navigate to the "Send Funds" screen and automatically fill in the address into the destination chain.

**Comment by ThaoNguyen998** [comment]
@Quangdm-cdm Please re-check navigate the incorrect screen when scanning QR.

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.6(181)
Devices test: IP 11
@Quangdm-cdm Please re-check this issue: Crashs app when scanning QR address

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/3b0a0e03-0ffa-4dd1-98be-d1d9bfff6dfe

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.6(182)
Devices test: IP 11
Validation passed.
