### ISSUE TITLE
The selected account/network/token icon is not displayed in the Select account/Select network/Select token screens

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#639]
Describe the bug
The selected account/network/token icon is not displayed in the Select account/Select network/Select token screens

https://user-images.githubusercontent.com/130966515/238198009-2623af6a-a958-4a96-a434-55b6187fa72a.mp4
   - Expect: Show the selected icon

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.3(154)
Devices test: IP 11
Validation passed
