### ISSUE TITLE
Still show All accounts option in case the wallet has only 1 account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#642]
**Describe the bug**
Still show All accounts option in case the wallet has **only 1 account**

![image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/919588ee-7e4c-472b-b027-1630b04364bb)

**Expect:** Do not show All Accounts option

Notes: Switch to "All accounts" in cases:
- Create or Import multi-account
- Remove any account 
   - If the wallet have > 2 account -> After removed, Switch to "All accounts"
   - If the wallet has 1 account -> After removed, navigate to the First screen
   - If the wallet have 2 account -> After removed, switch to the remain account

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.2(153)
Devices test: IP 11 
Validation passed.
