### ISSUE TITLE
Update UI the Setting screen follow by design

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#644]
Describe the task
- [x] Update setting screen

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/3e0383e0-f0a2-4d9c-bc9c-ac0432909c86)

- [x] Update icon Setting homepage screen

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/c7bdb7b0-3f5a-4e84-b072-fc09111becfb)

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.2(151)
Devices test: IP 11, MI 8 Lite 
Validation passed.
