### ISSUE TITLE
Can not search by address in case search account

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#655]
**Describe the bug**
Can not search by address in case search account

Steps: 
      1. Go to the search account screen
      2. Input the address valid then observe the displayed screen
      
Actual: Display message No result found

Expect: Display account matches the address entered.

**Comment by Sokol142196** [comment]
Please re-check search token criteria after update new web-runner (v1.0.5)
Expect: allow search by token symbol and network name

**Comment by ThaoNguyen998** [comment]
Version test: v1.03(161)

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.6(164)
Devices test: Ip 11
Validation passed.
