### ISSUE TITLE
Can not get balance in case web-runner disconnect

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#673]
**Describe the bug**
Can not get balance in case web-runner disconnect

**To reproduce the bug**

Steps: 
1. Open the Subwallet app, then perform some feature
2. Exit the app after a long time then re-open the app
3. Perform send or staking

Actual: Can not get balance

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/4eb492c3-cc41-4c28-8ffd-97b9129273b1)

Expect: Display balance

**Comment by saltict** [comment]
Improve with #818

**Comment by Sokol142196** [comment]
Resolve later in #818 => Close this issue
