### ISSUE TITLE
Improve touchable area

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Mobile#683]
Some touchable are too small, like input => please review and increase them.

- [x] Search box
- [x] Transfer 
  - [x]  Amount 
  - [x] Send to account

- [x] Contract address in case Import token
- [x] Import NFT
  - [x] NFT contract address
  - [x] NFT Collection name
- [x] Staking
  - [x] Amount

- [x] Password 
  - [x] Create Password 
  - [x] Change password
  - [x] Current password

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.4(170)
Devices test: IP 11
Validation passed
