### ISSUE TITLE
Bug required master password in case auto-lock less than 15 minutes

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#690]
**Describe the bug**
Bug required master password in case of auto-lock less than 15 minutes

**To reproduce the bug**
Steps: 
1. Open the Subwallet app 
2. Unlock the master password successfully in case the import account or transaction
3. Then perform any import account or transaction features

Actual: Still required master password
Expect: Auto requires a master password after 15 minutes

**Comment by Quangdm-cdm** [comment]
This problem occurs because we have logic to lock the app when it is in background => need more discussion for this logic

**Comment by saltict** [comment]
Resolve this problem in #444
