### ISSUE TITLE
Browser - Browser Home

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#692]
Describe the task
Update Browser screens follow by new UI
- BA Document: https://www.notion.so/subwallet/Feature_Manage-dApp-Connection-934786fdbd3346939f9187443a4c4fca?pvs=4#607ccaecb6ca4940811a76798df4a2c8
- Link design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3647-409422&mode=design&t=AaNoFozFle6QEM6h-4

Data handling

- [x] List dapps
- [x] List History
- [x] List Favorite
- [x] List Recommend
- [x] List Category

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-192-849-merge-2023-07-03T05-17-47.ipa

Please check the issues:

- [ ] Recent list
   - [ ] Improve: Do not save search criteria if the criteria is not dApp
![image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/a35b72c0-ea2b-498a-9fe4-ee69ca8a5f9e)

   - [ ] Still save the recent multi-time although user access to the old recent 
![image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/f5f81483-64f1-4cd3-bd71-0fd8a2b4151c)

      - Expect: Only 1 item
   - [ ] Do not update the dApp into Favorites when user performs adds to favorites/remove favarite from Recent list

- [ ] Re-commend list:
   - [ ] Go back to the first part when clicking the favorite button in the next part
      - Expect: Stay where the user is choosing

- [ ] Favorites list:
   - [ ] Still show dapp on favorite list after remove favorite
   - [ ] Add the empty list when viewing by category

- [ ] Do not view the list fully if scrolling
- [ ] Still dApp has no logo
- [ ] Improve: Auto- focus on search box on the Search screen

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-192-849-merge-2023-07-06T04-11-18.ipa

Please check:

- [ ] Show incorrect dApp on Favorites list in case add favorites from Recent list
   Steps:
   1. Go to the Browser tab
   2. Access to connect.subwallet.app
   3. Access to another dApp
   4. Access to connect.subwallet.app again
   5. On the Recent list, click on "Add favorite" for the connect.subwallet.app 
   6. Go to the Favorites list then observe the connect.subwallet.app 

   Actual: the favorite status of the "connect.subwallet.app" = OFF

- [ ] Show empty page when click on item that is not dApp in the favorites list
   Steps:
   1.

**Comment by saltict** [comment]
Can get banner image from https://dotinsights.subwallet.app/

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.9(197)
Devices test: IP 11
Validation passed.
