### ISSUE TITLE
Re-check get balance function in case send token cross-chain

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#706]
**Describe** the bug
Get incorrect balance to validate when send token cross-chain
- Wating for issue: https://github.com/Koniverse/SubWallet-Extension/issues/1428

![Image](https://user-images.githubusercontent.com/130966515/240463022-0c15a6ca-cac2-4326-abed-ae757dcfc596.png)

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.3(165)
Devices test: IP 11
Validation passed.
