### ISSUE TITLE
Incorrect validate when send token

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#707]
**Describe the bug**
Incorrect validate when send token

**To reproduce the bug**

- [x] Still show recipient invalid in case send token cross-chain (from Substrate -> EVM)
 
Steps:
1. Go to send token screen
2. Select token = DOT
3. Input recipient address = EVM address
4. Select Destination chain = Moonbeam
5. Click on "Transfer" button
6. Observe the screen displayed

**Actual:** show message " "The recipient address must be same type as the current account address"

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/7d2ff1ab-9ae1-4446-9080-8773634a2b3a)

**Expect:** Valid data, allow user send token successfully

- [x] Still show error message although the data is valid in case of change Sender account
Steps:
1. Stand on "All accounts" mode
2. Go to the Send Fund screen
3. Select the Sender account = EVM account
4. Input Recipient account = Substrate account. -> show error message
6. Change to Sender account = Substrate account (Sender & Recipient same type)
7. Observe the screen displayed

**Actual:** Still show error message although the data is valid in case of change Sender account
![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/1c82faa7-c559-4883-946a-66ec77de72b6)

**Expect:** Allow user transfer token successfully

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.3(165)
Devices test: IP 11
Validation passed.
