### ISSUE TITLE
UI bugs on the import token, import NFT screens

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#709]
**Describe the bug**
- [x] Do not close the Select type screen when touching on the type 
- [x] Auto-out focus field when input  1 character

https://user-images.githubusercontent.com/130966515/240473873-524cde9c-4e82-4947-81ac-dab4083f1c7f.MP4

- [x] Still touch 2 times to select network

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.3(165)
Devices test: IP 11
Validation passed.
