### ISSUE TITLE
Add more information for Network Staking information

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#712]
Describe the task

- [x] Nominated
- Substrate account
  - [x] Max nomination
  - [x] Estimated earnings

- Ethereum account

  - [x] Max nomination

- [x] Pools
  - [x] Estimated earnings

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.3(165)
Devices test: IP 11
Validation passed.
