### ISSUE TITLE
Add more dApps to Predefined List

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-Mobile#713]
Hi teams, please add the following dApps to the browser Predefined List. Thank you!
1. Multichain
https://app.multichain.org/#/router
2. Celer cBridge
https://cbridge.celer.network/
3. Wormhole Bridge
https://www.portalbridge.com/
4. Verse DEX
https://verse.bitcoin.com/#

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.4(170)
Devices test: IP 11, MI 8 Lite
Validation passed.
