### ISSUE TITLE
Do not open the Staking detail screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#715]
**Describe the task**
Re-check get staking data on the mobile app

**Actual:** Lost many times to get staking detail -> can not open the staking detail screen

![Image](https://user-images.githubusercontent.com/130966515/240632925-4abe33f6-a64e-4347-963e-84f0781a98de.png)

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.3(165)
Devices test: IP 11
Validation passed.
