### ISSUE TITLE
Show incorrect Transfer Max in case change from send cross-chain to on-chain

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#724]
**Describe the bug**
Show incorrect Transfer Max in case change from send cross-chain to on-chain

![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/fe1e852d-3154-45e2-9a26-e51ddd46bbe9)

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.3(165)
Devices test: IP 11
Validation passed.
