### ISSUE TITLE
Show incorrect APR and Min stake of the some chains

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#733]
Actual: 
   - APR of the AZERO = 4.12%/xx % after inflation
   - Min stake = 0

Expect: 
   - APR = 11.48%/2.44 % after inflation
   - Min stake = 10
 
Please re-check other token

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.4(170)
Devices test: IP 11
Validation passed.
