### ISSUE TITLE
Error page when send token of the custom network

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#734]
**Describe the bug**
Error page when send token of the custom network

**To reproduce the behavior**
Version test: v1.0.3 (164)

Steps:
1. Go to the Browser tab
2. Access to chainlist.org
3. On the chainlist.org page, perform connected to wallet successfully and add any network successfully
4. After imported successfully, go to the send token screen
5. Perform send token of the netwotk above

Actual: Show error page
Follow-up: https://github.com/Koniverse/SubWallet-Extension/issues/1451

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.4(173)
Devices test: IP 11
Validation passed.
