### ISSUE TITLE
Claim reward button (in pooled) is disabled even though the unclaimed value > 0

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#749]
**Describe the bug**
Claim reward button (in pooled) is disabled even though the unclaimed value > 0

**To reproduce the behavior**
_Version test: v1.0.3 (165)_
   - Check with acc: 5HbcGs2QXVAc6Q6eoTzLYNAJWpN17AkCFRLnWDaHCiGYXvNc

**Steps:**
1. Go to the Staking tab
2. Click on DOT (pooled) record
3. Observe the "Unclaim reward" value
4. Click on ... button then choose Claim reward

**Actual:** Claim reward button is disable

https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/c28f7b92-269d-4965-b03b-5f3bfff9cc35

**Expect:** Enable claim reward button when unclaim reward > 0

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.4(170)
Devices test: IP 11
Validation passed.
