### ISSUE TITLE
Do not view account on explorer from NFT detail screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#750]
**Describe the bug**
Do not view account on explorer from NFT detail screen

**To reproduce the behavior**
Steps:
1. Go to the NFT detail screen
2. Click on (i) button to view the account on explorer

**Actual:** Do not find account (404)
   - URL is incorrect: https://kusama.**subscan.io//account**/J7DwBNH9rBXr3v6aAoPSKXJfQeEuqZNhoBXtsrEgWV3H9QQ

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/c39df79a-235b-456e-9ef5-2515f2b72110)

**Expect:** Update URL: https://kusama.subscan.io/account/J7DwBNH9rBXr3v6aAoPSKXJfQeEuqZNhoBXtsrEgWV3H9QQ

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.4(173)
Devices test: IP 11
Validation passed.
