### ISSUE TITLE
Upgrade UI - Buy Token

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#764]
**Describe the task**
Update Buy token screens follow by new UI
- BA Document: https://www.notion.so/subwallet/Feature_Manage-token-6bcf46a6bd004d64b52a0ce964c94929?pvs=4#773309e0c0484233aa5e6c0bfaef9c8e
- Link design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3644-214843&mode=design&t=AaNoFozFle6QEM6h-4

**Comment by ThaoNguyen998** [comment]
@Quangdm-cdm Please check issue: 

- [ ] Crash app in case of touch Setting on the buy token screen


https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/4013042a-86ae-4813-8619-a19f5d391183

- UI bug header 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/bcc96e13-07fc-4823-8d4d-72e8a503ef98)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-192-847-merge-2023-07-03T11-15-27.apk
 

- [ ] Still, allow select service in case do not select the account

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/ad01d694-914d-4bb2-8dc7-4b37fefdd520)

Expect: Disable Select service field

**Comment by Quangdm-cdm** [comment]
@ThaoNguyen998 issue #820 has been resolved in this issue

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-192-847-merge-2023-07-06T03-38-07.apk
Devices test: MI 8 Lite
Validation passed.
