### ISSUE TITLE
Replace all old Select Modal with new Select Modal

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#777]
- [x] Receive:
  + [x] Select Account
  + [x] Select Token
- [x] Buy:
  + [x] Select Account
  + [x] Select Token
- [x] Home:
  + [x] Select Token
  + [x] Customize
- [x] Manage account:
  + [x] Import Account
  + [x] Create Account
  + [x] Attach Account
- [x] Flatlist screen: Filter
- [x] Stake Actions
  + [x] Stake
  + [x] Unstake
  + [x] Withdraw
  + [x] Cancel Unstake
  + [x] Claim reward

- [x] Import network
- [x] Import token
- [x] Import NFT

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-192-864-merge-2023-07-06T10-39-40.ipa
Devices test: IP 11
Validation passed.

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-199-895-merge-2023-07-14T04-19-55.ipa
@Quangdm-cdm Please re-check: 

- [ ] Create a new account

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/8c249bc4-3b8c-4975-b14e-3a76e4516454)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-199-895-merge-2023-07-14T11-09-39.ipa
Devices test: IP 11
Validation passed.
