### ISSUE TITLE
Replace all old form with new form

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#781]
- [x] Import Network & detail
- [x] Import Token & detail
- [x] Import NFT & send NFT
- [x] Add Stake, stake more, unstake
- [x] Send Fund

**Comment by ThaoNguyen998** [comment]
- [ ] Handing effect in case open modal

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/3c526223-0494-42d9-ae62-cc4a94e4252b

**Comment by nguyenduythuc** [comment]
@ThaoNguyen998, pls, move two bugs to other issue, relating to UI bug. Thanks!
