### ISSUE TITLE
Upload Image to read QR code

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#800]

**Comment by ThaoNguyen998** [comment]
- [ ] Do not show a warning  in case select the image invalid when transferring NFT
https://share.icloud.com/photos/07259WNG2iLlYbMU8TR6jNRgQ

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-188-814-merge-2023-06-30T06-55-44.ipa
Validation passed.
