### ISSUE TITLE
UI bug in case search haven't data

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#806]
Version test: v1.0.6(185)

- [x] Search provider
Devices test: IP 11

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/f9168de4-7a1e-4de1-83b1-563bbeda2e5e)

- [x] Search Account, Token
Devices test: Android

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/447136ff-9c63-4734-8cfc-c558cd2babe9)

**Comment by Quangdm-cdm** [comment]
Need more discussion in case use KeyboardAvoidingView in android

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-187-829-merge-2023-06-29T03-02-46.apk
Validation passed.
