### ISSUE TITLE
Update UI - Toast

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#808]
**Describe the task**
Update toast follow by new UI
- Design: https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base-1.0.0?type=design&node-id=494-6828&mode=design&t=kMh6R9owRZpE19qV-4

**Comment by ThaoNguyen998** [comment]
@Quangdm-cdm Please re-check this issue

**Comment by Quangdm-cdm** [comment]
- [ ] Derive Account
- [ ] Manage Address Book
- [ ] Transaction (SendFund, SendNFT, Stake, Unstake, Withdraw, CancelUnstake, ClaimReward)
- [ ] Enable Chain
- [ ] AccountDetail
- [ ] Attach QR-signer account
- [ ] Import QR code
- [ ] TokenGroup & TokenGroupDetail (press SendFund when using watch-only account)
- [ ] NFT Detail (press SendNFT)
- [ ] NFT LIst (delete NFT)
- [ ] Import NFT, Import token, Delete token
- [ ] Add Network, Add Provider

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-198-862-merge-2023-07-13T05-56-32.ipa
Devices test: IP 11
Validation passed.
