### ISSUE TITLE
Update UI - Change master password

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#810]
Describe the task
Update the Change password screens follow new UI
- BA document: https://www.notion.so/subwallet/Feature_Manage-wallet-password-435adb8e83344d888ea5b50438075453?pvs=4#8a8e83dc03064da3a99fdff7bbb75176
- Link figma: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=4739-158984&mode=design&t=4Qr0y195bNgtzdlD-4

**Comment by ThaoNguyen998** [comment]
@Quangdm-cdm Please update the message on the Change Password 2 screen

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/8ea9d2a2-1271-4898-84e9-bd6abe2d67be)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-192-850-merge-2023-07-03T10-31-12.apk
- [ ] Still, submit data in case don't input the current password

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/58d3f6b1-a1f3-4fcd-aa2d-03d68411af17)

Expect: Display message This is field required

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-192-850-merge-2023-07-06T09-59-22.ipa
Devices test: Ip 11
Validation passed.
