### ISSUE TITLE
Reset Wallet feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#812]
Describe the task
Support Reset Wallet feature

- BA Documentation: https://www.notion.so/subwallet/Feature_Manage-wallet-password-435adb8e83344d888ea5b50438075453?pvs=4#68e773d0f79846ab82b8023dbeb83ae8
- Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=7584-167471&mode=design&t=pT2bzzIxuARB4rJu-4

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-197-876-merge-2023-07-10T10-11-31.ipa
Devices test: IP 11

@Quangdm-cdm Please re-check this issue when reset wallet

- [ ] Bug UI 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/b3496be7-9d04-4f4c-b2b9-29bf3f3c98bf)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-197-876-merge-2023-07-12T09-26-31.ipa
Devices test: IP 11
Validation passed.
