### ISSUE TITLE
Still allow add network from dApp in case cannot connect to this provider

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#813]
**Describe the bug**
Still allow add network from dApp in case cannot connect to this provider

To reproduce the behavior
Steps:
1. Go to the Browser tab
2. Visit to chainlist.org
3. Connect wallet successfully
4. Scroll to network, that cannot connect to provider then Click on Add to wallet 
5. Observe the screen displayed

Actual: Still enable button Add network
Expect: Disable button Add network and show connect status of the Add network screens
- Design: https://www.notion.so/subwallet/Confirm-v-b-sung-c-c-m-n-h-nh-tr-n-mobile-app-d8fb4e5c276f4026b66fbeebf6f48d84?pvs=4

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-226-1089-merge-2023-10-21T04-17-23.apk
Device test: Samsung S20 FE 5G

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/d9f0cc6f-8d31-4e5a-950a-5f64fe26219c)
