### ISSUE TITLE
Update new Send Fund UI

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Mobile#815]
- [x] Style
- [x] Scan QR from home
- [x] Step view
- [x] Validate by step view
- [x] Amount input
- [x] Auto calculate amount to $
- [x] In "Amount view", token selector and des-chain selector will limit options to any chain that support the recipient address

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-192-863-merge-2023-07-06T02-12-27.ipa
@lw-cdm Please check: 

- [ ] Bug auto select Send from, Send to
Expect: Do not auto Send from, Send to

- [ ] Do not show a message in case of a change destination chain
Steps: 
1. Go to the transfer screen
2. Select send from, send to = substrate address
3. Change the destination chain = Moonbeam
4. Touch the Next button and then observe the displayed screen
5. Input a valid amount
6. Touch the Transfer button

Actual: 
In step 3: Do not show a message "The recipient address must be EVM type"
In step 4: Navigate to the Amount screen
In Step 6: Show the message error

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/4419f47d-887d-4238-8b0d-518a26efe2d4


Expect: Automatic check data when changing the destination chain

- [ ] Re-check the list token on the Amount screen
- [ ] Don't allow autofocus Send to 
- [ ] Update size logo address Send from
- [ ] Navigate the incorrect screen when performing a transaction successfully
- [ ] Do not validate data in case of scan QR on token screen 

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/86bc9a95-5bf6-4143-96e6-9b7e2a48884c

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-195-863-merge-2023-07-07T11-28-21.ipa
Devices test: IP 11

- [ ] Do not reset button transfer max

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-203-863-merge-2023-07-24T04-11-48.ipa

Please check:

- [ ] Do not show title screen Transfer
- [ ] Can not select account, select token, select network to transfer
  - https://share.icloud.com/photos/096f_94AFkqIdQoBItddvWneg

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-204-863-merge-2023-07-27T09-07-26.ipa

Devive test: IP 8 Plus (15.5)

Please check issues:

- [ ] Still allow user send on chain with same account
  
  **To reproduce the behavior**
  1. Go to the Send fund screen
  2. In Step 1, input the sender same as receiver and input valid data for remain fields
  3. Click Next to next step
  4. In step 2, change Destination chain: Destination chain = Origin chain
  5. Input valid amount then click Transfer button

  **Actual:** Still allow send fund

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/fa948d3f-be1f-47c0-9749-a883d27ebc50)


  **Expect:** Show message "The recipient address can not be the same as the sender address"

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-205-863-merge-2023-08-09T09-04-04.ipa
Devices test: IP 11
Validation passed.
