### ISSUE TITLE
Crash problems on android (implement crashlytic in development build)

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Mobile#817]
The App crash on android many times. @nguyenduythuc please mention your solution for this.

**Comment by nguyenduythuc** [comment]
- Recently, in Play Console, the App on android have highly crashing rates. We can add Bugsnag and build for development team to know what's happening
https://www.bugsnag.com/pricing/

**Comment by nguyenduythuc** [comment]
Solved crash app issue on Android, we don't need crashlytic anymore
