### ISSUE TITLE
Recheck animation seem make user feel app slowly on android

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Mobile#820]
Some animations make users feel the app slowly:
- Tab on "send fund" from the home screen
- Another screen use above animation

**Comment by ThaoNguyen998** [comment]
@Quangdm-cdm Please re-check this issue

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-192-847-merge-2023-07-06T03-38-07.apk
Devices test: MI 8 Lite
Validation passed.
