### ISSUE TITLE
Browser - Browser Home - List

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#821]
- [x] Search:
Figma link: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3911-208849&mode=design&t=RVgBHyCXtpVBBduk-4

- [x] History:
Figma link: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=4956-322959&mode=design&t=RVgBHyCXtpVBBduk-4

- [x] Favorite:
Figma link: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3911-208849&mode=design&t=RVgBHyCXtpVBBduk-4

- [x] Recommend:
Figma link: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3911-209392&mode=design&t=RVgBHyCXtpVBBduk-4

Conponents:

- [x] List item @lw-cdm 
- [x] Button Tab with number @nguyenduythuc 
- [x] Search bar @lw-cdm

**Comment by saltict** [comment]
Please check this case
- [ ] Emtpy list

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.9(197)
Devices test: IP 11
Validation passed.
