### ISSUE TITLE
Browser - Webview

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#822]
- [x] Detail
Figma link: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3853-231141&mode=design&t=RVgBHyCXtpVBBduk-4

- [x] More option
Figma link: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3853-231216&mode=design&t=RVgBHyCXtpVBBduk-4
- [x] Tab list
Figma link: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3854-233316&mode=design&t=RVgBHyCXtpVBBduk-4

**Comment by lw-cdm** [comment]
- [ ] dapp tag color map 
- [ ] Browser item
- [ ] Browser search
  - [ ] empty list
- [ ] Browser tab
  - [ ] header
  - [ ] footer
  - [ ] More option
- [ ] Browser tab manager
  - [ ] Item
  - [ ] header
  - [ ] footer
    - [ ] disable condition
  - [ ] empty list

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-192-849-merge-2023-07-03T05-17-47.ipa

Please check the issues:

- [ ] Show incorrect connection status after connecting dApp successfully
   Steps:
   1. Go to the Browser tab
   2. Visit to "alephzero.artzero.io"
   3. Connect dApp successfully
   4. Observe the connection status 
   
   Actual: Connection status = Disconnected
   Expect: Connection status = Connected
https://share.icloud.com/photos/0bc3jULnVM0m7IfjYx964TACw

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.9(197)
Devices test: IP 11
Validation passed
