### ISSUE TITLE
Browser - DApp Confirmation

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#823]
- [x] Update metadata (Fix UI follow new design)
- [x] Connect wallet confirmation
- [x] Connect wallet no account (Fix UI follow new design)
- [x] Cannot connect
- [x] Sign message
- [x] Transaction request detail
- [x] Fix ConfirmationHeader

**Comment by nguyenduythuc** [comment]
Reffer issue: https://github.com/Koniverse/SubWallet-Mobile/issues/802

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-189-838-merge-2023-07-01T10-21-09.ipa

- [ ] Hide the scroll bar on the Transaction detail

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/e425ad8b-f3c1-4a8f-b2f6-13c8aeb622ea)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-192-838-merge-2023-07-06T02-58-14.ipa
Devices test: IP 11
Validation passed.
