### ISSUE TITLE
Browser - Website access detail

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#824]
- [x] Detail
Figma link: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3916-165216&mode=design&t=RVgBHyCXtpVBBduk-4

- [x] More action
Figma link: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3916-165217&mode=design&t=RVgBHyCXtpVBBduk-4

**Comment by ThaoNguyen998** [comment]
- [ ] Incorrect order action on Website access config screen
- [ ] Title More options -> Website access config
- [ ] Field account selected -> account connected
- [ ] Do not disable the account in case block this site

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/69bd1baf-3ebe-49d0-8663-ef5b1f8434ca)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-189-837-merge-2023-07-01T08-01-20.ipa
Validation passed.
