### ISSUE TITLE
Browser - Connection

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#826]
- [x] Connection
Figma link: 
https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3916-165641&mode=design&t=RVgBHyCXtpVBBduk-4
https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3916-166106&mode=design&t=RVgBHyCXtpVBBduk-4
https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3916-166442&mode=design&t=RVgBHyCXtpVBBduk-4

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-192-849-merge-2023-07-03T05-17-47.ipa

Please check issues:
- [ ] UI bug on the Connect dApp confirmation
![image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/be548079-bf05-4700-a3ba-7ea9b6291cfd)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-192-849-merge-2023-07-06T04-11-18.ipa

Validation passed.
