### ISSUE TITLE
Error page in adding watch-only account screen

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#833]
Describe the bug
Version test: v1.0.6(186)
Devices test: IP 11

To reproduce the bug
Steps: 
1. Go to Attach watch-only account screen
2. Input invalid account address
3. Touch Enter on the keyboard and observe the displayed screen

Actual: Error page

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/3c508fcb-42ca-4c03-92fb-233c37d44d5e

**Comment by saltict** [comment]
Can not input after scan address successfully

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.9
Devices test: IP 11

@Quangdm-cdm please re-check the issue in case delete account address

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-197-866-merge-2023-07-11T03-29-45.ipa
Devices test: IP 11
Validation passed.
