### ISSUE TITLE
Show incorrect some information on the XCM history detail

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#841]
**Describe the bug**
Show incorrect some information on the XCM history detail

**To reproduce the behavior:**
Steps:
1. Perform a XCM transaction successfully (Receiver and Sender on same wallet)
2. On the result screen, click on "View history" to open the History detail
3. Observe the Destination Chain fee displayed
4. Switch to All accounts mode
5. Go to the History screen then observe the 2 history

**Actual:**
- Step 3: The Destination Chain Fee show incorrect

![Image](https://user-images.githubusercontent.com/130966515/249677632-649a1619-5c44-47b1-b126-b54e3f79ae69.png)

- Step 5: On the Receiver's history, show incorrect Sender Network

![Image](https://user-images.githubusercontent.com/130966515/249678015-49c91f31-9030-44a2-ab1c-c255aef185c8.png)

**Expect:**
- Step 3: Hide the Destination Chain Fee
- Step 5: Show correct Sender network

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-188-848-merge-2023-06-30T06-42-58.ipa
Validation passed.
