### ISSUE TITLE
Allow DApp access to watch-only account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#842]
**Describe the task**
Allow DApp access to watch-only account

Expect: Allow dApp access to watch-only account

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-192-858-merge-2023-07-03T05-26-09.apk

- [ ] Update message 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/4011be54-5e4e-4236-89b6-8ba9f783f3a1)

- [ ] UI bug

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/04e51a61-909d-49e9-9d9f-7e573f423521)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-192-858-merge-2023-07-06T03-18-45.apk
Devices test: IP 11
Validation passed.
