### ISSUE TITLE
Add the warning message in case XCM transfer

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#843]
**Describe the task**
Add the warning message in case XCM transfer
- Reference the design on extension: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=1620-98015&mode=design&t=Fzm1YWNs5q7i3v7R-4

![Image](https://user-images.githubusercontent.com/130966515/249682826-813b982a-ffca-44ba-9584-e9bde8daa15c.png)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-226-1086-merge-2023-10-21T03-45-38.apk
Device test: Samsung S20 FE 5G

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/a4dcdbeb-12ad-409e-846e-046377ea4d2d)
