### ISSUE TITLE
Change "show zero balance" default from turn on to turn off

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Mobile#846]
- Change default option of "show zero balance" from turn on to turn off

**Comment by ThaoNguyen998** [comment]
@saltict Please check the issue: The default option Show zero balance turn on in case Install https://share.icloud.com/photos/04bJA7GVRuM0x9COb0S3ven6w

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.7(189)
Devices test: IP 11
Validation passed.
