### ISSUE TITLE
UI bug in case create new account when connect Dapp

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#851]
To reproduce the bug

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/0aedf290-72e2-46d5-be68-336581de7bf9

**Comment by Quangdm-cdm** [comment]
This error is caused by the react-navigation library in iOS and it is very difficult to handle at the moment. Moreover, it does not affect the user experience too much.
