### ISSUE TITLE
Update UI - Header on list view

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#853]
Describe the task
- Update Header on list view follow by design

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-192-859-merge-2023-07-04T07-35-12.apk
Devices test: MI 8 Lite
Validation test.
