### ISSUE TITLE
Refactor - Bump deps

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Mobile#855]
Upgrade React Native from 0.71.1 to 0.71.12

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-200-888-merge-2023-07-17T05-02-28.ipa
Devices test: IP 11
Validation passed.
