### ISSUE TITLE
Implement Browser Predefined Data

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Mobile#856]
Please list all requirements of data for the browser DApps list that are required in browser features.

**Comment by nguyenduythuc** [comment]
- Load predefined dapps from this resource: https://static-data.subwallet.app/dapps/list.json
- Filter feature dapps to show

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-223-1067-merge-2023-10-11T05-51-12.ipa
Device test: IP 11

Validation passed.
