### ISSUE TITLE
Fix Browser issues

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Mobile#873]
@Sokol142196 please move all remaining issue of browser to this issue

- [x] Show incorrect dApp on Favorites list in case add favorites from Recent list
   Steps:
   1. Go to the Browser tab
   2. Access to connect.subwallet.app
   3. Access to another dApp
   4. Access to connect.subwallet.app again
   5. On the Recent list, click on "Add favorite" for the connect.subwallet.app 
   6. Go to the Favorites list then observe the connect.subwallet.app 

   Actual: the favorite status of the "connect.subwallet.app" = OFF
https://share.icloud.com/photos/05d-Z_mkm1yjjJ4VvDLCLBr3Q
- [x] Improve performance in case search
- [x] Allow user search by dApp name and dApp URL
- [x] Show incorrect connection status after connecting dApp successfully
   Steps:
   1. Go to the Browser tab
   2. Visit to "alephzero.artzero.io"
   3. Connect dApp successfully
   4. Observe the connection status 
   
   Actual: Connection status = Disconnected
https://share.icloud.com/photos/0bc3jULnVM0m7IfjYx964TACw

   Expect: Connection status = Connected

- [x] Update background of the web-view
- [x] UI bug confirmation screen

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/8cea616e-0cbd-4060-92bf-f9cdf58f22f9)
- [x] Recent list
  
     - [x] Improve: Still save the recent multi-time although user access to the old recent 
 ![image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/f5f81483-64f1-4cd3-bd71-0fd8a2b4151c)
 Expect: Only 1 item

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.9(197)
Devices test: IP 11
Validation passed.
