### ISSUE TITLE
Improve list performance (round 2nd)

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Mobile#874]
Check and improve all list performance in mobile-app.
Please listing all of screen need to be changed in this issue. Notice (focus on crypto, nft, staking and browser and some field that implement big list like select token, select network....)

**Comment by nguyenduythuc** [comment]
Screens to be improved performance:
[ ] Select token modal
[ ] Nft Collections
[ ] Browser Home
[ ] Browser Categories

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-204-923-merge-2023-07-29T02-06-38.ipa


Validation passed.

Continue to improve in Round 3
