### ISSUE TITLE
Update UI - Add the sort for the Select Pool/Validator/Collator/dApp screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#875]
**Describe the task**
Add the sort for the Select Pool/Validator/Collator/dApp screen

Design:
- https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3589-160581&mode=design&t=QxSXytdeYLFFsQ4Q-4
- https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3589-159578&mode=design&t=QxSXytdeYLFFsQ4Q-4

- Filter criteria: reference extension @ThaoNguyen998 please help me specific for @Quangdm-cdm

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-197-883-merge-2023-07-11T11-11-29.ipa
Devices test: IP 11

- [ ] Do not reset criteria in case open Select validator again
- [ ] Update UI Sorting screen follow by design

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-197-883-merge-2023-07-12T08-54-53.ipa
Devices test: IP 11
Validation passed.
