### ISSUE TITLE
Still show Token detail screen when switch account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#879]
**Describe the bug**
Still show Token detail screen when switch account

**To reproduce the behavior**
Steps:
1. Open the app
2. Switch to Substrate account
3. Click on any token to go to Token detail screen
4. Click on Send button
5. On the Send fund screen, switch to EVM account
6. Observe the screen displayed

**Actual:** Still show Token detail - empty page

https://user-images.githubusercontent.com/130966515/252620679-7a5cedda-a59b-4099-b998-e71b1f659fbe.MP4

**Expect:** Back to Homepage (Token tab)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-197-887-merge-2023-07-12T07-29-37.ipa
Devices test: IP 11
Validation passed.
