### ISSUE TITLE
Bugs when click on actions on header when standing transaction screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#880]
**Describe the bug**
Bugs when click on actions on header when standing transaction screen

**To reproduce the behavior**
Steps:
1. Go to the Send fund/ Send NFT/ Staking
2. Input valid data for the all fields
3. Click on Transfer/Submit button
4. While transaction is submitting, click on Setting/Scan QR/Switch account button
5. Back to transaction then observe

Actual: 

- [x] Transaction does not send, does not move to the next screen
- [x] Crash app in case click on Setting button when standing on Send NFT screen

Expect: Blur all action when submitting

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-198-890-merge-2023-07-13T02-45-35.ipa
Devices test: IP 11

@Quangdm-cdm Please re-check: Not blur all action when submitting

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-198-890-merge-2023-07-13T07-27-15.ipa
Devices test: IP 11
Validation passed.
