### ISSUE TITLE
Fix Browser issue (continue)

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#885]
- [x] Update banner image
- [x] Re-check case do not refresh the page

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-197-878-merge-2023-07-12T03-53-38.ipa

Please check:

- [ ] Show incorrect list by category on the Favorites list


![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/13528e6e-48f9-4b07-bd69-79f8bc0a1df5)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-198-893-merge-2023-07-13T06-18-19.ipa
Devices test: IP 11
Validation passed.
