### ISSUE TITLE
Small UX Suggestion: Ignore case when typing in seed phrase

### ISSUE THREAD

**Issue by wilwade** [Koniverse/SubWallet-Mobile#897]
I typed in my seed phrase, but the phone keyboard automatically capitalized the first word. That invalidated the seed phrase.

Suggested Solution: Ignore casing and automatically lowercase the seed phrase import when processing the field value

Platform: Android 10
Version: v1.0.10 (199)

**Comment by saltict** [comment]
> I typed in my seed phrase, but the phone keyboard automatically capitalized the first word. That invalidated the seed phrase.
> 
> Suggested Solution: Ignore casing and automatically lowercase the seed phrase import when processing the field value
> 
> Platform: Android 10 Version: v1.0.10 (199)

Hi @wilwade,

Many thanks for your feedback. I pushed it to our issues list to fix.

Have a nice day!

**Comment by nguyenduythuc** [comment]
Will be fixed in issue #898
