### ISSUE TITLE
Fix browser issues

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#898]
Describe the bug
Version test: v1.0.9(199)
Devices test: IP 11

- [x] UI bug 

![Image](https://user-images.githubusercontent.com/117999489/253740657-7a183b1e-3766-495e-a9c5-b28fd2e090fe.png)

- [x] Show incorrect list favorite in case the criteria is not dApp

![Image](https://user-images.githubusercontent.com/117999489/253740859-8ebe8de5-849b-4a23-8124-86a3a4c29c91.png)

- [x] Update favicon for dapp

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-203-908-merge-2023-07-21T10-07-08.ipa

Please fix issue:

- [ ] Still add to favorites for the "search duckduckgo" item"
  - Expect: Disable/Hide this option
![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/80213024-4dc3-457a-acfe-b60a882c2fff)

**Comment by Sokol142196** [comment]
- [ ] Do not displayed favorite site after add to favorite from dApp detail

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-203-908-merge-2023-07-24T10-53-03.ipa

Validation passed
