### ISSUE TITLE
Fix bug UI on Android

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#909]
Describe the bug

- [x] Create a master password

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/fba94078-f6e7-417b-970a-2d71e34286e2)

- [x] Select validator

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/50a3649c-798f-43a7-b954-dba5ce5badf8)

**Comment by Sokol142196** [comment]
@nguyenduythuc please check case 3
