### ISSUE TITLE
Auto update notification

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Mobile#913]
Display an alert notifying users that a new version is available and assisting users in updating to the latest version:
   - Notify the user if the current version is lower than the latest version as Modal. The Modal will include Title, Content, Action
     - The Content section will include the ChangeLogs and the Link to GithubPage
       - ChangeLog will display as a list according to each version 
       - The link to the Github page will show all ChangeLogs.
     - The Action section will have 2 actions: Cancel and Update.
       - Cancel action will keep the user in the current version.
       - Update action will support users depending on the Platform.
         -  IOS: open Appstore. 
         - Android:  if the app is installed from the PlayStore, it will open the PlayStore. If the app is installed from an APK version, it will support users to download the APK version and install it.

Round 1: 
 - [x] Check app installed from Play Store or sideload APK
 - [x] Get and check lastest version, get ChangeLogs data from github, 
 - [x] Show alert update app
 - [x] If app install from Playstore, click Update button will open AppStore or GooglePlay,...
 - [x] If app installed from sideload APK, click Update btn will download APK and install from inside of the App

Round 2: 
- Get and check lastest version, get ChangeLogs data from static content

Round 3: 
- Consider to get and check lastest version, get ChangeLogs data from WebRunner

**Comment by nguyenduythuc** [comment]
- [ x ] Check app installed from Play Store or sideload APK
- [ x ] Get and check lastest version from github
- [  ] Show alert update app
- [ x ] Download APK and install from inside of the App

**Comment by ThaoNguyen998** [comment]
Test on version 239

**Comment by ThaoNguyen998** [comment]
Version test: PR #964 15:56 15/11/2023
Device test: S20 FE 5G

- [ ] Not updating the app when clicking the update button in the notification when there is a new version
Steps:
1. Open SubWallet app
2. On the popup update version, click on Update button
3. Observe the displayed screen

Actual: Not updating the app when clicking the update button in the notification when there is a new version

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/c47f29b0-17d7-4fb4-8ea5-a798575530af

Expect: Auto update app to the newest version

- [ ] Still show popup update version when re-open app
Steps: 
1. Open SubWallet app
2. On the popup update version, click on Cancel
3. Close app and re-open app
4. Observe the displayed screen

Actual: Still show popup update version

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/a296e3e1-c06a-4be6-95b7-f28ffea6cbbb

Expect: Do not show popup update version

- Disscus more: Add checkbox "Don't show again"

**Comment by nampc1** [comment]
We want to show version update in the same modal as marketing campaign. The Update button will redirect to Github release note 
Will be resolved in #1546
