### ISSUE TITLE
Update link some dApp on Recommended list

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#914]
**Describe the task**
Update link some dApp on Recommended list
 
- [x] Replace: "https://alephzero.artzero.io"  to "https://a0.artzero.io"
- [x] Add the "https://a0.inkwhale.net"

**Comment by nguyenduythuc** [comment]
@Sokol142196 This issue will be fixed in #898

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-203-908-merge-2023-07-24T09-06-39.ipa

Validation passed
