### ISSUE TITLE
UI bugs on the NFT list screen (Android device)

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#915]
**Describe the bug**
UI bugs on the NFT list screen (Android device)

**Comment by Sokol142196** [comment]
Android device:
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-204-916-merge-2023-07-26T09-51-00.apk

Validation passed.

------
IOS device
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-204-916-merge-2023-07-26T09-53-40.ipa
Device: IP 8 Plus (15.5)

Please kindly check:

- [ ] UI bug

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/bb85ca76-f0cb-4d4e-bd64-d93a9e9567e3)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-205-916-merge-2023-08-10T06-03-47.apk
Device test: Mi 8 lite
Validation passed.
