### ISSUE TITLE
Update UI - Update show/hide balance feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#917]
**Describe the task**
Update UI - Update show/hide balance feature

Actual: 
- Only apply for show/hide on the Token list

Expect: 
- Apply more:
  - Staking
  - Crowdloan
  - History

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-210-990-merge-2023-08-26T10-40-27.apk
Device test: Samsung S20 FE 5G

Validation passed.
