### ISSUE TITLE
Record the address entered from the view-only account screen attached to the recent address in the address book

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#918]
**Describe the bug**

- [x] Case 1: Record the address entered from the watch-only account screen attached to the recent address in the address book

To reproduce the behavior
Steps:
1. Go to the attach watch-only screen
2. Scan or input address for the address field
3. Touch on attach
4. Go to the Manage address book screen
5. Observe the recent list

Actual: The address entered from the watch-only account screen attached to the recent list
- Record file: https://share.icloud.com/photos/02cVOsF1cjenikq-INSNT87CQ

Expect: Do not save

-----

- [x] Case 2: Still save the invalid address to the recent list 
   - Expect: Only save the valid address

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-220-1033-merge-2023-09-21T09-53-52.ipa
Device test: IP 11

Validation passed
