### ISSUE TITLE
Show the import account by JSON file screen when switch account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#919]
**Describe the bug**
Show the import account by JSON file screen when switch account

**To reproduce the behavior**
Steps:
1. Open the app after installed successfully
2. Perform import multi account by JSON file
3. After imported successfully, go to the send fund screen
4. Stand on Send fund screen and switch account on header
5. Observe the screen displayed

**Actual:** Show the import account by JSON file screen
  - Record file: https://share.icloud.com/photos/027C5hqYV69TEAZuIn1r_FBWg
  
**Expect**: Switch account successfully and navigate user to the homepage

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.4(227)
Device test: Samsung S20 FE 5G

I can't reproduce this bug on the newest version
