### ISSUE TITLE
Support sort token by value

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#920]
**Describe the task**
Create sort order option: Sort by value ($balance)

Implement sort the order of tokens displayed in the list:

- [x] Token list (Token tab, Token list by chain, search token)
- [x] Crowdloans
- [x] Staking

**Comment by ThaoNguyen998** [comment]
Version test: 
Android: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-207-952-merge-2023-08-15T09-13-30.apk
IOS: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-207-952-merge-2023-08-15T09-16-32.ipa
Devices test: IP 11, MI 8 Lite

Validation passed.
