### ISSUE TITLE
Allow reload NFT, staking in case the list is empty

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#927]
**Describe the task**
Allow reload NFT, staking in case the list is empty

**Actual:** In case the list NFT/ list staking is empty -> can not reload data
**Expect:** Allow reload

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-978-merge-2023-08-23T08-03-16.ipa
Device test: IP 11

Validation passed.
