### ISSUE TITLE
Replace all native modal to javascript modal (round 1)

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#928]
* React Native Modal makes nested modal complexity, then we should replace all modal to javascript modal (except: Login, Confirmation, Enter Master Password modal).

- First round modals:

> - [ ] Received modal

- Second round modals:

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-205-911-merge-2023-08-07T02-44-00.apk
Devices test: IP 11

- [ ] Bug keyboard overlapped modal

- [ ] UI bug on Android
![image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/a4086251-a106-4ece-906c-108f78861c58)

- [ ] UI bug Scan QR screen in case import account
![image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/d858fc2e-e914-4ddb-b070-ef7fd799c14a)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-205-937-merge-2023-08-11T10-24-54.ipa
Devices test: IP 11
Validation passed.
