### ISSUE TITLE
Update web-runner version 1.1.7

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Mobile#930]
Please check these tasks:
- https://github.com/Koniverse/SubWallet-Extension/issues/1554
- https://github.com/Koniverse/SubWallet-Extension/issues/1746 (Contact to @S2kael for get env fro build)

**Comment by saltict** [comment]
Testing on branch upgrade-ui

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-205-937-merge-2023-08-11T08-33-23.ipa
Devices test: IP 11
Validation passed.
