### ISSUE TITLE
Update showing minimum active value on mobile app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#931]
**Describe the task**
Update showing minimum active value

**Actual:** On the add to bond screen, minimum active = Min stake of chain

![Image](https://user-images.githubusercontent.com/130966515/258965238-cadeae74-b5b1-45d0-8ddb-c049b43bda70.png)

**Expect:** Minimum active = Max (MinStakeChain, MinStakeValidator)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-969-merge-2023-08-21T08-53-54.ipa
https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-969-merge-2023-08-21T08-50-57.apk
Devices test: IP 11, MI 8 Lite

Validation passed.
