### ISSUE TITLE
Update showing staking account on the Staking detail screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#932]
**Describe the task**
Update showing staking account on the Staking detail screen

**Actual:** Number of accounts = all accounts in the wallet

![Image](https://user-images.githubusercontent.com/130966515/253716667-f480f57d-6d6d-4a42-8054-c9f4eb397ea6.png)

**Expect:** Number of accounts = Number of accounts participating in staking (distinct pooled and nominated)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-983-merge-2023-08-24T11-01-20.ipa
Device test: IP 11

Validation passed.
