### ISSUE TITLE
Do not show validator on the Select validator screen in case turn on network when stake

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#933]
**Describe the bug**
Do not show validator on the Select validator screen in case turn on network when stake

**Expect:** Show the validator list after turn on network
_Refer: https://github.com/Koniverse/SubWallet-Extension/issues/1496_

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-974-merge-2023-08-22T08-52-47.ipa
Device test: IP 11

Validation passed.
