### ISSUE TITLE
Upgrade UI - Update sorting modal

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#935]
Describe the task
Update sorting modal follow by new design

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-207-958-merge-2023-08-16T10-41-56.ipa
Devices test: IP 11
Validation passed.
