### ISSUE TITLE
Do not delete connection when reset wallet

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#936]
**Describe the bug**
Do not delete connection (WalletConnect) when reset wallet

**To reproduce the behavior**
Steps:
1. Connected dApp via WalletConnect successfully
2. Perform reset wallet
3. After reset successfully, import account then re-open list connection of the WalletConnect

**Actual:** Still show connection
**Expect:** Delete connection when reset wallet

Follow-up: https://github.com/Koniverse/SubWallet-Extension/issues/1762

**Comment by Quangdm-cdm** [comment]
Recheck this issue in new version

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.15(210)
Device test: IP 11

Validation passed.
