### ISSUE TITLE
Bug related to WalletConnect feature

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#941]
Describe the bug

- [x] Wallet connect in-app browser

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/dde4440f-780b-4371-843a-fa950a79ca92

- [x] Do not show popup confirmation on some screen
   - [ ] Share address when Receive
   - [x] Current tab
   - [x] In case enable the keyboard

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/151fb7b5-a621-4b97-bd07-4d29497d46fb)

- [x] UI bug

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/5b338153-a82a-48fe-a4ee-c9bd76449be9)

- [x] Add effect when connecting
- [x] Enable avatar when selected account

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/0dfd34f5-caa3-4717-b75e-f00ddfeb548d)

**Comment by Quangdm-cdm** [comment]
@ThaoNguyen998 @sokol142 with issue  do not show popup confirmation when open Share modal, I think we can deal with it later because it's a rare case

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-207-946-merge-2023-08-15T11-50-48.apk

- [ ] Crash app when perform transactions from dApp via WalletConnect
https://share.icloud.com/photos/0bd-Iq7CdQ4eqOosynNTyBFaA

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-207-946-merge-2023-08-16T04-34-43.apk
Devices test: Samsung S20 FE 5G
