### ISSUE TITLE
UI bug on the Welcome screen on Huawei device

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#943]
**Describe the bug**
UI bug on the Welcome screen on Huawei device

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/5a200154-f049-4514-b9ca-839251a59b50)

**Comment by ThaoNguyen998** [comment]
Version test: v1.0.15(211)
Device test: Huawei

Validation passed.
