### ISSUE TITLE
Add dApps to Predefined List

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-Mobile#945]
Please add the following dApps to our predefined list on SubWallet mobile:
1. HEAL-III
https://heal3.com/
2. Oxalus
https://oxalus.io/
3. Birdeye
https://birdeye.so/
4. Ink Whale
https://www.inkwhale.net/#/

Thank you!

**Comment by Mabel-Nguyen** [comment]
Please also help add this dApp @Sokol142196 @Quangdm-cdm 
4. Ink Whale
https://www.inkwhale.net/#/

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-207-957-merge-2023-08-16T04-46-43.ipa
Devices test: IP 11
Validation passed.
