### ISSUE TITLE
Support fiat on-ramp with Banxa on mobile app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#950]
**Describe the task**
Support fiat on-ramp with Banxa on mobile app

- Related issue: https://github.com/Koniverse/SubWallet-Extension/issues/1084

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-215-upgrade-ui-2023-09-18T10-56-05.apk
Device test: Samsung S20 FE 5G
