### ISSUE TITLE
Update web runner 1.1.8

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#953]
Update web runner 1.1.8
Bump relate packages in package.json

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-207-954-merge-2023-08-15T09-48-41.ipa
Devices: IP 11

Validation passed.
