### ISSUE TITLE
The $value of the staking item is displayed incorrectly

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#955]
**Describe the bug**
The $value of the staking item is displayed incorrectly

![Image](https://user-images.githubusercontent.com/130966515/260699412-84a5e590-6a37-4ee9-ba44-a66d04685d30.png)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-968-merge-2023-08-18T03-56-04.ipa
Devices test: IP 11
Validation passed.
