### ISSUE TITLE
Do not reset validator/collator/dApp in case change token to nominate

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#956]
**Describe** the bug
Do not reset validator/collator/dApp in case change token to nominate

**To reproduce the behavior**
Steps:
1. Go to the Add to bond screen
2. Select any token (example: DOT) then select validator
3. After selected validator, user change token to another token
4. Observe the selected validator displaying

**Actual:** Do not reset validator

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/dd3db81f-7d3f-4b8b-959b-1abe9aeba1b0)

**Expect:** Reset validator/collator/dApp wwhen change token

**Comment by ThaoNguyen998** [comment]
- [ ] Bug when the re-select validator
Steps: 
1. Go to the Staking screen
2. Select any validator
3. Re-select the validator and observe the displayed screen
Actual: Do not show the validator selected

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-974-merge-2023-08-22T08-52-47.ipa
Device test: IP 11

Validation passed.
