### ISSUE TITLE
Support domain name for mobile app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#960]
**Describe the task**
Support domain name for mobile app
- Refer: https://github.com/Koniverse/SubWallet-ChainList/issues/40

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-985-merge-2023-08-26T05-08-37.apk
Device test: MI 8 Lite

Validation passed.
