### ISSUE TITLE
Show collection ID and NFT Id in the NFT detail screen for mobile app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#961]
**Describe the task**
Show collection ID and NFT Id in the NFT detail screen for mobile app

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-223-1065-merge-2023-10-09T08-25-15.ipa

@Quangdm-cdm Please re-check this issue:
Show incorrect Collection ID, NFT Id

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/091c498d-d6a7-4903-85e9-2d38ce6946b5)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-223-1065-merge-2023-10-11T03-39-43.ipa
Device test: IP 11

Validation passed.
