### ISSUE TITLE
Do not display NFT after import NFT successfully

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#965]
Describe the bug
Do not display NFT when import NFT successfully

To reproduce the bug
Steps: 
1. Open Subwallet app
2. Perform import NFT successfully
3. Observe the displayed screen 
4. Close app and then re-open app

Actual: 
- In step 3: Do not display NFT although import successfully
- In step 4: Display NFT

**Comment by Sokol142196** [comment]
@ThaoNguyen998 please reproduce this bug then feedback for @nguyenduythuc

**Comment by ThaoNguyen998** [comment]
@nguyenduythuc Please re-check this issue, I still reproduce this bug
https://share.icloud.com/photos/055WQm9BHDf6MCVHUN2AFJ4aQ

**Comment by nguyenduythuc** [comment]
Will be fixed in #977

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-979-merge-2023-08-25T10-27-55.ipa
Device test: IP 11

Validation passed.
