### ISSUE TITLE
Update Receive icon to Copy icon

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#970]
**Describe the task**

- [x] Update Receive icon to Copy button
- [x] Update text from "Receive" to "Address"

Reference SubWallet extension

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-971-merge-2023-08-21T01-53-07.ipa
Device test: IP 11

Validation passed.
