### ISSUE TITLE
Support multi-language for WalletConnect feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#973]
**Describe the task**
Support multi-language for WalletConnect feature

**Comment by Quangdm-cdm** [comment]
Support multi-language for Validator Selector Empty list

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-982-merge-2023-08-24T10-12-15.ipa

- [ ] Wallet connect

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/ec7e9205-a1b7-4814-b5e4-cd84ddf8572f)


- [ ] Select collator

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/945f7fa1-593b-47be-a040-bee7fcde453c)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-upgrade-ui-2023-08-26T04-52-37.ipa
Device test: IP 11

Validation passed.
