### ISSUE TITLE
Still show popup turn on network in case change Pool  to Nominate

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#975]
**Describe the bug**
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-974-merge-2023-08-21T11-06-00.ipa
Devices test: IP 11

**To reproduce the bug**
Pre-condition: Config Require unlock = Always
Steps
1. Go to Add Staking screen
2. On the Pools tab, select the token turn off
3. Touch button Connect 
4. Perform change Pool to Nominate and observe the displayed screen

Actual: 
In step 2: Show popup Enable chain
In step 4: Still show popup Enable chain

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/004055f1-1ff9-4222-8805-373dfd9effb7

Expect: Do not show popup Enable chain

**Comment by NnajiChimuanya** [comment]
Can you add a picture to better describe

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-210-991-merge-2023-08-26T10-49-27.apk
Device test: Samsung S20 FE 5G

- [ ] Still reproduce this bug on Android

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-215-991-merge-2023-09-13T03-53-42.ipa
Device test: IP 11

Validation passed.
