### ISSUE TITLE
Incorrect token price display (JOY)

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#976]
**Describe the bug**
- Incorrect token price display (JOY)
- Re-check all token

![Image](https://user-images.githubusercontent.com/130966515/262208725-c8c61734-713a-4b99-ad00-f601d944a7c9.png)

**Comment by saltict** [comment]
The problem is because of price cache services. It has been fixed, @Sokol142196 please check it again.

**Comment by Sokol142196** [comment]
@saltict I verified that the issue was passed so I closed the issue and continued to follow up
