### ISSUE TITLE
Update web-runner for mobile (extension - v1.1.9)

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#977]
**Describe the task**
Update web-runner for mobile (extension - v1.1.9)

**Comment by ThaoNguyen998** [comment]
@nguyenduythuc Please re-check this issue

- [ ] Do not show NFT after import successfully
5D2ujd1quLvo3EHS6G1g1gwgC6H6czYAuDdJgNwhtieAFBZb - a0 testnet(BD)
5FsB91tXSEuMj6akzdPczAtmBaVKToqHmtAwSUzXh49AYzaD - a0 testnet( BD)

**Comment by nguyenduythuc** [comment]
@saltict Please check this issue

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-979-merge-2023-08-25T10-27-55.ipa
Device test: IP 11

Validation passed.
