### ISSUE TITLE
Follow up show dApp's logo in svg in Browser and dApp confirmations

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#980]
- Show logo from predefined dapps if exist.
- If not exist in dapps, trying to show favicon.ico, favicon.png, favicon.svg

**Comment by ThaoNguyen998** [comment]
Version test: PR 1087 13:12 04/11/2023
Device test: IP 11

Validation passed. 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/9214cf80-ec26-4bea-b09e-85e6f882e60c)
