### ISSUE TITLE
Bugs related to Send NFT

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#986]
**Describe the bug**
Bugs related to Send NFT
To reproduce the bug with BD account

- [x] Show incorrect message when input invalid recipient address
- [x] Still send NFT when input invalid recipient address

![Image](https://user-images.githubusercontent.com/130966515/263270833-0fcae189-67d0-48b4-a610-186f8ed820f0.gif)

- [ ] Update style of the Send button

![Image](https://user-images.githubusercontent.com/130966515/263271157-50162de1-586a-46be-bbe5-e5b3c211d04d.png)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-987-merge-2023-08-26T07-46-00.apk
Device test: Samsung S20 FE 5G

- [ ] Still show incorrect message when input invalid recipient address

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/827440a3-54f3-4947-ae8b-f1feaef93036)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-212-987-merge-2023-09-06T08-55-27.apk
Devices test: MI 8 Lite

- [ ] Please update style of the Send button
