### ISSUE TITLE
Fix static server to support cors

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#988]
The app is using react-native-static-server to serve background. But currently, the library's having so much errors about cors. We have to fix it or find some alternative library

**Comment by nguyenduythuc** [comment]
The library react-native-static-server is continuing support in @dr.pogodin/react-native-static-server. We have to update WebRunner config file. We need to test these flow to make sure the app works correctly:

- Get data from background: Token, Price, Balance, NFTs, Staking, Confirmation
- Import from json
- Browser tab

**Comment by ThaoNguyen998** [comment]
@nguyenduythuc Please re-check this issue
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-211-994-merge-2023-08-28T08-19-45.ipa
Device test: IP 11 

- [ ] Do not show token list in case import multi-account

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-213-994-merge-2023-09-08T03-32-12.ipa
Device test: IP 11

- [ ] Bug when import from Polkadot.{js} 

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/9fa630e8-e11c-4559-a522-580ff64e33a2

https://drive.google.com/file/d/1hUmcoljbCUwUr9f2mWvc4d3QMSzLdcJg/view?usp=sharing

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-220-994-merge-2023-09-25T03-18-22.apk
Device test: Mi 8 Lite

@nguyenduythuc Please re-check the bug on Android
https://github.com/Koniverse/SubWallet-Mobile/issues/988#issuecomment-1715284280

- [ ] UI bug

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/2ab50c52-a4c5-4653-90e3-37ca3b333243)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-221-994-merge-2023-09-27T05-21-14.apk
Device test: Samsung S20 FE 5G

Validation passed.
