### ISSUE TITLE
Add the button on the empty list (mobile app)

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#995]
**Describe the task**
Add the button on the empty list

- [x] List NFT Collection: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3312-159538&mode=design&t=uro0UVEC4rvIPi8A-4
- [x] List staking: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=10208-591666&mode=design&t=uro0UVEC4rvIPi8A-4
- [x] List token: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=5809-142566&mode=design&t=uro0UVEC4rvIPi8A-4

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-218-1029-merge-2023-09-20T11-39-04.ipa
Device test: IP 11

- [ ] Add the button empty list 
  - [ ] Search token to get address
  - [ ] Search network in case have no result (Manage network, customize asset display)
- [ ] Do not navigate to Import token when touch the button when search the token on the header
- [ ] Handle the case where you have to press twice to switch screens

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-220-1029-merge-2023-09-26T03-57-56.ipa
Device test: IP 11

- [ ] Can't navigate Import network on customize asset display screen

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-220-1029-merge-2023-09-26T04-59-19.ipa
Device test: IP 11

Validation passed.

**Comment by ThaoNguyen998** [comment]
@Quangdm-cdm Please re-check this issue: 

- [ ] Navigate incorrect in case search token to get address (All account)
Actual: Navigate to the Select Account screen
Expect: Navigate to Import token

- [ ] Can't navigate in case select token when stake

**Comment by Sokol142196** [comment]
@Quangdm-cdm please update the message on empty list following this page: https://www.notion.so/subwallet/Empty-state-e6f40f6f42c34b4fa0f0549bb262eb9c?pvs=4


![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/130966515/317e6c8e-2bd8-4760-91bf-ab3ad736648d)
