### ISSUE TITLE
Show duplicate toast No internet connection in case the first install app

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#996]
**Describe the bug**

Version test: https://file.cdmteck.com/s/DB9JLAnjJczopcC/download?path=%2F&files=SubWalletMobile-build-209-984-merge-2023-08-26T08-33-23.ipa
Devices test: IP 11

- [x] Still show duplicate toast 

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/4c6dd43b-1c3c-4201-8e6a-6eadea262be5)

**Comment by Quangdm-cdm** [comment]
Can't reproduce this bug. Please check and close this issue

**Comment by ThaoNguyen998** [comment]
Can't reproduce this bug on the lastest version -> Close issue
